// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ped_alg,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.130750,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=101,HLS_SYN_LUT=443,HLS_VERSION=2020_1}" *)

module ped_alg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ped_val_i,
        ped_val_o,
        ped_val_o_ap_vld,
        accum_i,
        accum_o,
        accum_o_ap_vld,
        ADC_i,
        ADC_o,
        ADC_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ped_val_i;
output  [31:0] ped_val_o;
output   ped_val_o_ap_vld;
input  [31:0] accum_i;
output  [31:0] accum_o;
output   accum_o_ap_vld;
input  [31:0] ADC_i;
output  [31:0] ADC_o;
output   ADC_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ped_val_o;
reg ped_val_o_ap_vld;
reg[31:0] accum_o;
reg accum_o_ap_vld;
reg ADC_o_ap_vld;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] ADC_read_reg_203;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln17_1_fu_157_p2;
wire   [31:0] select_ln17_fu_163_p3;
wire   [31:0] add_ln34_fu_183_p2;
wire   [0:0] icmp_ln27_fu_171_p2;
wire   [0:0] icmp_ln33_fu_177_p2;
wire   [31:0] add_ln28_fu_190_p2;
wire   [0:0] ap_phi_mux_accum_flag_2_phi_fu_89_p6;
reg   [0:0] accum_flag_2_reg_85;
reg   [31:0] accum_new_2_reg_99;
reg   [31:0] ped_val_load_3_reg_114;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln21_fu_137_p2;
wire   [31:0] add_ln22_fu_143_p2;
wire   [0:0] icmp_ln17_fu_125_p2;
wire   [31:0] add_ln18_fu_131_p2;
wire   [31:0] select_ln21_fu_149_p3;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_177_p2 == 1'd0) & (icmp_ln27_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        accum_flag_2_reg_85 <= icmp_ln17_1_fu_157_p2;
    end else if ((((icmp_ln27_fu_171_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln33_fu_177_p2 == 1'd1) & (icmp_ln27_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        accum_flag_2_reg_85 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_177_p2 == 1'd0) & (icmp_ln27_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        accum_new_2_reg_99 <= select_ln17_fu_163_p3;
    end else if ((((icmp_ln27_fu_171_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln33_fu_177_p2 == 1'd1) & (icmp_ln27_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        accum_new_2_reg_99 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((icmp_ln33_fu_177_p2 == 1'd0) & (icmp_ln27_fu_171_p2 == 1'd0))) begin
            ped_val_load_3_reg_114 <= ped_val_i;
        end else if (((icmp_ln33_fu_177_p2 == 1'd1) & (icmp_ln27_fu_171_p2 == 1'd0))) begin
            ped_val_load_3_reg_114 <= add_ln34_fu_183_p2;
        end else if ((icmp_ln27_fu_171_p2 == 1'd1)) begin
            ped_val_load_3_reg_114 <= add_ln28_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ADC_read_reg_203 <= ADC_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ADC_o_ap_vld = 1'b1;
    end else begin
        ADC_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_accum_flag_2_phi_fu_89_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        accum_o = accum_new_2_reg_99;
    end else begin
        accum_o = accum_i;
    end
end

always @ (*) begin
    if (((ap_phi_mux_accum_flag_2_phi_fu_89_p6 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        accum_o_ap_vld = 1'b1;
    end else begin
        accum_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln27_fu_171_p2 == 1'd1)) begin
            ped_val_o = add_ln28_fu_190_p2;
        end else if (((icmp_ln33_fu_177_p2 == 1'd1) & (icmp_ln27_fu_171_p2 == 1'd0))) begin
            ped_val_o = add_ln34_fu_183_p2;
        end else begin
            ped_val_o = ped_val_i;
        end
    end else begin
        ped_val_o = ped_val_i;
    end
end

always @ (*) begin
    if ((((icmp_ln27_fu_171_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln33_fu_177_p2 == 1'd1) & (icmp_ln27_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        ped_val_o_ap_vld = 1'b1;
    end else begin
        ped_val_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ADC_o = (ADC_read_reg_203 - ped_val_load_3_reg_114);

assign add_ln18_fu_131_p2 = (accum_i + 32'd1);

assign add_ln22_fu_143_p2 = ($signed(accum_i) + $signed(32'd4294967295));

assign add_ln28_fu_190_p2 = (ped_val_i + 32'd1);

assign add_ln34_fu_183_p2 = ($signed(ped_val_i) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_phi_mux_accum_flag_2_phi_fu_89_p6 = accum_flag_2_reg_85;

assign icmp_ln17_1_fu_157_p2 = ((ADC_i != ped_val_i) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_125_p2 = (($signed(ADC_i) > $signed(ped_val_i)) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_137_p2 = (($signed(ADC_i) < $signed(ped_val_i)) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_171_p2 = (($signed(select_ln17_fu_163_p3) > $signed(32'd9)) ? 1'b1 : 1'b0);

assign icmp_ln33_fu_177_p2 = (($signed(select_ln17_fu_163_p3) < $signed(32'd4294967287)) ? 1'b1 : 1'b0);

assign select_ln17_fu_163_p3 = ((icmp_ln17_fu_125_p2[0:0] === 1'b1) ? add_ln18_fu_131_p2 : select_ln21_fu_149_p3);

assign select_ln21_fu_149_p3 = ((icmp_ln21_fu_137_p2[0:0] === 1'b1) ? add_ln22_fu_143_p2 : accum_i);

endmodule //ped_alg
