# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr.xci
# IP: The module: 'axis_register_slice_fr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_fr'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_fr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr.xci
# IP: The module: 'axis_register_slice_fr' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_fr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/axis_register_slice_fr/axis_register_slice_fr_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_register_slice_fr'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
