-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ped_alg is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ped_val_i : IN STD_LOGIC_VECTOR (31 downto 0);
    ped_val_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    ped_val_o_ap_vld : OUT STD_LOGIC;
    accum_i : IN STD_LOGIC_VECTOR (31 downto 0);
    accum_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    accum_o_ap_vld : OUT STD_LOGIC;
    ADC_i : IN STD_LOGIC_VECTOR (31 downto 0);
    ADC_o : OUT STD_LOGIC_VECTOR (31 downto 0);
    ADC_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ped_alg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ped_alg,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.130750,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=100,HLS_SYN_LUT=437,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_FFFFFFF7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111110111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ADC_read_reg_193 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln17_1_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_fu_153_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln32_fu_173_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln26_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln27_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_accum_flag_2_phi_fu_79_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_flag_2_reg_75 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_new_2_reg_89 : STD_LOGIC_VECTOR (31 downto 0);
    signal ped_val_load_3_reg_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln21_fu_127_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln22_fu_133_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln17_fu_115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln18_fu_121_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln21_fu_139_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    accum_flag_2_reg_75_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln31_fu_167_p2 = ap_const_lv1_0) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                accum_flag_2_reg_75 <= icmp_ln17_1_fu_147_p2;
            elsif ((((ap_start = ap_const_logic_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (icmp_ln31_fu_167_p2 = ap_const_lv1_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                accum_flag_2_reg_75 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    accum_new_2_reg_89_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (icmp_ln31_fu_167_p2 = ap_const_lv1_0) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                accum_new_2_reg_89 <= select_ln17_fu_153_p3;
            elsif ((((ap_start = ap_const_logic_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (icmp_ln31_fu_167_p2 = ap_const_lv1_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                accum_new_2_reg_89 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ped_val_load_3_reg_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if (((icmp_ln31_fu_167_p2 = ap_const_lv1_0) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0))) then 
                    ped_val_load_3_reg_104 <= ped_val_i;
                elsif (((icmp_ln31_fu_167_p2 = ap_const_lv1_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0))) then 
                    ped_val_load_3_reg_104 <= add_ln32_fu_173_p2;
                elsif ((icmp_ln26_fu_161_p2 = ap_const_lv1_1)) then 
                    ped_val_load_3_reg_104 <= add_ln27_fu_180_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ADC_read_reg_193 <= ADC_i;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ADC_o <= std_logic_vector(unsigned(ADC_read_reg_193) - unsigned(ped_val_load_3_reg_104));

    ADC_o_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ADC_o_ap_vld <= ap_const_logic_1;
        else 
            ADC_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    accum_o_assign_proc : process(accum_i, ap_phi_mux_accum_flag_2_phi_fu_79_p6, accum_new_2_reg_89, ap_CS_fsm_state2)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_79_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_o <= accum_new_2_reg_89;
        else 
            accum_o <= accum_i;
        end if; 
    end process;


    accum_o_ap_vld_assign_proc : process(ap_phi_mux_accum_flag_2_phi_fu_79_p6, ap_CS_fsm_state2)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_79_p6 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_o_ap_vld <= ap_const_logic_1;
        else 
            accum_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln18_fu_121_p2 <= std_logic_vector(unsigned(accum_i) + unsigned(ap_const_lv32_1));
    add_ln22_fu_133_p2 <= std_logic_vector(unsigned(accum_i) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln27_fu_180_p2 <= std_logic_vector(unsigned(ped_val_i) + unsigned(ap_const_lv32_1));
    add_ln32_fu_173_p2 <= std_logic_vector(unsigned(ped_val_i) + unsigned(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_accum_flag_2_phi_fu_79_p6 <= accum_flag_2_reg_75;

    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln17_1_fu_147_p2 <= "0" when (ADC_i = ped_val_i) else "1";
    icmp_ln17_fu_115_p2 <= "1" when (signed(ADC_i) > signed(ped_val_i)) else "0";
    icmp_ln21_fu_127_p2 <= "1" when (signed(ADC_i) < signed(ped_val_i)) else "0";
    icmp_ln26_fu_161_p2 <= "1" when (signed(select_ln17_fu_153_p3) > signed(ap_const_lv32_9)) else "0";
    icmp_ln31_fu_167_p2 <= "1" when (signed(select_ln17_fu_153_p3) < signed(ap_const_lv32_FFFFFFF7)) else "0";

    ped_val_o_assign_proc : process(ap_start, ap_CS_fsm_state1, ped_val_i, add_ln32_fu_173_p2, icmp_ln26_fu_161_p2, icmp_ln31_fu_167_p2, add_ln27_fu_180_p2)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
            if ((icmp_ln26_fu_161_p2 = ap_const_lv1_1)) then 
                ped_val_o <= add_ln27_fu_180_p2;
            elsif (((icmp_ln31_fu_167_p2 = ap_const_lv1_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0))) then 
                ped_val_o <= add_ln32_fu_173_p2;
            else 
                ped_val_o <= ped_val_i;
            end if;
        else 
            ped_val_o <= ped_val_i;
        end if; 
    end process;


    ped_val_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, icmp_ln26_fu_161_p2, icmp_ln31_fu_167_p2)
    begin
        if ((((ap_start = ap_const_logic_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (icmp_ln31_fu_167_p2 = ap_const_lv1_1) and (icmp_ln26_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ped_val_o_ap_vld <= ap_const_logic_1;
        else 
            ped_val_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln17_fu_153_p3 <= 
        add_ln18_fu_121_p2 when (icmp_ln17_fu_115_p2(0) = '1') else 
        select_ln21_fu_139_p3;
    select_ln21_fu_139_p3 <= 
        add_ln22_fu_133_p2 when (icmp_ln21_fu_127_p2(0) = '1') else 
        accum_i;
end behav;
