-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ped_alg is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ped_val_i : IN STD_LOGIC_VECTOR (15 downto 0);
    ped_val_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    ped_val_o_ap_vld : OUT STD_LOGIC;
    accum_i : IN STD_LOGIC_VECTOR (7 downto 0);
    accum_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    accum_o_ap_vld : OUT STD_LOGIC;
    ADC : OUT STD_LOGIC_VECTOR (15 downto 0);
    ADC_ap_vld : OUT STD_LOGIC;
    tdata : IN STD_LOGIC_VECTOR (15 downto 0);
    tvalid : IN STD_LOGIC;
    tkeep0 : IN STD_LOGIC;
    tkeep1 : IN STD_LOGIC;
    tready : IN STD_LOGIC );
end;


architecture behav of ped_alg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ped_alg,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.380750,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=52,HLS_SYN_LUT=282,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_F7 : STD_LOGIC_VECTOR (7 downto 0) := "11110111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal or_ln24_1_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_1_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_fu_197_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_reg_283 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln29_fu_201_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln29_reg_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ped_val_read_reg_294 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln35_fu_236_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln35_reg_302 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_accum_flag_2_phi_fu_132_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln45_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_1_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_accum_new_2_phi_fu_145_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln46_fu_266_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ped_val_load_3_phi_fu_159_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_fu_259_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln24_fu_167_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_173_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln24_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln24_fu_179_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln24_fu_179_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln24_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln24_1_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln39_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_fu_222_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln35_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln36_fu_210_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln39_fu_228_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                or_ln24_1_reg_279 <= or_ln24_1_fu_191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                ped_val_read_reg_294 <= ped_val_i;
                select_ln35_reg_302 <= select_ln35_fu_236_p3;
                    zext_ln29_reg_288(11 downto 0) <= zext_ln29_fu_201_p1(11 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (or_ln24_1_fu_191_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_reg_283 <= trunc_fu_197_p1;
            end if;
        end if;
    end process;
    zext_ln29_reg_288(15 downto 12) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, or_ln24_1_fu_191_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (or_ln24_1_fu_191_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_start = ap_const_logic_1) and (or_ln24_1_fu_191_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ADC <= std_logic_vector(unsigned(zext_ln29_reg_288) - unsigned(ap_phi_mux_ped_val_load_3_phi_fu_159_p6));

    ADC_ap_vld_assign_proc : process(or_ln24_1_reg_279, ap_CS_fsm_state3)
    begin
        if (((or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ADC_ap_vld <= ap_const_logic_1;
        else 
            ADC_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    accum_o_assign_proc : process(accum_i, or_ln24_1_reg_279, ap_phi_mux_accum_flag_2_phi_fu_132_p6, ap_CS_fsm_state3, ap_phi_mux_accum_new_2_phi_fu_145_p6)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_132_p6 = ap_const_lv1_1) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            accum_o <= ap_phi_mux_accum_new_2_phi_fu_145_p6;
        else 
            accum_o <= accum_i;
        end if; 
    end process;


    accum_o_ap_vld_assign_proc : process(or_ln24_1_reg_279, ap_phi_mux_accum_flag_2_phi_fu_132_p6, ap_CS_fsm_state3)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_132_p6 = ap_const_lv1_1) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            accum_o_ap_vld <= ap_const_logic_1;
        else 
            accum_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln36_fu_210_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(accum_i));
    add_ln40_fu_222_p2 <= std_logic_vector(signed(ap_const_lv8_FF) + signed(accum_i));
    add_ln46_fu_266_p2 <= std_logic_vector(unsigned(ped_val_read_reg_294) + unsigned(ap_const_lv16_1));
    add_ln51_fu_259_p2 <= std_logic_vector(unsigned(ped_val_read_reg_294) + unsigned(ap_const_lv16_FFFF));
    and_ln24_fu_179_p0 <= (0=>tkeep0, others=>'-');
    and_ln24_fu_179_p1 <= (0=>tkeep1, others=>'-');
    and_ln24_fu_179_p2 <= (and_ln24_fu_179_p1 and and_ln24_fu_179_p0);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_accum_flag_2_phi_fu_132_p6_assign_proc : process(or_ln24_1_reg_279, ap_CS_fsm_state3, icmp_ln45_fu_249_p2, icmp_ln50_fu_254_p2, icmp_ln35_1_fu_244_p2)
    begin
        if (((icmp_ln50_fu_254_p2 = ap_const_lv1_0) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_accum_flag_2_phi_fu_132_p6 <= icmp_ln35_1_fu_244_p2;
        elsif ((((icmp_ln50_fu_254_p2 = ap_const_lv1_1) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln45_fu_249_p2 = ap_const_lv1_1) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ap_phi_mux_accum_flag_2_phi_fu_132_p6 <= ap_const_lv1_1;
        else 
            ap_phi_mux_accum_flag_2_phi_fu_132_p6 <= "X";
        end if; 
    end process;


    ap_phi_mux_accum_new_2_phi_fu_145_p6_assign_proc : process(or_ln24_1_reg_279, select_ln35_reg_302, ap_CS_fsm_state3, icmp_ln45_fu_249_p2, icmp_ln50_fu_254_p2)
    begin
        if (((icmp_ln50_fu_254_p2 = ap_const_lv1_0) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_accum_new_2_phi_fu_145_p6 <= select_ln35_reg_302;
        elsif ((((icmp_ln50_fu_254_p2 = ap_const_lv1_1) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln45_fu_249_p2 = ap_const_lv1_1) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ap_phi_mux_accum_new_2_phi_fu_145_p6 <= ap_const_lv8_0;
        else 
            ap_phi_mux_accum_new_2_phi_fu_145_p6 <= "XXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_ped_val_load_3_phi_fu_159_p6_assign_proc : process(or_ln24_1_reg_279, ped_val_read_reg_294, ap_CS_fsm_state3, icmp_ln45_fu_249_p2, icmp_ln50_fu_254_p2, add_ln46_fu_266_p2, add_ln51_fu_259_p2)
    begin
        if (((or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
            if (((icmp_ln50_fu_254_p2 = ap_const_lv1_0) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_ped_val_load_3_phi_fu_159_p6 <= ped_val_read_reg_294;
            elsif (((icmp_ln50_fu_254_p2 = ap_const_lv1_1) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_ped_val_load_3_phi_fu_159_p6 <= add_ln51_fu_259_p2;
            elsif ((icmp_ln45_fu_249_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_ped_val_load_3_phi_fu_159_p6 <= add_ln46_fu_266_p2;
            else 
                ap_phi_mux_ped_val_load_3_phi_fu_159_p6 <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_ped_val_load_3_phi_fu_159_p6 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln35_1_fu_244_p2 <= "0" when (zext_ln29_reg_288 = ped_val_read_reg_294) else "1";
    icmp_ln35_fu_204_p2 <= "1" when (signed(zext_ln29_fu_201_p1) > signed(ped_val_i)) else "0";
    icmp_ln39_fu_216_p2 <= "1" when (signed(zext_ln29_fu_201_p1) < signed(ped_val_i)) else "0";
    icmp_ln45_fu_249_p2 <= "1" when (signed(select_ln35_reg_302) > signed(ap_const_lv8_9)) else "0";
    icmp_ln50_fu_254_p2 <= "1" when (signed(select_ln35_reg_302) < signed(ap_const_lv8_F7)) else "0";
    or_ln24_1_fu_191_p2 <= (xor_ln24_1_fu_185_p2 or or_ln24_fu_173_p2);
    or_ln24_fu_173_p0 <= (0=>tready, others=>'-');
    or_ln24_fu_173_p2 <= (xor_ln24_fu_167_p2 or or_ln24_fu_173_p0);

    ped_val_o_assign_proc : process(ped_val_i, or_ln24_1_reg_279, ap_CS_fsm_state3, icmp_ln45_fu_249_p2, icmp_ln50_fu_254_p2, add_ln46_fu_266_p2, add_ln51_fu_259_p2)
    begin
        if (((or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
            if ((icmp_ln45_fu_249_p2 = ap_const_lv1_1)) then 
                ped_val_o <= add_ln46_fu_266_p2;
            elsif (((icmp_ln50_fu_254_p2 = ap_const_lv1_1) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0))) then 
                ped_val_o <= add_ln51_fu_259_p2;
            else 
                ped_val_o <= ped_val_i;
            end if;
        else 
            ped_val_o <= ped_val_i;
        end if; 
    end process;


    ped_val_o_ap_vld_assign_proc : process(or_ln24_1_reg_279, ap_CS_fsm_state3, icmp_ln45_fu_249_p2, icmp_ln50_fu_254_p2)
    begin
        if ((((icmp_ln50_fu_254_p2 = ap_const_lv1_1) and (icmp_ln45_fu_249_p2 = ap_const_lv1_0) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((icmp_ln45_fu_249_p2 = ap_const_lv1_1) and (or_ln24_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ped_val_o_ap_vld <= ap_const_logic_1;
        else 
            ped_val_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln35_fu_236_p3 <= 
        add_ln36_fu_210_p2 when (icmp_ln35_fu_204_p2(0) = '1') else 
        select_ln39_fu_228_p3;
    select_ln39_fu_228_p3 <= 
        add_ln40_fu_222_p2 when (icmp_ln39_fu_216_p2(0) = '1') else 
        accum_i;
    trunc_fu_197_p1 <= tdata(12 - 1 downto 0);
    xor_ln24_1_fu_185_p2 <= (ap_const_lv1_1 xor and_ln24_fu_179_p2);
    xor_ln24_fu_167_p0 <= (0=>tvalid, others=>'-');
    xor_ln24_fu_167_p2 <= (xor_ln24_fu_167_p0 xor ap_const_lv1_1);
    zext_ln29_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_reg_283),16));
end behav;
