# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/fmc0_8chan_9g6.xci
# IP: The module: 'fmc0_8chan_9g6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/synth/fmc0_8chan_9g6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmc0_8chan_9g6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/synth/fmc0_8chan_9g6.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmc0_8chan_9g6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/fmc0_8chan_9g6.xci
# IP: The module: 'fmc0_8chan_9g6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/synth/fmc0_8chan_9g6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmc0_8chan_9g6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/fmc0_8chan_9g6/synth/fmc0_8chan_9g6.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmc0_8chan_9g6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
