# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/address_LUT/address_LUT.xci
# IP: The module: 'address_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/address_LUT/address_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'address_LUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/address_LUT/address_LUT.xci
# IP: The module: 'address_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data/kmanolo/Josh/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/address_LUT/address_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'address_LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
