create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[0]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[1]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[2]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[3]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[4]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[5]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[6]]
create_clock -period 4.167 [get_ports -no_traverse rxoutclk_out[7]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[0]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[1]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[2]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[3]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[4]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[5]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[6]]
create_clock -period 4.167 [get_ports -no_traverse txoutclk_out[7]]
create_generated_clock -source [get_ports gtrefclk01_in[0]] -edges {1 2 3} -edge_shift {0.000 -3.096 -6.192} [get_ports -no_traverse qpll1outclk_out[0]]
create_generated_clock -source [get_ports gtrefclk01_in[1]] -edges {1 2 3} -edge_shift {0.000 -3.096 -6.192} [get_ports -no_traverse qpll1outclk_out[1]]
create_generated_clock -source [get_ports gtrefclk01_in[0]] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports -no_traverse qpll1outrefclk_out[0]]
create_generated_clock -source [get_ports gtrefclk01_in[1]] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports -no_traverse qpll1outrefclk_out[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxn_in[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthrxp_in[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxn_out[7]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[0]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[0]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[1]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[1]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[2]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[2]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[3]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[3]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[4]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[4]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[5]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[5]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[6]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[6]]
set_property -quiet IO_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[7]]
set_property -quiet CLOCK_BUFFER_TYPE NONE [get_ports -quiet gthtxp_out[7]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 6.400 [get_ports -no_traverse -quiet gtrefclk01_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 6.400 [get_ports -no_traverse -quiet gtrefclk01_in[1]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet gtwiz_reset_clk_freerun_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[1]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[2]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[3]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[4]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[5]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[6]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk2_in[7]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[1]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[2]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[3]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[4]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[5]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[6]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet rxusrclk_in[7]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[1]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[2]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[3]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[4]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[5]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[6]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk2_in[7]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[0]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[1]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[2]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[3]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[4]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[5]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[6]]
set_property -quiet CLOCK_PERIOD_OOC_TARGET 4.166 [get_ports -no_traverse -quiet txusrclk_in[7]]
set_property -quiet IS_IP_OOC_CELL TRUE [get_cells -of [get_ports -no_traverse -quiet gthrxn_in[0]]]
