// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ped_alg,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.018750,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=42,HLS_SYN_LUT=266,HLS_VERSION=2020_1}" *)

module ped_alg (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ped_val_i,
        ped_val_o,
        ped_val_o_ap_vld,
        accum_i,
        accum_o,
        accum_o_ap_vld,
        ADC,
        ADC_ap_vld,
        tdata,
        tvalid,
        tkeep0,
        tkeep1,
        tready,
        treset,
        tlast
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ped_val_i;
output  [15:0] ped_val_o;
output   ped_val_o_ap_vld;
input  [7:0] accum_i;
output  [7:0] accum_o;
output   accum_o_ap_vld;
output  [15:0] ADC;
output   ADC_ap_vld;
input  [15:0] tdata;
input   tvalid;
input   tkeep0;
input   tkeep1;
input   tready;
input   treset;
input   tlast;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ped_val_o;
reg ped_val_o_ap_vld;
reg[7:0] accum_o;
reg accum_o_ap_vld;
reg ADC_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tready_read_read_fu_70_p2;
wire   [0:0] tvalid_read_read_fu_76_p2;
wire   [0:0] tkeep0_read_read_fu_82_p2;
wire   [0:0] tkeep1_read_read_fu_88_p2;
wire   [0:0] treset_read_read_fu_94_p2;
wire   [15:0] zext_ln35_fu_183_p1;
reg   [15:0] zext_ln35_reg_285;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln41_1_fu_219_p2;
wire   [7:0] select_ln41_fu_225_p3;
wire   [15:0] add_ln57_fu_245_p2;
wire   [0:0] icmp_ln51_fu_233_p2;
wire   [0:0] icmp_ln56_fu_239_p2;
wire   [15:0] add_ln52_fu_252_p2;
reg   [15:0] ped_val_load_3_reg_139;
wire   [0:0] ap_phi_mux_accum_flag_2_phi_fu_154_p6;
reg   [0:0] accum_flag_2_reg_150;
reg   [7:0] accum_new_2_reg_164;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [11:0] trunc_fu_179_p1;
wire   [0:0] icmp_ln45_fu_199_p2;
wire   [7:0] add_ln46_fu_205_p2;
wire   [0:0] icmp_ln41_fu_187_p2;
wire   [7:0] add_ln42_fu_193_p2;
wire   [7:0] select_ln45_fu_211_p3;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_239_p2 == 1'd0) & (icmp_ln51_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        accum_flag_2_reg_150 <= icmp_ln41_1_fu_219_p2;
    end else if ((((icmp_ln51_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln51_fu_233_p2 == 1'd0) & (icmp_ln56_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        accum_flag_2_reg_150 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_239_p2 == 1'd0) & (icmp_ln51_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        accum_new_2_reg_164 <= select_ln41_fu_225_p3;
    end else if ((((icmp_ln51_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln51_fu_233_p2 == 1'd0) & (icmp_ln56_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        accum_new_2_reg_164 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if (((icmp_ln56_fu_239_p2 == 1'd0) & (icmp_ln51_fu_233_p2 == 1'd0))) begin
            ped_val_load_3_reg_139 <= ped_val_i;
        end else if (((icmp_ln51_fu_233_p2 == 1'd0) & (icmp_ln56_fu_239_p2 == 1'd1))) begin
            ped_val_load_3_reg_139 <= add_ln57_fu_245_p2;
        end else if ((icmp_ln51_fu_233_p2 == 1'd1)) begin
            ped_val_load_3_reg_139 <= add_ln52_fu_252_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln35_reg_285[11 : 0] <= zext_ln35_fu_183_p1[11 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ADC_ap_vld = 1'b1;
    end else begin
        ADC_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((treset_read_read_fu_94_p2 == 1'd0) & (ap_phi_mux_accum_flag_2_phi_fu_154_p6 == 1'd1) & (tkeep1_read_read_fu_88_p2 == 1'd1) & (tkeep0_read_read_fu_82_p2 == 1'd1) & (tvalid_read_read_fu_76_p2 == 1'd1) & (tready_read_read_fu_70_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        accum_o = accum_new_2_reg_164;
    end else begin
        accum_o = accum_i;
    end
end

always @ (*) begin
    if (((treset_read_read_fu_94_p2 == 1'd0) & (ap_phi_mux_accum_flag_2_phi_fu_154_p6 == 1'd1) & (tkeep1_read_read_fu_88_p2 == 1'd1) & (tkeep0_read_read_fu_82_p2 == 1'd1) & (tvalid_read_read_fu_76_p2 == 1'd1) & (tready_read_read_fu_70_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        accum_o_ap_vld = 1'b1;
    end else begin
        accum_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((icmp_ln51_fu_233_p2 == 1'd1)) begin
            ped_val_o = add_ln52_fu_252_p2;
        end else if (((icmp_ln51_fu_233_p2 == 1'd0) & (icmp_ln56_fu_239_p2 == 1'd1))) begin
            ped_val_o = add_ln57_fu_245_p2;
        end else begin
            ped_val_o = ped_val_i;
        end
    end else begin
        ped_val_o = ped_val_i;
    end
end

always @ (*) begin
    if ((((icmp_ln51_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln51_fu_233_p2 == 1'd0) & (icmp_ln56_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ped_val_o_ap_vld = 1'b1;
    end else begin
        ped_val_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((treset_read_read_fu_94_p2 == 1'd0) & (tkeep1_read_read_fu_88_p2 == 1'd1) & (tkeep0_read_read_fu_82_p2 == 1'd1) & (tvalid_read_read_fu_76_p2 == 1'd1) & (tready_read_read_fu_70_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((tready_read_read_fu_70_p2 == 1'd0) | ((tvalid_read_read_fu_76_p2 == 1'd0) | ((tkeep0_read_read_fu_82_p2 == 1'd0) | ((tkeep1_read_read_fu_88_p2 == 1'd0) | (treset_read_read_fu_94_p2 == 1'd1))))))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ADC = (zext_ln35_reg_285 - ped_val_load_3_reg_139);

assign add_ln42_fu_193_p2 = (8'd1 + accum_i);

assign add_ln46_fu_205_p2 = ($signed(8'd255) + $signed(accum_i));

assign add_ln52_fu_252_p2 = (ped_val_i + 16'd1);

assign add_ln57_fu_245_p2 = ($signed(ped_val_i) + $signed(16'd65535));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_phi_mux_accum_flag_2_phi_fu_154_p6 = accum_flag_2_reg_150;

assign icmp_ln41_1_fu_219_p2 = ((zext_ln35_fu_183_p1 != ped_val_i) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_187_p2 = (($signed(zext_ln35_fu_183_p1) > $signed(ped_val_i)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_199_p2 = (($signed(zext_ln35_fu_183_p1) < $signed(ped_val_i)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_233_p2 = (($signed(select_ln41_fu_225_p3) > $signed(8'd9)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_239_p2 = (($signed(select_ln41_fu_225_p3) < $signed(8'd247)) ? 1'b1 : 1'b0);

assign select_ln41_fu_225_p3 = ((icmp_ln41_fu_187_p2[0:0] === 1'b1) ? add_ln42_fu_193_p2 : select_ln45_fu_211_p3);

assign select_ln45_fu_211_p3 = ((icmp_ln45_fu_199_p2[0:0] === 1'b1) ? add_ln46_fu_205_p2 : accum_i);

assign tkeep0_read_read_fu_82_p2 = tkeep0;

assign tkeep1_read_read_fu_88_p2 = tkeep1;

assign tready_read_read_fu_70_p2 = tready;

assign treset_read_read_fu_94_p2 = treset;

assign trunc_fu_179_p1 = tdata[11:0];

assign tvalid_read_read_fu_76_p2 = tvalid;

assign zext_ln35_fu_183_p1 = trunc_fu_179_p1;

always @ (posedge ap_clk) begin
    zext_ln35_reg_285[15:12] <= 4'b0000;
end

endmodule //ped_alg
