// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ped_alg.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ped_alg::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ped_alg::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> ped_alg::ap_ST_fsm_state1 = "1";
const sc_lv<3> ped_alg::ap_ST_fsm_state2 = "10";
const sc_lv<3> ped_alg::ap_ST_fsm_state3 = "100";
const sc_lv<32> ped_alg::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> ped_alg::ap_const_lv1_0 = "0";
const sc_lv<1> ped_alg::ap_const_lv1_1 = "1";
const sc_lv<32> ped_alg::ap_const_lv32_1 = "1";
const sc_lv<32> ped_alg::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> ped_alg::ap_const_lv32_9 = "1001";
const sc_lv<32> ped_alg::ap_const_lv32_FFFFFFF7 = "11111111111111111111111111110111";
const sc_lv<32> ped_alg::ap_const_lv32_2 = "10";
const bool ped_alg::ap_const_boolean_1 = true;

ped_alg::ped_alg(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ADC_o);
    sensitive << ( ADC_read_reg_193 );
    sensitive << ( ped_val_load_3_reg_104 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ADC_o_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_accum_o);
    sensitive << ( accum_i );
    sensitive << ( ap_phi_mux_accum_flag_2_phi_fu_79_p6 );
    sensitive << ( accum_new_2_reg_89 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_accum_o_ap_vld);
    sensitive << ( ap_phi_mux_accum_flag_2_phi_fu_79_p6 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_add_ln18_fu_121_p2);
    sensitive << ( accum_i );

    SC_METHOD(thread_add_ln22_fu_133_p2);
    sensitive << ( accum_i );

    SC_METHOD(thread_add_ln27_fu_180_p2);
    sensitive << ( ped_val_i );

    SC_METHOD(thread_add_ln32_fu_173_p2);
    sensitive << ( ped_val_i );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_accum_flag_2_phi_fu_79_p6);
    sensitive << ( accum_flag_2_reg_75 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln17_1_fu_147_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ped_val_i );
    sensitive << ( ADC_i );

    SC_METHOD(thread_icmp_ln17_fu_115_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ped_val_i );
    sensitive << ( ADC_i );

    SC_METHOD(thread_icmp_ln21_fu_127_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ped_val_i );
    sensitive << ( ADC_i );

    SC_METHOD(thread_icmp_ln26_fu_161_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln17_fu_153_p3 );

    SC_METHOD(thread_icmp_ln31_fu_167_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln17_fu_153_p3 );
    sensitive << ( icmp_ln26_fu_161_p2 );

    SC_METHOD(thread_ped_val_o);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ped_val_i );
    sensitive << ( add_ln32_fu_173_p2 );
    sensitive << ( icmp_ln26_fu_161_p2 );
    sensitive << ( icmp_ln31_fu_167_p2 );
    sensitive << ( add_ln27_fu_180_p2 );

    SC_METHOD(thread_ped_val_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln26_fu_161_p2 );
    sensitive << ( icmp_ln31_fu_167_p2 );

    SC_METHOD(thread_select_ln17_fu_153_p3);
    sensitive << ( icmp_ln17_fu_115_p2 );
    sensitive << ( add_ln18_fu_121_p2 );
    sensitive << ( select_ln21_fu_139_p3 );

    SC_METHOD(thread_select_ln21_fu_139_p3);
    sensitive << ( accum_i );
    sensitive << ( icmp_ln21_fu_127_p2 );
    sensitive << ( add_ln22_fu_133_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ped_alg_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ped_val_i, "(port)ped_val_i");
    sc_trace(mVcdFile, ped_val_o, "(port)ped_val_o");
    sc_trace(mVcdFile, ped_val_o_ap_vld, "(port)ped_val_o_ap_vld");
    sc_trace(mVcdFile, accum_i, "(port)accum_i");
    sc_trace(mVcdFile, accum_o, "(port)accum_o");
    sc_trace(mVcdFile, accum_o_ap_vld, "(port)accum_o_ap_vld");
    sc_trace(mVcdFile, ADC_i, "(port)ADC_i");
    sc_trace(mVcdFile, ADC_o, "(port)ADC_o");
    sc_trace(mVcdFile, ADC_o_ap_vld, "(port)ADC_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ADC_read_reg_193, "ADC_read_reg_193");
    sc_trace(mVcdFile, icmp_ln17_1_fu_147_p2, "icmp_ln17_1_fu_147_p2");
    sc_trace(mVcdFile, select_ln17_fu_153_p3, "select_ln17_fu_153_p3");
    sc_trace(mVcdFile, add_ln32_fu_173_p2, "add_ln32_fu_173_p2");
    sc_trace(mVcdFile, icmp_ln26_fu_161_p2, "icmp_ln26_fu_161_p2");
    sc_trace(mVcdFile, icmp_ln31_fu_167_p2, "icmp_ln31_fu_167_p2");
    sc_trace(mVcdFile, add_ln27_fu_180_p2, "add_ln27_fu_180_p2");
    sc_trace(mVcdFile, ap_phi_mux_accum_flag_2_phi_fu_79_p6, "ap_phi_mux_accum_flag_2_phi_fu_79_p6");
    sc_trace(mVcdFile, accum_flag_2_reg_75, "accum_flag_2_reg_75");
    sc_trace(mVcdFile, accum_new_2_reg_89, "accum_new_2_reg_89");
    sc_trace(mVcdFile, ped_val_load_3_reg_104, "ped_val_load_3_reg_104");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln21_fu_127_p2, "icmp_ln21_fu_127_p2");
    sc_trace(mVcdFile, add_ln22_fu_133_p2, "add_ln22_fu_133_p2");
    sc_trace(mVcdFile, icmp_ln17_fu_115_p2, "icmp_ln17_fu_115_p2");
    sc_trace(mVcdFile, add_ln18_fu_121_p2, "add_ln18_fu_121_p2");
    sc_trace(mVcdFile, select_ln21_fu_139_p3, "select_ln21_fu_139_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("ped_alg.hdltvin.dat");
    mHdltvoutHandle.open("ped_alg.hdltvout.dat");
}

ped_alg::~ped_alg() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void ped_alg::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_167_p2.read()))) {
        accum_flag_2_reg_75 = icmp_ln17_1_fu_147_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(icmp_ln31_fu_167_p2.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_1)))) {
        accum_flag_2_reg_75 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_167_p2.read()))) {
        accum_new_2_reg_89 = select_ln17_fu_153_p3.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(icmp_ln31_fu_167_p2.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                 esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_1)))) {
        accum_new_2_reg_89 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        if ((esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_167_p2.read()))) {
            ped_val_load_3_reg_104 = ped_val_i.read();
        } else if ((esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(icmp_ln31_fu_167_p2.read(), ap_const_lv1_1))) {
            ped_val_load_3_reg_104 = add_ln32_fu_173_p2.read();
        } else if (esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_1)) {
            ped_val_load_3_reg_104 = add_ln27_fu_180_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ADC_read_reg_193 = ADC_i.read();
    }
}

void ped_alg::thread_ADC_o() {
    ADC_o = (!ADC_read_reg_193.read().is_01() || !ped_val_load_3_reg_104.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ADC_read_reg_193.read()) - sc_biguint<32>(ped_val_load_3_reg_104.read()));
}

void ped_alg::thread_ADC_o_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ADC_o_ap_vld = ap_const_logic_1;
    } else {
        ADC_o_ap_vld = ap_const_logic_0;
    }
}

void ped_alg::thread_accum_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_accum_flag_2_phi_fu_79_p6.read()))) {
        accum_o = accum_new_2_reg_89.read();
    } else {
        accum_o = accum_i.read();
    }
}

void ped_alg::thread_accum_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_accum_flag_2_phi_fu_79_p6.read()))) {
        accum_o_ap_vld = ap_const_logic_1;
    } else {
        accum_o_ap_vld = ap_const_logic_0;
    }
}

void ped_alg::thread_add_ln18_fu_121_p2() {
    add_ln18_fu_121_p2 = (!accum_i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(accum_i.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ped_alg::thread_add_ln22_fu_133_p2() {
    add_ln22_fu_133_p2 = (!accum_i.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(accum_i.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void ped_alg::thread_add_ln27_fu_180_p2() {
    add_ln27_fu_180_p2 = (!ped_val_i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(ped_val_i.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void ped_alg::thread_add_ln32_fu_173_p2() {
    add_ln32_fu_173_p2 = (!ped_val_i.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(ped_val_i.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void ped_alg::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ped_alg::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ped_alg::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void ped_alg::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void ped_alg::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ped_alg::thread_ap_phi_mux_accum_flag_2_phi_fu_79_p6() {
    ap_phi_mux_accum_flag_2_phi_fu_79_p6 = accum_flag_2_reg_75.read();
}

void ped_alg::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ped_alg::thread_icmp_ln17_1_fu_147_p2() {
    icmp_ln17_1_fu_147_p2 = (!ADC_i.read().is_01() || !ped_val_i.read().is_01())? sc_lv<1>(): sc_lv<1>(ADC_i.read() != ped_val_i.read());
}

void ped_alg::thread_icmp_ln17_fu_115_p2() {
    icmp_ln17_fu_115_p2 = (!ADC_i.read().is_01() || !ped_val_i.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ADC_i.read()) > sc_bigint<32>(ped_val_i.read()));
}

void ped_alg::thread_icmp_ln21_fu_127_p2() {
    icmp_ln21_fu_127_p2 = (!ADC_i.read().is_01() || !ped_val_i.read().is_01())? sc_lv<1>(): (sc_bigint<32>(ADC_i.read()) < sc_bigint<32>(ped_val_i.read()));
}

void ped_alg::thread_icmp_ln26_fu_161_p2() {
    icmp_ln26_fu_161_p2 = (!select_ln17_fu_153_p3.read().is_01() || !ap_const_lv32_9.is_01())? sc_lv<1>(): (sc_bigint<32>(select_ln17_fu_153_p3.read()) > sc_bigint<32>(ap_const_lv32_9));
}

void ped_alg::thread_icmp_ln31_fu_167_p2() {
    icmp_ln31_fu_167_p2 = (!select_ln17_fu_153_p3.read().is_01() || !ap_const_lv32_FFFFFFF7.is_01())? sc_lv<1>(): (sc_bigint<32>(select_ln17_fu_153_p3.read()) < sc_bigint<32>(ap_const_lv32_FFFFFFF7));
}

void ped_alg::thread_ped_val_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        if (esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_1)) {
            ped_val_o = add_ln27_fu_180_p2.read();
        } else if ((esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(icmp_ln31_fu_167_p2.read(), ap_const_lv1_1))) {
            ped_val_o = add_ln32_fu_173_p2.read();
        } else {
            ped_val_o = ped_val_i.read();
        }
    } else {
        ped_val_o = ped_val_i.read();
    }
}

void ped_alg::thread_ped_val_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(icmp_ln31_fu_167_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(icmp_ln26_fu_161_p2.read(), ap_const_lv1_1)))) {
        ped_val_o_ap_vld = ap_const_logic_1;
    } else {
        ped_val_o_ap_vld = ap_const_logic_0;
    }
}

void ped_alg::thread_select_ln17_fu_153_p3() {
    select_ln17_fu_153_p3 = (!icmp_ln17_fu_115_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln17_fu_115_p2.read()[0].to_bool())? add_ln18_fu_121_p2.read(): select_ln21_fu_139_p3.read());
}

void ped_alg::thread_select_ln21_fu_139_p3() {
    select_ln21_fu_139_p3 = (!icmp_ln21_fu_127_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln21_fu_127_p2.read()[0].to_bool())? add_ln22_fu_133_p2.read(): accum_i.read());
}

void ped_alg::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void ped_alg::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ped_val_i\" :  \"" << ped_val_i.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ped_val_o\" :  \"" << ped_val_o.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ped_val_o_ap_vld\" :  \"" << ped_val_o_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"accum_i\" :  \"" << accum_i.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"accum_o\" :  \"" << accum_o.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"accum_o_ap_vld\" :  \"" << accum_o_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ADC_i\" :  \"" << ADC_i.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ADC_o\" :  \"" << ADC_o.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ADC_o_ap_vld\" :  \"" << ADC_o_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

