# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data2/hmo31799/dune_project/ped_sub/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/RAM_2048x12/RAM_2048x12.xci
# IP: The module: 'RAM_2048x12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data2/hmo31799/dune_project/ped_sub/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/RAM_2048x12/RAM_2048x12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_2048x12'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /data2/hmo31799/dune_project/ped_sub/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/RAM_2048x12/RAM_2048x12.xci
# IP: The module: 'RAM_2048x12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data2/hmo31799/dune_project/ped_sub/tpg_core/proj/dataflowZCU102/dataflowZCU102/dataflowZCU102.srcs/sources_1/ip/RAM_2048x12/RAM_2048x12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_2048x12'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
