-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_HLS_simplified is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tdata_i : IN STD_LOGIC_VECTOR (15 downto 0);
    tdata_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    tdata_o_ap_vld : OUT STD_LOGIC;
    tvalid_i : IN STD_LOGIC;
    tvalid_o : OUT STD_LOGIC;
    tvalid_o_ap_vld : OUT STD_LOGIC;
    tuser_i : IN STD_LOGIC;
    tuser_o : OUT STD_LOGIC;
    tuser_o_ap_vld : OUT STD_LOGIC;
    tkeep0_i : IN STD_LOGIC;
    tkeep0_o : OUT STD_LOGIC;
    tkeep0_o_ap_vld : OUT STD_LOGIC;
    tkeep1_i : IN STD_LOGIC;
    tkeep1_o : OUT STD_LOGIC;
    tkeep1_o_ap_vld : OUT STD_LOGIC;
    tready_i : IN STD_LOGIC;
    treset_i : IN STD_LOGIC;
    treset_o : OUT STD_LOGIC;
    treset_o_ap_vld : OUT STD_LOGIC;
    tlast_i : IN STD_LOGIC;
    tlast_o : OUT STD_LOGIC;
    tlast_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fir_HLS_simplified is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_HLS_simplified,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.240000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=549,HLS_SYN_LUT=1703,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv16_B : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001011";
    constant ap_const_lv16_D : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tlast_reset : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal restore_count : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tap_array_22 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_21 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_19 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_15 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tap_array_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tdata_previous_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tvalid_previous_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tuser_previous_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tkeep_previous_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tlast_previous_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tlast_i_read_reg_1653 : STD_LOGIC_VECTOR (0 downto 0);
    signal treset_i_read_read_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal treset_i_read_reg_1658 : STD_LOGIC_VECTOR (0 downto 0);
    signal tkeep1_i_read_reg_1662 : STD_LOGIC_VECTOR (0 downto 0);
    signal tkeep0_i_read_reg_1667 : STD_LOGIC_VECTOR (0 downto 0);
    signal tuser_i_read_reg_1672 : STD_LOGIC_VECTOR (0 downto 0);
    signal tvalid_i_read_reg_1677 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1682 : STD_LOGIC_VECTOR (0 downto 0);
    signal tap_array_21_load_reg_1686 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_20_load_reg_1691 : STD_LOGIC_VECTOR (15 downto 0);
    signal brmerge2_demorgan_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_demorgan_reg_1697 : STD_LOGIC_VECTOR (0 downto 0);
    signal mult_9_fu_831_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mult_9_reg_1702 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp2_fu_861_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp2_reg_1707 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp7_fu_867_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp7_fu_867_p2 : signal is "no";
    signal tmp7_reg_1712 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1629_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp11_reg_1717 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1637_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp12_reg_1722 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1645_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp14_reg_1727 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp16_fu_872_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp16_reg_1732 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal grp_output_assign_fu_545_ap_ready : STD_LOGIC;
    signal grp_output_assign_fu_545_tdata_assign : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_output_assign_fu_545_tvalid_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_tuser_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_tkeep0_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_tkeep1_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_treset_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_tlast_assign : STD_LOGIC;
    signal grp_output_assign_fu_545_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_output_assign_fu_545_ap_return_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_output_assign_fu_545_ap_return_2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_output_assign_fu_545_ap_return_3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_output_assign_fu_545_ap_return_4 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_output_assign_fu_545_ap_return_5 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_output_assign_fu_545_ap_return_6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tlast_reset_flag_3_reg_241 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_tlast_reset_flag_1_fu_1343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tlast_reset_new_3_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_demorgan_fu_1336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_restore_count_flag_2_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_restore_count_new_2_phi_fu_276_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_restore_count_new_2_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_tmp_s_fu_890_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_30_flag_3_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal tap_array_30_flag_2_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_22_new_3_reg_304 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_22_new_2_fu_1129_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_21_new_3_reg_314 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_21_new_2_fu_1138_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_20_new_3_reg_324 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_20_new_2_fu_1147_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_19_new_3_reg_334 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_19_new_2_fu_1156_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_18_new_3_reg_344 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_18_new_2_fu_1165_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_17_new_3_reg_354 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_17_new_2_fu_1174_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_16_new_3_reg_364 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_16_new_2_fu_1183_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_15_new_3_reg_374 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_15_new_2_fu_1192_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_14_new_3_reg_384 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_14_new_2_fu_1201_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_13_new_3_reg_394 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_13_new_2_fu_1210_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_12_new_3_reg_404 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_12_new_2_fu_1219_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_11_new_3_reg_414 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_11_new_2_fu_1228_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_10_new_3_reg_424 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_10_new_2_fu_1237_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_9_new_3_reg_434 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_9_new_2_fu_1246_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_8_new_3_reg_444 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_8_new_2_fu_1255_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_7_new_3_reg_454 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_7_new_2_fu_1264_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_6_new_3_reg_464 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_6_new_2_fu_1273_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_5_new_3_reg_474 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_5_new_2_fu_1282_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_4_new_3_reg_484 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_4_new_2_fu_1291_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_3_new_3_reg_494 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_3_new_2_fu_1300_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_2_new_3_reg_504 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_2_new_2_fu_1309_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_1_new_3_reg_514 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_1_new_2_fu_1318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_tap_array_0_new_3_reg_524 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_0_new_2_fu_1327_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_1_fu_1594_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal brmerge_fu_618_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_618_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_729_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_729_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_demorgan_fu_735_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_747_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_765_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_771_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_783_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_789_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_13_fu_807_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_14_fu_819_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_15_fu_825_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_801_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_741_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp4_fu_855_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp3_fu_849_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1620_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal mult_1_fu_753_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_16_fu_837_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_843_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_878_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tap_array_17_load_fu_947_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_15_load_fu_963_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_14_load_fu_971_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_12_load_fu_987_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tlast_reset_flag_1_fu_1099_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tap_array_21_load_fu_915_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_20_load_fu_923_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_19_load_fu_931_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_18_load_fu_939_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_17_load_fu_947_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_18_new_2_fu_1165_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_16_load_fu_955_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_15_load_fu_963_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_16_new_2_fu_1183_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_14_load_fu_971_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_15_new_2_fu_1192_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_13_load_fu_979_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_12_load_fu_987_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tap_array_13_new_2_fu_1210_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_11_load_fu_995_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_10_load_fu_1003_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_9_load_fu_1011_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_8_load_fu_1019_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_7_load_fu_1027_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_6_load_fu_1035_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_5_load_fu_1043_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_4_load_fu_1051_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_3_load_fu_1059_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_2_load_fu_1067_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_1_load_fu_1075_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tap_array_0_load_fu_1083_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_tdata_i_fu_1091_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal brmerge3_demorgan_fu_1336_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_demorgan_fu_1336_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_1537_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_1542_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_1532_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mult_s_fu_1547_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp6_fu_1553_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp5_fu_1559_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp15_fu_1573_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp13_fu_1577_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of tmp13_fu_1577_p2 : signal is "no";
    signal tmp10_fu_1569_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of tmp10_fu_1569_p2 : signal is "no";
    signal tmp9_fu_1582_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_1564_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_2_s_fu_1588_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1620_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1620_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1629_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1629_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1637_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1637_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1645_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1645_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_344 : BOOLEAN;
    signal ap_condition_323 : BOOLEAN;
    signal ap_condition_943 : BOOLEAN;

    component output_assign IS
    port (
        ap_ready : OUT STD_LOGIC;
        tdata_assign : IN STD_LOGIC_VECTOR (15 downto 0);
        tvalid_assign : IN STD_LOGIC;
        tuser_assign : IN STD_LOGIC;
        tkeep0_assign : IN STD_LOGIC;
        tkeep1_assign : IN STD_LOGIC;
        treset_assign : IN STD_LOGIC;
        tlast_assign : IN STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_output_assign_fu_545 : component output_assign
    port map (
        ap_ready => grp_output_assign_fu_545_ap_ready,
        tdata_assign => grp_output_assign_fu_545_tdata_assign,
        tvalid_assign => grp_output_assign_fu_545_tvalid_assign,
        tuser_assign => grp_output_assign_fu_545_tuser_assign,
        tkeep0_assign => grp_output_assign_fu_545_tkeep0_assign,
        tkeep1_assign => grp_output_assign_fu_545_tkeep1_assign,
        treset_assign => grp_output_assign_fu_545_treset_assign,
        tlast_assign => grp_output_assign_fu_545_tlast_assign,
        ap_return_0 => grp_output_assign_fu_545_ap_return_0,
        ap_return_1 => grp_output_assign_fu_545_ap_return_1,
        ap_return_2 => grp_output_assign_fu_545_ap_return_2,
        ap_return_3 => grp_output_assign_fu_545_ap_return_3,
        ap_return_4 => grp_output_assign_fu_545_ap_return_4,
        ap_return_5 => grp_output_assign_fu_545_ap_return_5,
        ap_return_6 => grp_output_assign_fu_545_ap_return_6);

    fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1_U8 : component fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_1620_p0,
        din1 => tap_array_17,
        din2 => grp_fu_1620_p2,
        dout => grp_fu_1620_p3);

    fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1_U9 : component fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_1629_p0,
        din1 => tap_array_15,
        din2 => grp_fu_1629_p2,
        dout => grp_fu_1629_p3);

    fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1_U10 : component fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_1637_p0,
        din1 => tap_array_14,
        din2 => grp_fu_1637_p2,
        dout => grp_fu_1637_p3);

    fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1_U11 : component fir_HLS_simplified_mac_muladd_5ns_16s_16ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        din0 => grp_fu_1645_p0,
        din1 => tap_array_12,
        din2 => grp_fu_1645_p2,
        dout => grp_fu_1645_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    tdata_previous_0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_943)) then
                if ((treset_i_read_reg_1658 = ap_const_lv1_1)) then 
                    tdata_previous_0 <= ap_const_lv16_0;
                elsif ((treset_i_read_reg_1658 = ap_const_lv1_0)) then 
                    tdata_previous_0 <= sum_1_fu_1594_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((treset_i_read_read_fu_150_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                brmerge2_demorgan_reg_1697 <= brmerge2_demorgan_fu_735_p2;
                    mult_9_reg_1702(15 downto 1) <= mult_9_fu_831_p2(15 downto 1);
                    tmp16_reg_1732(15 downto 1) <= tmp16_fu_872_p2(15 downto 1);
                tmp2_reg_1707 <= tmp2_fu_861_p2;
                tmp7_reg_1712 <= tmp7_fu_867_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                brmerge_reg_1682 <= brmerge_fu_618_p2;
                tkeep0_i_read_reg_1667 <= (0=>tkeep0_i, others=>'-');
                tkeep1_i_read_reg_1662 <= (0=>tkeep1_i, others=>'-');
                tlast_i_read_reg_1653 <= (0=>tlast_i, others=>'-');
                treset_i_read_reg_1658 <= (0=>treset_i, others=>'-');
                tuser_i_read_reg_1672 <= (0=>tuser_i, others=>'-');
                tvalid_i_read_reg_1677 <= (0=>tvalid_i, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 = ap_const_lv1_1) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                restore_count <= ap_phi_mux_restore_count_new_2_phi_fu_276_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 = ap_const_lv1_1) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                tap_array_0 <= ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4;
                tap_array_1 <= ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4;
                tap_array_10 <= ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4;
                tap_array_11 <= ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4;
                tap_array_12 <= ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4;
                tap_array_13 <= ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4;
                tap_array_14 <= ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4;
                tap_array_15 <= ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4;
                tap_array_16 <= ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4;
                tap_array_17 <= ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4;
                tap_array_18 <= ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4;
                tap_array_19 <= ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4;
                tap_array_2 <= ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4;
                tap_array_20 <= ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4;
                tap_array_21 <= ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4;
                tap_array_22 <= ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4;
                tap_array_3 <= ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4;
                tap_array_4 <= ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4;
                tap_array_5 <= ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4;
                tap_array_6 <= ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4;
                tap_array_7 <= ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4;
                tap_array_8 <= ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4;
                tap_array_9 <= ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                tap_array_20_load_reg_1691 <= tap_array_20;
                tap_array_21_load_reg_1686 <= tap_array_21;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1) and (treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) or ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1)))) then
                tkeep_previous_0 <= (0=>tkeep0_i, others=>'-');
                tlast_previous_0 <= (0=>tlast_i, others=>'-');
                tuser_previous_0 <= (0=>tuser_i, others=>'-');
                tvalid_previous_0 <= (0=>tvalid_i, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 = ap_const_lv1_1) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                tlast_reset <= ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((treset_i_read_read_fu_150_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1))) then
                tmp11_reg_1717 <= grp_fu_1629_p3;
                tmp12_reg_1722 <= grp_fu_1637_p3;
                tmp14_reg_1727 <= grp_fu_1645_p3;
            end if;
        end if;
    end process;
    mult_9_reg_1702(0) <= '0';
    tmp16_reg_1732(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_323_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_323 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_344_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, brmerge_fu_618_p2, ap_block_pp0_stage0)
    begin
                ap_condition_344 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_fu_618_p2 = ap_const_lv1_1));
    end process;


    ap_condition_943_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, brmerge_reg_1682)
    begin
                ap_condition_943 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_restore_count_flag_2_phi_fu_265_p4_assign_proc : process(tlast_reset, treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_restore_count_flag_2_reg_262, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 <= tlast_reset;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 <= ap_phi_reg_pp0_iter0_restore_count_flag_2_reg_262;
            end if;
        else 
            ap_phi_mux_restore_count_flag_2_phi_fu_265_p4 <= ap_phi_reg_pp0_iter0_restore_count_flag_2_reg_262;
        end if; 
    end process;


    ap_phi_mux_restore_count_new_2_phi_fu_276_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_restore_count_new_2_reg_273, p_tmp_s_fu_890_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_restore_count_new_2_phi_fu_276_p4 <= p_tmp_s_fu_890_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_restore_count_new_2_phi_fu_276_p4 <= ap_const_lv8_0;
            else 
                ap_phi_mux_restore_count_new_2_phi_fu_276_p4 <= ap_phi_reg_pp0_iter0_restore_count_new_2_reg_273;
            end if;
        else 
            ap_phi_mux_restore_count_new_2_phi_fu_276_p4 <= ap_phi_reg_pp0_iter0_restore_count_new_2_reg_273;
        end if; 
    end process;


    ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_0_new_3_reg_524, tap_array_0_new_2_fu_1327_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4 <= tap_array_0_new_2_fu_1327_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4 <= ap_phi_reg_pp0_iter0_tap_array_0_new_3_reg_524;
            end if;
        else 
            ap_phi_mux_tap_array_0_new_3_phi_fu_527_p4 <= ap_phi_reg_pp0_iter0_tap_array_0_new_3_reg_524;
        end if; 
    end process;


    ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_10_new_3_reg_424, tap_array_10_new_2_fu_1237_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4 <= tap_array_10_new_2_fu_1237_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4 <= ap_phi_reg_pp0_iter0_tap_array_10_new_3_reg_424;
            end if;
        else 
            ap_phi_mux_tap_array_10_new_3_phi_fu_427_p4 <= ap_phi_reg_pp0_iter0_tap_array_10_new_3_reg_424;
        end if; 
    end process;


    ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_11_new_3_reg_414, tap_array_11_new_2_fu_1228_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4 <= tap_array_11_new_2_fu_1228_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4 <= ap_phi_reg_pp0_iter0_tap_array_11_new_3_reg_414;
            end if;
        else 
            ap_phi_mux_tap_array_11_new_3_phi_fu_417_p4 <= ap_phi_reg_pp0_iter0_tap_array_11_new_3_reg_414;
        end if; 
    end process;


    ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_12_new_3_reg_404, tap_array_12_new_2_fu_1219_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4 <= tap_array_12_new_2_fu_1219_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4 <= ap_phi_reg_pp0_iter0_tap_array_12_new_3_reg_404;
            end if;
        else 
            ap_phi_mux_tap_array_12_new_3_phi_fu_407_p4 <= ap_phi_reg_pp0_iter0_tap_array_12_new_3_reg_404;
        end if; 
    end process;


    ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_13_new_3_reg_394, tap_array_13_new_2_fu_1210_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4 <= tap_array_13_new_2_fu_1210_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4 <= ap_phi_reg_pp0_iter0_tap_array_13_new_3_reg_394;
            end if;
        else 
            ap_phi_mux_tap_array_13_new_3_phi_fu_397_p4 <= ap_phi_reg_pp0_iter0_tap_array_13_new_3_reg_394;
        end if; 
    end process;


    ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_14_new_3_reg_384, tap_array_14_new_2_fu_1201_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4 <= tap_array_14_new_2_fu_1201_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4 <= ap_phi_reg_pp0_iter0_tap_array_14_new_3_reg_384;
            end if;
        else 
            ap_phi_mux_tap_array_14_new_3_phi_fu_387_p4 <= ap_phi_reg_pp0_iter0_tap_array_14_new_3_reg_384;
        end if; 
    end process;


    ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_15_new_3_reg_374, tap_array_15_new_2_fu_1192_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4 <= tap_array_15_new_2_fu_1192_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4 <= ap_phi_reg_pp0_iter0_tap_array_15_new_3_reg_374;
            end if;
        else 
            ap_phi_mux_tap_array_15_new_3_phi_fu_377_p4 <= ap_phi_reg_pp0_iter0_tap_array_15_new_3_reg_374;
        end if; 
    end process;


    ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_16_new_3_reg_364, tap_array_16_new_2_fu_1183_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4 <= tap_array_16_new_2_fu_1183_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4 <= ap_phi_reg_pp0_iter0_tap_array_16_new_3_reg_364;
            end if;
        else 
            ap_phi_mux_tap_array_16_new_3_phi_fu_367_p4 <= ap_phi_reg_pp0_iter0_tap_array_16_new_3_reg_364;
        end if; 
    end process;


    ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_17_new_3_reg_354, tap_array_17_new_2_fu_1174_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4 <= tap_array_17_new_2_fu_1174_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4 <= ap_phi_reg_pp0_iter0_tap_array_17_new_3_reg_354;
            end if;
        else 
            ap_phi_mux_tap_array_17_new_3_phi_fu_357_p4 <= ap_phi_reg_pp0_iter0_tap_array_17_new_3_reg_354;
        end if; 
    end process;


    ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_18_new_3_reg_344, tap_array_18_new_2_fu_1165_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4 <= tap_array_18_new_2_fu_1165_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4 <= ap_phi_reg_pp0_iter0_tap_array_18_new_3_reg_344;
            end if;
        else 
            ap_phi_mux_tap_array_18_new_3_phi_fu_347_p4 <= ap_phi_reg_pp0_iter0_tap_array_18_new_3_reg_344;
        end if; 
    end process;


    ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_19_new_3_reg_334, tap_array_19_new_2_fu_1156_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4 <= tap_array_19_new_2_fu_1156_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4 <= ap_phi_reg_pp0_iter0_tap_array_19_new_3_reg_334;
            end if;
        else 
            ap_phi_mux_tap_array_19_new_3_phi_fu_337_p4 <= ap_phi_reg_pp0_iter0_tap_array_19_new_3_reg_334;
        end if; 
    end process;


    ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_1_new_3_reg_514, tap_array_1_new_2_fu_1318_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4 <= tap_array_1_new_2_fu_1318_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4 <= ap_phi_reg_pp0_iter0_tap_array_1_new_3_reg_514;
            end if;
        else 
            ap_phi_mux_tap_array_1_new_3_phi_fu_517_p4 <= ap_phi_reg_pp0_iter0_tap_array_1_new_3_reg_514;
        end if; 
    end process;


    ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_20_new_3_reg_324, tap_array_20_new_2_fu_1147_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4 <= tap_array_20_new_2_fu_1147_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4 <= ap_phi_reg_pp0_iter0_tap_array_20_new_3_reg_324;
            end if;
        else 
            ap_phi_mux_tap_array_20_new_3_phi_fu_327_p4 <= ap_phi_reg_pp0_iter0_tap_array_20_new_3_reg_324;
        end if; 
    end process;


    ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_21_new_3_reg_314, tap_array_21_new_2_fu_1138_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4 <= tap_array_21_new_2_fu_1138_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4 <= ap_phi_reg_pp0_iter0_tap_array_21_new_3_reg_314;
            end if;
        else 
            ap_phi_mux_tap_array_21_new_3_phi_fu_317_p4 <= ap_phi_reg_pp0_iter0_tap_array_21_new_3_reg_314;
        end if; 
    end process;


    ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_22_new_3_reg_304, tap_array_22_new_2_fu_1129_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4 <= tap_array_22_new_2_fu_1129_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4 <= ap_phi_reg_pp0_iter0_tap_array_22_new_3_reg_304;
            end if;
        else 
            ap_phi_mux_tap_array_22_new_3_phi_fu_307_p4 <= ap_phi_reg_pp0_iter0_tap_array_22_new_3_reg_304;
        end if; 
    end process;


    ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_2_new_3_reg_504, tap_array_2_new_2_fu_1309_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4 <= tap_array_2_new_2_fu_1309_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4 <= ap_phi_reg_pp0_iter0_tap_array_2_new_3_reg_504;
            end if;
        else 
            ap_phi_mux_tap_array_2_new_3_phi_fu_507_p4 <= ap_phi_reg_pp0_iter0_tap_array_2_new_3_reg_504;
        end if; 
    end process;


    ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_30_flag_3_reg_283, tap_array_30_flag_2_fu_1105_p2, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 <= tap_array_30_flag_2_fu_1105_p2;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 <= ap_phi_reg_pp0_iter0_tap_array_30_flag_3_reg_283;
            end if;
        else 
            ap_phi_mux_tap_array_30_flag_3_phi_fu_286_p4 <= ap_phi_reg_pp0_iter0_tap_array_30_flag_3_reg_283;
        end if; 
    end process;


    ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_3_new_3_reg_494, tap_array_3_new_2_fu_1300_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4 <= tap_array_3_new_2_fu_1300_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4 <= ap_phi_reg_pp0_iter0_tap_array_3_new_3_reg_494;
            end if;
        else 
            ap_phi_mux_tap_array_3_new_3_phi_fu_497_p4 <= ap_phi_reg_pp0_iter0_tap_array_3_new_3_reg_494;
        end if; 
    end process;


    ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_4_new_3_reg_484, tap_array_4_new_2_fu_1291_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4 <= tap_array_4_new_2_fu_1291_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4 <= ap_phi_reg_pp0_iter0_tap_array_4_new_3_reg_484;
            end if;
        else 
            ap_phi_mux_tap_array_4_new_3_phi_fu_487_p4 <= ap_phi_reg_pp0_iter0_tap_array_4_new_3_reg_484;
        end if; 
    end process;


    ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_5_new_3_reg_474, tap_array_5_new_2_fu_1282_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4 <= tap_array_5_new_2_fu_1282_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4 <= ap_phi_reg_pp0_iter0_tap_array_5_new_3_reg_474;
            end if;
        else 
            ap_phi_mux_tap_array_5_new_3_phi_fu_477_p4 <= ap_phi_reg_pp0_iter0_tap_array_5_new_3_reg_474;
        end if; 
    end process;


    ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_6_new_3_reg_464, tap_array_6_new_2_fu_1273_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4 <= tap_array_6_new_2_fu_1273_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4 <= ap_phi_reg_pp0_iter0_tap_array_6_new_3_reg_464;
            end if;
        else 
            ap_phi_mux_tap_array_6_new_3_phi_fu_467_p4 <= ap_phi_reg_pp0_iter0_tap_array_6_new_3_reg_464;
        end if; 
    end process;


    ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_7_new_3_reg_454, tap_array_7_new_2_fu_1264_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4 <= tap_array_7_new_2_fu_1264_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4 <= ap_phi_reg_pp0_iter0_tap_array_7_new_3_reg_454;
            end if;
        else 
            ap_phi_mux_tap_array_7_new_3_phi_fu_457_p4 <= ap_phi_reg_pp0_iter0_tap_array_7_new_3_reg_454;
        end if; 
    end process;


    ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_8_new_3_reg_444, tap_array_8_new_2_fu_1255_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4 <= tap_array_8_new_2_fu_1255_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4 <= ap_phi_reg_pp0_iter0_tap_array_8_new_3_reg_444;
            end if;
        else 
            ap_phi_mux_tap_array_8_new_3_phi_fu_447_p4 <= ap_phi_reg_pp0_iter0_tap_array_8_new_3_reg_444;
        end if; 
    end process;


    ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tap_array_9_new_3_reg_434, tap_array_9_new_2_fu_1246_p3, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4 <= tap_array_9_new_2_fu_1246_p3;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4 <= ap_const_lv16_0;
            else 
                ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4 <= ap_phi_reg_pp0_iter0_tap_array_9_new_3_reg_434;
            end if;
        else 
            ap_phi_mux_tap_array_9_new_3_phi_fu_437_p4 <= ap_phi_reg_pp0_iter0_tap_array_9_new_3_reg_434;
        end if; 
    end process;


    ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tlast_reset_flag_3_reg_241, p_tlast_reset_flag_1_fu_1343_p2, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 <= p_tlast_reset_flag_1_fu_1343_p2;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 <= ap_phi_reg_pp0_iter0_tlast_reset_flag_3_reg_241;
            end if;
        else 
            ap_phi_mux_tlast_reset_flag_3_phi_fu_244_p4 <= ap_phi_reg_pp0_iter0_tlast_reset_flag_3_reg_241;
        end if; 
    end process;


    ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4_assign_proc : process(treset_i_read_read_fu_150_p2, ap_phi_reg_pp0_iter0_tlast_reset_new_3_reg_252, brmerge3_demorgan_fu_1336_p2, ap_condition_344)
    begin
        if ((ap_const_boolean_1 = ap_condition_344)) then
            if ((treset_i_read_read_fu_150_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4 <= brmerge3_demorgan_fu_1336_p2;
            elsif ((treset_i_read_read_fu_150_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4 <= ap_phi_reg_pp0_iter0_tlast_reset_new_3_reg_252;
            end if;
        else 
            ap_phi_mux_tlast_reset_new_3_phi_fu_255_p4 <= ap_phi_reg_pp0_iter0_tlast_reset_new_3_reg_252;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_restore_count_flag_2_reg_262 <= "X";
    ap_phi_reg_pp0_iter0_restore_count_new_2_reg_273 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_0_new_3_reg_524 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_10_new_3_reg_424 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_11_new_3_reg_414 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_12_new_3_reg_404 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_13_new_3_reg_394 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_14_new_3_reg_384 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_15_new_3_reg_374 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_16_new_3_reg_364 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_17_new_3_reg_354 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_18_new_3_reg_344 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_19_new_3_reg_334 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_1_new_3_reg_514 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_20_new_3_reg_324 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_21_new_3_reg_314 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_22_new_3_reg_304 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_2_new_3_reg_504 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_30_flag_3_reg_283 <= "X";
    ap_phi_reg_pp0_iter0_tap_array_3_new_3_reg_494 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_4_new_3_reg_484 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_5_new_3_reg_474 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_6_new_3_reg_464 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_7_new_3_reg_454 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_8_new_3_reg_444 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tap_array_9_new_3_reg_434 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_tlast_reset_flag_3_reg_241 <= "X";
    ap_phi_reg_pp0_iter0_tlast_reset_new_3_reg_252 <= "X";

    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge2_demorgan_fu_735_p1 <= (0=>tvalid_i, others=>'-');
    brmerge2_demorgan_fu_735_p2 <= (tmp_fu_729_p2 and brmerge2_demorgan_fu_735_p1);
    brmerge3_demorgan_fu_1336_p0 <= (0=>tlast_i, others=>'-');
    brmerge3_demorgan_fu_1336_p1 <= (0=>tuser_i, others=>'-');
    brmerge3_demorgan_fu_1336_p2 <= (brmerge3_demorgan_fu_1336_p1 and brmerge3_demorgan_fu_1336_p0);
    brmerge_fu_618_p0 <= (0=>tready_i, others=>'-');
    brmerge_fu_618_p1 <= (0=>treset_i, others=>'-');
    brmerge_fu_618_p2 <= (brmerge_fu_618_p1 or brmerge_fu_618_p0);
    grp_fu_1620_p0 <= ap_const_lv16_B(5 - 1 downto 0);
    grp_fu_1620_p2 <= std_logic_vector(shift_left(unsigned(tap_array_18),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    grp_fu_1629_p0 <= ap_const_lv16_D(5 - 1 downto 0);
    grp_fu_1629_p2 <= std_logic_vector(unsigned(tmp_8_fu_765_p2) - unsigned(tmp_9_fu_771_p2));
    grp_fu_1637_p0 <= ap_const_lv16_D(5 - 1 downto 0);
    grp_fu_1637_p2 <= std_logic_vector(unsigned(tmp_10_fu_783_p2) - unsigned(tmp_11_fu_789_p2));
    grp_fu_1645_p0 <= ap_const_lv16_B(5 - 1 downto 0);
    grp_fu_1645_p2 <= std_logic_vector(unsigned(tmp_13_fu_807_p2) - unsigned(tap_array_10));

    grp_output_assign_fu_545_tdata_assign_assign_proc : process(tdata_previous_0, treset_i_read_reg_1658, brmerge_reg_1682, sum_1_fu_1594_p3, ap_condition_323)
    begin
        if ((ap_const_boolean_1 = ap_condition_323)) then
            if (((brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1))) then 
                grp_output_assign_fu_545_tdata_assign <= ap_const_lv16_0;
            elsif (((treset_i_read_reg_1658 = ap_const_lv1_0) and (brmerge_reg_1682 = ap_const_lv1_1))) then 
                grp_output_assign_fu_545_tdata_assign <= sum_1_fu_1594_p3;
            elsif ((brmerge_reg_1682 = ap_const_lv1_0)) then 
                grp_output_assign_fu_545_tdata_assign <= tdata_previous_0;
            else 
                grp_output_assign_fu_545_tdata_assign <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_output_assign_fu_545_tdata_assign <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_output_assign_fu_545_tkeep0_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tkeep_previous_0, treset_i_read_reg_1658, tkeep0_i_read_reg_1667, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)))) then 
            grp_output_assign_fu_545_tkeep0_assign <= tkeep0_i_read_reg_1667(0);
        elsif (((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_output_assign_fu_545_tkeep0_assign <= tkeep_previous_0(0);
        else 
            grp_output_assign_fu_545_tkeep0_assign <= 'X';
        end if; 
    end process;


    grp_output_assign_fu_545_tkeep1_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tkeep_previous_0, treset_i_read_reg_1658, tkeep1_i_read_reg_1662, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)))) then 
            grp_output_assign_fu_545_tkeep1_assign <= tkeep1_i_read_reg_1662(0);
        elsif (((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_output_assign_fu_545_tkeep1_assign <= tkeep_previous_0(0);
        else 
            grp_output_assign_fu_545_tkeep1_assign <= 'X';
        end if; 
    end process;


    grp_output_assign_fu_545_tlast_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tlast_previous_0, tlast_i_read_reg_1653, treset_i_read_reg_1658, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)))) then 
            grp_output_assign_fu_545_tlast_assign <= tlast_i_read_reg_1653(0);
        elsif (((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_output_assign_fu_545_tlast_assign <= tlast_previous_0(0);
        else 
            grp_output_assign_fu_545_tlast_assign <= 'X';
        end if; 
    end process;


    grp_output_assign_fu_545_treset_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, treset_i_read_reg_1658, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1))) then 
            grp_output_assign_fu_545_treset_assign <= ap_const_logic_1;
        elsif ((((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            grp_output_assign_fu_545_treset_assign <= ap_const_logic_0;
        else 
            grp_output_assign_fu_545_treset_assign <= 'X';
        end if; 
    end process;


    grp_output_assign_fu_545_tuser_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tuser_previous_0, treset_i_read_reg_1658, tuser_i_read_reg_1672, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)))) then 
            grp_output_assign_fu_545_tuser_assign <= tuser_i_read_reg_1672(0);
        elsif (((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_output_assign_fu_545_tuser_assign <= tuser_previous_0(0);
        else 
            grp_output_assign_fu_545_tuser_assign <= 'X';
        end if; 
    end process;


    grp_output_assign_fu_545_tvalid_assign_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tvalid_previous_0, treset_i_read_reg_1658, tvalid_i_read_reg_1677, brmerge_reg_1682, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)))) then 
            grp_output_assign_fu_545_tvalid_assign <= tvalid_i_read_reg_1677(0);
        elsif (((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_output_assign_fu_545_tvalid_assign <= tvalid_previous_0(0);
        else 
            grp_output_assign_fu_545_tvalid_assign <= 'X';
        end if; 
    end process;

    mult_1_fu_753_p2 <= std_logic_vector(unsigned(tmp_6_fu_747_p2) - unsigned(tap_array_19));
    mult_9_fu_831_p2 <= std_logic_vector(unsigned(tmp_14_fu_819_p2) - unsigned(tmp_15_fu_825_p2));
    mult_s_fu_1547_p2 <= std_logic_vector(unsigned(tmp_4_fu_1537_p2) - unsigned(tmp_5_fu_1542_p2));
    p_tap_array_0_load_fu_1083_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_0;
    p_tap_array_10_load_fu_1003_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_10;
    p_tap_array_11_load_fu_995_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_11;
    p_tap_array_12_load_fu_987_p2 <= tap_array_12;
    p_tap_array_12_load_fu_987_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        p_tap_array_12_load_fu_987_p2;
    p_tap_array_13_load_fu_979_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_13;
    p_tap_array_14_load_fu_971_p2 <= tap_array_14;
    p_tap_array_14_load_fu_971_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        p_tap_array_14_load_fu_971_p2;
    p_tap_array_15_load_fu_963_p2 <= tap_array_15;
    p_tap_array_15_load_fu_963_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        p_tap_array_15_load_fu_963_p2;
    p_tap_array_16_load_fu_955_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_16;
    p_tap_array_17_load_fu_947_p2 <= tap_array_17;
    p_tap_array_17_load_fu_947_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        p_tap_array_17_load_fu_947_p2;
    p_tap_array_18_load_fu_939_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_18;
    p_tap_array_19_load_fu_931_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_19;
    p_tap_array_1_load_fu_1075_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_1;
    p_tap_array_20_load_fu_923_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_20;
    p_tap_array_21_load_fu_915_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_21;
    p_tap_array_2_load_fu_1067_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_2;
    p_tap_array_3_load_fu_1059_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_3;
    p_tap_array_4_load_fu_1051_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_4;
    p_tap_array_5_load_fu_1043_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_5;
    p_tap_array_6_load_fu_1035_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_6;
    p_tap_array_7_load_fu_1027_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_7;
    p_tap_array_8_load_fu_1019_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_8;
    p_tap_array_9_load_fu_1011_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tap_array_9;
    p_tdata_i_fu_1091_p3 <= 
        ap_const_lv16_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tdata_i;
    p_tlast_reset_flag_1_fu_1343_p2 <= (tlast_reset_flag_1_fu_1099_p2 or brmerge3_demorgan_fu_1336_p2);
    p_tmp_s_fu_890_p3 <= 
        ap_const_lv8_0 when (tmp_1_fu_884_p2(0) = '1') else 
        tmp_s_fu_878_p2;
    sum_1_fu_1594_p3 <= 
        sum_2_s_fu_1588_p2 when (brmerge2_demorgan_reg_1697(0) = '1') else 
        ap_const_lv16_0;
    sum_2_s_fu_1588_p2 <= std_logic_vector(unsigned(tmp9_fu_1582_p2) + unsigned(tmp1_fu_1564_p2));
    tap_array_0_new_2_fu_1327_p3 <= 
        p_tdata_i_fu_1091_p3 when (tlast_reset(0) = '1') else 
        tdata_i;
    tap_array_10_new_2_fu_1237_p3 <= 
        p_tap_array_9_load_fu_1011_p3 when (tlast_reset(0) = '1') else 
        tap_array_9;
    tap_array_11_new_2_fu_1228_p3 <= 
        p_tap_array_10_load_fu_1003_p3 when (tlast_reset(0) = '1') else 
        tap_array_10;
    tap_array_12_new_2_fu_1219_p3 <= 
        p_tap_array_11_load_fu_995_p3 when (tlast_reset(0) = '1') else 
        tap_array_11;
    tap_array_13_new_2_fu_1210_p2 <= tap_array_12;
    tap_array_13_new_2_fu_1210_p3 <= 
        p_tap_array_12_load_fu_987_p3 when (tlast_reset(0) = '1') else 
        tap_array_13_new_2_fu_1210_p2;
    tap_array_14_new_2_fu_1201_p3 <= 
        p_tap_array_13_load_fu_979_p3 when (tlast_reset(0) = '1') else 
        tap_array_13;
    tap_array_15_new_2_fu_1192_p2 <= tap_array_14;
    tap_array_15_new_2_fu_1192_p3 <= 
        p_tap_array_14_load_fu_971_p3 when (tlast_reset(0) = '1') else 
        tap_array_15_new_2_fu_1192_p2;
    tap_array_16_new_2_fu_1183_p2 <= tap_array_15;
    tap_array_16_new_2_fu_1183_p3 <= 
        p_tap_array_15_load_fu_963_p3 when (tlast_reset(0) = '1') else 
        tap_array_16_new_2_fu_1183_p2;
    tap_array_17_new_2_fu_1174_p3 <= 
        p_tap_array_16_load_fu_955_p3 when (tlast_reset(0) = '1') else 
        tap_array_16;
    tap_array_18_new_2_fu_1165_p2 <= tap_array_17;
    tap_array_18_new_2_fu_1165_p3 <= 
        p_tap_array_17_load_fu_947_p3 when (tlast_reset(0) = '1') else 
        tap_array_18_new_2_fu_1165_p2;
    tap_array_19_new_2_fu_1156_p3 <= 
        p_tap_array_18_load_fu_939_p3 when (tlast_reset(0) = '1') else 
        tap_array_18;
    tap_array_1_new_2_fu_1318_p3 <= 
        p_tap_array_0_load_fu_1083_p3 when (tlast_reset(0) = '1') else 
        tap_array_0;
    tap_array_20_new_2_fu_1147_p3 <= 
        p_tap_array_19_load_fu_931_p3 when (tlast_reset(0) = '1') else 
        tap_array_19;
    tap_array_21_new_2_fu_1138_p3 <= 
        p_tap_array_20_load_fu_923_p3 when (tlast_reset(0) = '1') else 
        tap_array_20;
    tap_array_22_new_2_fu_1129_p3 <= 
        p_tap_array_21_load_fu_915_p3 when (tlast_reset(0) = '1') else 
        tap_array_21;
    tap_array_2_new_2_fu_1309_p3 <= 
        p_tap_array_1_load_fu_1075_p3 when (tlast_reset(0) = '1') else 
        tap_array_1;
    tap_array_30_flag_2_fu_1105_p2 <= (tlast_reset_flag_1_fu_1099_p2 or brmerge2_demorgan_fu_735_p2);
    tap_array_3_new_2_fu_1300_p3 <= 
        p_tap_array_2_load_fu_1067_p3 when (tlast_reset(0) = '1') else 
        tap_array_2;
    tap_array_4_new_2_fu_1291_p3 <= 
        p_tap_array_3_load_fu_1059_p3 when (tlast_reset(0) = '1') else 
        tap_array_3;
    tap_array_5_new_2_fu_1282_p3 <= 
        p_tap_array_4_load_fu_1051_p3 when (tlast_reset(0) = '1') else 
        tap_array_4;
    tap_array_6_new_2_fu_1273_p3 <= 
        p_tap_array_5_load_fu_1043_p3 when (tlast_reset(0) = '1') else 
        tap_array_5;
    tap_array_7_new_2_fu_1264_p3 <= 
        p_tap_array_6_load_fu_1035_p3 when (tlast_reset(0) = '1') else 
        tap_array_6;
    tap_array_8_new_2_fu_1255_p3 <= 
        p_tap_array_7_load_fu_1027_p3 when (tlast_reset(0) = '1') else 
        tap_array_7;
    tap_array_9_new_2_fu_1246_p3 <= 
        p_tap_array_8_load_fu_1019_p3 when (tlast_reset(0) = '1') else 
        tap_array_8;
    tdata_o <= grp_output_assign_fu_545_ap_return_0;

    tdata_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tdata_o_ap_vld <= ap_const_logic_1;
        else 
            tdata_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tkeep0_o <= grp_output_assign_fu_545_ap_return_3(0);

    tkeep0_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tkeep0_o_ap_vld <= ap_const_logic_1;
        else 
            tkeep0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tkeep1_o <= grp_output_assign_fu_545_ap_return_4(0);

    tkeep1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tkeep1_o_ap_vld <= ap_const_logic_1;
        else 
            tkeep1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tlast_o <= grp_output_assign_fu_545_ap_return_6(0);

    tlast_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tlast_o_ap_vld <= ap_const_logic_1;
        else 
            tlast_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tlast_reset_flag_1_fu_1099_p2 <= (tmp_1_fu_884_p2 and tlast_reset);
    tmp10_fu_1569_p2 <= std_logic_vector(signed(tmp12_reg_1722) + signed(tmp11_reg_1717));
    tmp13_fu_1577_p2 <= std_logic_vector(unsigned(tmp15_fu_1573_p2) + unsigned(tmp14_reg_1727));
    tmp15_fu_1573_p2 <= std_logic_vector(unsigned(tmp16_reg_1732) + unsigned(mult_9_reg_1702));
    tmp16_fu_872_p2 <= std_logic_vector(unsigned(tmp_16_fu_837_p2) + unsigned(tmp_17_fu_843_p2));
    tmp1_fu_1564_p2 <= std_logic_vector(unsigned(tmp5_fu_1559_p2) + unsigned(tmp2_reg_1707));
    tmp2_fu_861_p2 <= std_logic_vector(unsigned(tmp4_fu_855_p2) + unsigned(tmp3_fu_849_p2));
    tmp3_fu_849_p2 <= std_logic_vector(unsigned(tap_array_11) + unsigned(tap_array_18));
    tmp4_fu_855_p2 <= std_logic_vector(unsigned(tmp_12_fu_801_p2) + unsigned(tmp_2_fu_741_p2));
    tmp5_fu_1559_p2 <= std_logic_vector(unsigned(tmp7_reg_1712) + unsigned(tmp6_fu_1553_p2));
    tmp6_fu_1553_p2 <= std_logic_vector(unsigned(tmp_3_fu_1532_p2) + unsigned(mult_s_fu_1547_p2));
    tmp7_fu_867_p2 <= std_logic_vector(signed(grp_fu_1620_p3) + signed(mult_1_fu_753_p2));
    tmp9_fu_1582_p2 <= std_logic_vector(unsigned(tmp13_fu_1577_p2) + unsigned(tmp10_fu_1569_p2));
    tmp_10_fu_783_p2 <= std_logic_vector(shift_left(unsigned(tap_array_13),to_integer(unsigned('0' & ap_const_lv16_4(16-1 downto 0)))));
    tmp_11_fu_789_p2 <= std_logic_vector(shift_left(unsigned(tap_array_13),to_integer(unsigned('0' & ap_const_lv16_2(16-1 downto 0)))));
    tmp_12_fu_801_p2 <= std_logic_vector(shift_left(unsigned(tap_array_11),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    tmp_13_fu_807_p2 <= std_logic_vector(shift_left(unsigned(tap_array_10),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    tmp_14_fu_819_p2 <= std_logic_vector(shift_left(unsigned(tap_array_9),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    tmp_15_fu_825_p2 <= std_logic_vector(shift_left(unsigned(tap_array_9),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    tmp_16_fu_837_p2 <= std_logic_vector(shift_left(unsigned(tap_array_8),to_integer(unsigned('0' & ap_const_lv16_2(16-1 downto 0)))));
    tmp_17_fu_843_p2 <= std_logic_vector(shift_left(unsigned(tap_array_7),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    tmp_1_fu_884_p2 <= "1" when (tmp_s_fu_878_p2 = ap_const_lv8_2) else "0";
    tmp_2_fu_741_p2 <= std_logic_vector(shift_left(unsigned(tap_array_22),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    tmp_3_fu_1532_p2 <= std_logic_vector(shift_left(unsigned(tap_array_21_load_reg_1686),to_integer(unsigned('0' & ap_const_lv16_2(16-1 downto 0)))));
    tmp_4_fu_1537_p2 <= std_logic_vector(shift_left(unsigned(tap_array_20_load_reg_1691),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    tmp_5_fu_1542_p2 <= std_logic_vector(shift_left(unsigned(tap_array_20_load_reg_1691),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    tmp_6_fu_747_p2 <= std_logic_vector(shift_left(unsigned(tap_array_19),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    tmp_8_fu_765_p2 <= std_logic_vector(shift_left(unsigned(tap_array_16),to_integer(unsigned('0' & ap_const_lv16_4(16-1 downto 0)))));
    tmp_9_fu_771_p2 <= std_logic_vector(shift_left(unsigned(tap_array_16),to_integer(unsigned('0' & ap_const_lv16_2(16-1 downto 0)))));
    tmp_fu_729_p0 <= (0=>tkeep0_i, others=>'-');
    tmp_fu_729_p1 <= (0=>tkeep1_i, others=>'-');
    tmp_fu_729_p2 <= (tmp_fu_729_p1 and tmp_fu_729_p0);
    tmp_s_fu_878_p2 <= std_logic_vector(unsigned(ap_const_lv8_1) + unsigned(restore_count));
    treset_i_read_read_fu_150_p2 <= (0=>treset_i, others=>'-');
    treset_o <= grp_output_assign_fu_545_ap_return_5(0);

    treset_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            treset_o_ap_vld <= ap_const_logic_1;
        else 
            treset_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tuser_o <= grp_output_assign_fu_545_ap_return_2(0);

    tuser_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tuser_o_ap_vld <= ap_const_logic_1;
        else 
            tuser_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tvalid_o <= grp_output_assign_fu_545_ap_return_1(0);

    tvalid_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_1658, brmerge_reg_1682)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1) and (treset_i_read_reg_1658 = ap_const_lv1_1)) or ((treset_i_read_reg_1658 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (brmerge_reg_1682 = ap_const_lv1_1)) or ((brmerge_reg_1682 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tvalid_o_ap_vld <= ap_const_logic_1;
        else 
            tvalid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
