-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_HLS_axi4s_simplified is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axis_data_TREADY : IN STD_LOGIC;
    s_axis_data_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    s_axis_data_TVALID : IN STD_LOGIC;
    s_axis_data_TREADY : OUT STD_LOGIC;
    s_axis_data_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    s_axis_data_TLAST : IN STD_LOGIC;
    m_axis_data_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axis_data_TVALID : OUT STD_LOGIC;
    m_axis_data_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axis_data_TLAST : OUT STD_LOGIC );
end;


architecture behav of fir_HLS_axi4s_simplified is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fir_HLS_axi4s_simplified,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=102,HLS_SYN_LUT=244,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal s_axis_data_data_V_0_vld_out : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal m_axis_data_data_V_1_ack_in : STD_LOGIC;
    signal m_axis_data_keep_V_1_ack_in : STD_LOGIC;
    signal m_axis_data_last_1_ack_in : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal s_axis_data_data_V_0_data_out : STD_LOGIC_VECTOR (15 downto 0);
    signal s_axis_data_data_V_0_vld_in : STD_LOGIC;
    signal s_axis_data_data_V_0_ack_in : STD_LOGIC;
    signal s_axis_data_data_V_0_ack_out : STD_LOGIC;
    signal s_axis_data_data_V_0_payload_A : STD_LOGIC_VECTOR (15 downto 0);
    signal s_axis_data_data_V_0_payload_B : STD_LOGIC_VECTOR (15 downto 0);
    signal s_axis_data_data_V_0_sel_rd : STD_LOGIC := '0';
    signal s_axis_data_data_V_0_sel_wr : STD_LOGIC := '0';
    signal s_axis_data_data_V_0_sel : STD_LOGIC;
    signal s_axis_data_data_V_0_load_A : STD_LOGIC;
    signal s_axis_data_data_V_0_load_B : STD_LOGIC;
    signal s_axis_data_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal s_axis_data_data_V_0_state_cmp_full : STD_LOGIC;
    signal s_axis_data_keep_V_0_data_out : STD_LOGIC_VECTOR (1 downto 0);
    signal s_axis_data_keep_V_0_vld_in : STD_LOGIC;
    signal s_axis_data_keep_V_0_vld_out : STD_LOGIC;
    signal s_axis_data_keep_V_0_ack_in : STD_LOGIC;
    signal s_axis_data_keep_V_0_ack_out : STD_LOGIC;
    signal s_axis_data_keep_V_0_payload_A : STD_LOGIC_VECTOR (1 downto 0);
    signal s_axis_data_keep_V_0_payload_B : STD_LOGIC_VECTOR (1 downto 0);
    signal s_axis_data_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal s_axis_data_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal s_axis_data_keep_V_0_sel : STD_LOGIC;
    signal s_axis_data_keep_V_0_load_A : STD_LOGIC;
    signal s_axis_data_keep_V_0_load_B : STD_LOGIC;
    signal s_axis_data_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal s_axis_data_keep_V_0_state_cmp_full : STD_LOGIC;
    signal s_axis_data_last_0_data_out : STD_LOGIC;
    signal s_axis_data_last_0_vld_in : STD_LOGIC;
    signal s_axis_data_last_0_vld_out : STD_LOGIC;
    signal s_axis_data_last_0_ack_in : STD_LOGIC;
    signal s_axis_data_last_0_ack_out : STD_LOGIC;
    signal s_axis_data_last_0_payload_A : STD_LOGIC;
    signal s_axis_data_last_0_payload_B : STD_LOGIC;
    signal s_axis_data_last_0_sel_rd : STD_LOGIC := '0';
    signal s_axis_data_last_0_sel_wr : STD_LOGIC := '0';
    signal s_axis_data_last_0_sel : STD_LOGIC;
    signal s_axis_data_last_0_load_A : STD_LOGIC;
    signal s_axis_data_last_0_load_B : STD_LOGIC;
    signal s_axis_data_last_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal s_axis_data_last_0_state_cmp_full : STD_LOGIC;
    signal m_axis_data_data_V_1_data_out : STD_LOGIC_VECTOR (15 downto 0);
    signal m_axis_data_data_V_1_vld_in : STD_LOGIC;
    signal m_axis_data_data_V_1_vld_out : STD_LOGIC;
    signal m_axis_data_data_V_1_ack_out : STD_LOGIC;
    signal m_axis_data_data_V_1_payload_A : STD_LOGIC_VECTOR (15 downto 0);
    signal m_axis_data_data_V_1_payload_B : STD_LOGIC_VECTOR (15 downto 0);
    signal m_axis_data_data_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_data_data_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_data_data_V_1_sel : STD_LOGIC;
    signal m_axis_data_data_V_1_load_A : STD_LOGIC;
    signal m_axis_data_data_V_1_load_B : STD_LOGIC;
    signal m_axis_data_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_data_data_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_data_keep_V_1_data_out : STD_LOGIC_VECTOR (1 downto 0);
    signal m_axis_data_keep_V_1_vld_in : STD_LOGIC;
    signal m_axis_data_keep_V_1_vld_out : STD_LOGIC;
    signal m_axis_data_keep_V_1_ack_out : STD_LOGIC;
    signal m_axis_data_keep_V_1_payload_A : STD_LOGIC_VECTOR (1 downto 0);
    signal m_axis_data_keep_V_1_payload_B : STD_LOGIC_VECTOR (1 downto 0);
    signal m_axis_data_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_data_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_data_keep_V_1_sel : STD_LOGIC;
    signal m_axis_data_keep_V_1_load_A : STD_LOGIC;
    signal m_axis_data_keep_V_1_load_B : STD_LOGIC;
    signal m_axis_data_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_data_keep_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_data_last_1_data_out : STD_LOGIC;
    signal m_axis_data_last_1_vld_in : STD_LOGIC;
    signal m_axis_data_last_1_vld_out : STD_LOGIC;
    signal m_axis_data_last_1_ack_out : STD_LOGIC;
    signal m_axis_data_last_1_payload_A : STD_LOGIC;
    signal m_axis_data_last_1_payload_B : STD_LOGIC;
    signal m_axis_data_last_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_data_last_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_data_last_1_sel : STD_LOGIC;
    signal m_axis_data_last_1_load_A : STD_LOGIC;
    signal m_axis_data_last_1_load_B : STD_LOGIC;
    signal m_axis_data_last_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_data_last_1_state_cmp_full : STD_LOGIC;
    signal s_axis_data_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal m_axis_data_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_data_data_V_1_ack_out = ap_const_logic_1) and (m_axis_data_data_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_data_data_V_1_sel_rd <= not(m_axis_data_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_data_data_V_1_ack_in = ap_const_logic_1) and (m_axis_data_data_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_data_data_V_1_sel_wr <= not(m_axis_data_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_data_data_V_1_state = ap_const_lv2_2) and (m_axis_data_data_V_1_vld_in = ap_const_logic_0)) or ((m_axis_data_data_V_1_state = ap_const_lv2_3) and (m_axis_data_data_V_1_vld_in = ap_const_logic_0) and (m_axis_data_data_V_1_ack_out = ap_const_logic_1)))) then 
                    m_axis_data_data_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_data_data_V_1_state = ap_const_lv2_1) and (m_axis_data_data_V_1_ack_out = ap_const_logic_0)) or ((m_axis_data_data_V_1_state = ap_const_lv2_3) and (m_axis_data_data_V_1_ack_out = ap_const_logic_0) and (m_axis_data_data_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((m_axis_data_data_V_1_vld_in = ap_const_logic_0) and (m_axis_data_data_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_data_data_V_1_ack_out = ap_const_logic_0) and (m_axis_data_data_V_1_vld_in = ap_const_logic_1))) and (m_axis_data_data_V_1_state = ap_const_lv2_3)) or ((m_axis_data_data_V_1_state = ap_const_lv2_1) and (m_axis_data_data_V_1_ack_out = ap_const_logic_1)) or ((m_axis_data_data_V_1_state = ap_const_lv2_2) and (m_axis_data_data_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_data_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_data_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_data_keep_V_1_ack_out = ap_const_logic_1) and (m_axis_data_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_data_keep_V_1_sel_rd <= not(m_axis_data_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_data_keep_V_1_ack_in = ap_const_logic_1) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_data_keep_V_1_sel_wr <= not(m_axis_data_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_data_keep_V_1_state = ap_const_lv2_2) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_0)) or ((m_axis_data_keep_V_1_state = ap_const_lv2_3) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_0) and (m_axis_data_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    m_axis_data_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_data_keep_V_1_state = ap_const_lv2_1) and (m_axis_data_keep_V_1_ack_out = ap_const_logic_0)) or ((m_axis_data_keep_V_1_state = ap_const_lv2_3) and (m_axis_data_keep_V_1_ack_out = ap_const_logic_0) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((m_axis_data_keep_V_1_vld_in = ap_const_logic_0) and (m_axis_data_keep_V_1_ack_out = ap_const_logic_1))) and not(((m_axis_data_keep_V_1_ack_out = ap_const_logic_0) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_1))) and (m_axis_data_keep_V_1_state = ap_const_lv2_3)) or ((m_axis_data_keep_V_1_state = ap_const_lv2_1) and (m_axis_data_keep_V_1_ack_out = ap_const_logic_1)) or ((m_axis_data_keep_V_1_state = ap_const_lv2_2) and (m_axis_data_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_keep_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_data_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_last_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_last_1_sel_rd <= ap_const_logic_0;
            else
                if (((m_axis_data_last_1_ack_out = ap_const_logic_1) and (m_axis_data_last_1_vld_out = ap_const_logic_1))) then 
                                        m_axis_data_last_1_sel_rd <= not(m_axis_data_last_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_last_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_last_1_sel_wr <= ap_const_logic_0;
            else
                if (((m_axis_data_last_1_ack_in = ap_const_logic_1) and (m_axis_data_last_1_vld_in = ap_const_logic_1))) then 
                                        m_axis_data_last_1_sel_wr <= not(m_axis_data_last_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_data_last_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                m_axis_data_last_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_data_last_1_state = ap_const_lv2_2) and (m_axis_data_last_1_vld_in = ap_const_logic_0)) or ((m_axis_data_last_1_state = ap_const_lv2_3) and (m_axis_data_last_1_vld_in = ap_const_logic_0) and (m_axis_data_last_1_ack_out = ap_const_logic_1)))) then 
                    m_axis_data_last_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_data_last_1_state = ap_const_lv2_1) and (m_axis_data_last_1_ack_out = ap_const_logic_0)) or ((m_axis_data_last_1_state = ap_const_lv2_3) and (m_axis_data_last_1_ack_out = ap_const_logic_0) and (m_axis_data_last_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_last_1_state <= ap_const_lv2_1;
                elsif (((not(((m_axis_data_last_1_vld_in = ap_const_logic_0) and (m_axis_data_last_1_ack_out = ap_const_logic_1))) and not(((m_axis_data_last_1_ack_out = ap_const_logic_0) and (m_axis_data_last_1_vld_in = ap_const_logic_1))) and (m_axis_data_last_1_state = ap_const_lv2_3)) or ((m_axis_data_last_1_state = ap_const_lv2_1) and (m_axis_data_last_1_ack_out = ap_const_logic_1)) or ((m_axis_data_last_1_state = ap_const_lv2_2) and (m_axis_data_last_1_vld_in = ap_const_logic_1)))) then 
                    m_axis_data_last_1_state <= ap_const_lv2_3;
                else 
                    m_axis_data_last_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((s_axis_data_data_V_0_ack_out = ap_const_logic_1) and (s_axis_data_data_V_0_vld_out = ap_const_logic_1))) then 
                                        s_axis_data_data_V_0_sel_rd <= not(s_axis_data_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((s_axis_data_data_V_0_ack_in = ap_const_logic_1) and (s_axis_data_data_V_0_vld_in = ap_const_logic_1))) then 
                                        s_axis_data_data_V_0_sel_wr <= not(s_axis_data_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((s_axis_data_data_V_0_state = ap_const_lv2_2) and (s_axis_data_data_V_0_vld_in = ap_const_logic_0)) or ((s_axis_data_data_V_0_state = ap_const_lv2_3) and (s_axis_data_data_V_0_vld_in = ap_const_logic_0) and (s_axis_data_data_V_0_ack_out = ap_const_logic_1)))) then 
                    s_axis_data_data_V_0_state <= ap_const_lv2_2;
                elsif ((((s_axis_data_data_V_0_state = ap_const_lv2_1) and (s_axis_data_data_V_0_ack_out = ap_const_logic_0)) or ((s_axis_data_data_V_0_state = ap_const_lv2_3) and (s_axis_data_data_V_0_ack_out = ap_const_logic_0) and (s_axis_data_data_V_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((s_axis_data_data_V_0_ack_out = ap_const_logic_0) and (s_axis_data_data_V_0_vld_in = ap_const_logic_1))) and not(((s_axis_data_data_V_0_vld_in = ap_const_logic_0) and (s_axis_data_data_V_0_ack_out = ap_const_logic_1))) and (s_axis_data_data_V_0_state = ap_const_lv2_3)) or ((s_axis_data_data_V_0_state = ap_const_lv2_1) and (s_axis_data_data_V_0_ack_out = ap_const_logic_1)) or ((s_axis_data_data_V_0_state = ap_const_lv2_2) and (s_axis_data_data_V_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_data_V_0_state <= ap_const_lv2_3;
                else 
                    s_axis_data_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((s_axis_data_keep_V_0_ack_out = ap_const_logic_1) and (s_axis_data_keep_V_0_vld_out = ap_const_logic_1))) then 
                                        s_axis_data_keep_V_0_sel_rd <= not(s_axis_data_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((s_axis_data_keep_V_0_ack_in = ap_const_logic_1) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_1))) then 
                                        s_axis_data_keep_V_0_sel_wr <= not(s_axis_data_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((s_axis_data_keep_V_0_state = ap_const_lv2_2) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_0)) or ((s_axis_data_keep_V_0_state = ap_const_lv2_3) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_0) and (s_axis_data_keep_V_0_ack_out = ap_const_logic_1)))) then 
                    s_axis_data_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((s_axis_data_keep_V_0_state = ap_const_lv2_1) and (s_axis_data_keep_V_0_ack_out = ap_const_logic_0)) or ((s_axis_data_keep_V_0_state = ap_const_lv2_3) and (s_axis_data_keep_V_0_ack_out = ap_const_logic_0) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_keep_V_0_state <= ap_const_lv2_1;
                elsif (((not(((s_axis_data_keep_V_0_vld_in = ap_const_logic_0) and (s_axis_data_keep_V_0_ack_out = ap_const_logic_1))) and not(((s_axis_data_keep_V_0_ack_out = ap_const_logic_0) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_1))) and (s_axis_data_keep_V_0_state = ap_const_lv2_3)) or ((s_axis_data_keep_V_0_state = ap_const_lv2_1) and (s_axis_data_keep_V_0_ack_out = ap_const_logic_1)) or ((s_axis_data_keep_V_0_state = ap_const_lv2_2) and (s_axis_data_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_keep_V_0_state <= ap_const_lv2_3;
                else 
                    s_axis_data_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_last_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_last_0_sel_rd <= ap_const_logic_0;
            else
                if (((s_axis_data_last_0_ack_out = ap_const_logic_1) and (s_axis_data_last_0_vld_out = ap_const_logic_1))) then 
                                        s_axis_data_last_0_sel_rd <= not(s_axis_data_last_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_last_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_last_0_sel_wr <= ap_const_logic_0;
            else
                if (((s_axis_data_last_0_ack_in = ap_const_logic_1) and (s_axis_data_last_0_vld_in = ap_const_logic_1))) then 
                                        s_axis_data_last_0_sel_wr <= not(s_axis_data_last_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    s_axis_data_last_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                s_axis_data_last_0_state <= ap_const_lv2_0;
            else
                if ((((s_axis_data_last_0_state = ap_const_lv2_2) and (s_axis_data_last_0_vld_in = ap_const_logic_0)) or ((s_axis_data_last_0_state = ap_const_lv2_3) and (s_axis_data_last_0_vld_in = ap_const_logic_0) and (s_axis_data_last_0_ack_out = ap_const_logic_1)))) then 
                    s_axis_data_last_0_state <= ap_const_lv2_2;
                elsif ((((s_axis_data_last_0_state = ap_const_lv2_1) and (s_axis_data_last_0_ack_out = ap_const_logic_0)) or ((s_axis_data_last_0_state = ap_const_lv2_3) and (s_axis_data_last_0_ack_out = ap_const_logic_0) and (s_axis_data_last_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_last_0_state <= ap_const_lv2_1;
                elsif (((not(((s_axis_data_last_0_vld_in = ap_const_logic_0) and (s_axis_data_last_0_ack_out = ap_const_logic_1))) and not(((s_axis_data_last_0_ack_out = ap_const_logic_0) and (s_axis_data_last_0_vld_in = ap_const_logic_1))) and (s_axis_data_last_0_state = ap_const_lv2_3)) or ((s_axis_data_last_0_state = ap_const_lv2_1) and (s_axis_data_last_0_ack_out = ap_const_logic_1)) or ((s_axis_data_last_0_state = ap_const_lv2_2) and (s_axis_data_last_0_vld_in = ap_const_logic_1)))) then 
                    s_axis_data_last_0_state <= ap_const_lv2_3;
                else 
                    s_axis_data_last_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_data_V_1_load_A = ap_const_logic_1)) then
                m_axis_data_data_V_1_payload_A <= s_axis_data_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_data_V_1_load_B = ap_const_logic_1)) then
                m_axis_data_data_V_1_payload_B <= s_axis_data_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_keep_V_1_load_A = ap_const_logic_1)) then
                m_axis_data_keep_V_1_payload_A <= s_axis_data_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_keep_V_1_load_B = ap_const_logic_1)) then
                m_axis_data_keep_V_1_payload_B <= s_axis_data_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_last_1_load_A = ap_const_logic_1)) then
                m_axis_data_last_1_payload_A <= s_axis_data_last_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((m_axis_data_last_1_load_B = ap_const_logic_1)) then
                m_axis_data_last_1_payload_B <= s_axis_data_last_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_data_V_0_load_A = ap_const_logic_1)) then
                s_axis_data_data_V_0_payload_A <= s_axis_data_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_data_V_0_load_B = ap_const_logic_1)) then
                s_axis_data_data_V_0_payload_B <= s_axis_data_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_keep_V_0_load_A = ap_const_logic_1)) then
                s_axis_data_keep_V_0_payload_A <= s_axis_data_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_keep_V_0_load_B = ap_const_logic_1)) then
                s_axis_data_keep_V_0_payload_B <= s_axis_data_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_last_0_load_A = ap_const_logic_1)) then
                s_axis_data_last_0_payload_A <= s_axis_data_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((s_axis_data_last_0_load_B = ap_const_logic_1)) then
                s_axis_data_last_0_payload_B <= s_axis_data_TLAST;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, s_axis_data_data_V_0_vld_out, m_axis_data_data_V_1_ack_in, m_axis_data_keep_V_1_ack_in, m_axis_data_last_1_ack_in)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axis_data_last_1_ack_in = ap_const_logic_0) or (m_axis_data_keep_V_1_ack_in = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (s_axis_data_data_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, s_axis_data_data_V_0_vld_out, m_axis_data_data_V_1_ack_in, m_axis_data_keep_V_1_ack_in, m_axis_data_last_1_ack_in)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axis_data_last_1_ack_in = ap_const_logic_0) or (m_axis_data_keep_V_1_ack_in = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0) or (s_axis_data_data_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, s_axis_data_data_V_0_vld_out, m_axis_data_data_V_1_ack_in, m_axis_data_keep_V_1_ack_in, m_axis_data_last_1_ack_in)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((m_axis_data_last_1_ack_in = ap_const_logic_0) or (m_axis_data_keep_V_1_ack_in = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0) or (s_axis_data_data_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, s_axis_data_data_V_0_vld_out)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (s_axis_data_data_V_0_vld_out = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axis_data_data_V_1_ack_in, m_axis_data_keep_V_1_ack_in, m_axis_data_last_1_ack_in)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((m_axis_data_last_1_ack_in = ap_const_logic_0) or (m_axis_data_keep_V_1_ack_in = ap_const_logic_0) or (m_axis_data_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    m_axis_data_TDATA <= m_axis_data_data_V_1_data_out;

    m_axis_data_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axis_data_data_V_1_state, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            m_axis_data_TDATA_blk_n <= m_axis_data_data_V_1_state(1);
        else 
            m_axis_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_data_TKEEP <= m_axis_data_keep_V_1_data_out;
    m_axis_data_TLAST <= m_axis_data_last_1_data_out;
    m_axis_data_TVALID <= m_axis_data_last_1_state(0);
    m_axis_data_data_V_1_ack_in <= m_axis_data_data_V_1_state(1);
    m_axis_data_data_V_1_ack_out <= m_axis_data_TREADY;

    m_axis_data_data_V_1_data_out_assign_proc : process(m_axis_data_data_V_1_payload_A, m_axis_data_data_V_1_payload_B, m_axis_data_data_V_1_sel)
    begin
        if ((m_axis_data_data_V_1_sel = ap_const_logic_1)) then 
            m_axis_data_data_V_1_data_out <= m_axis_data_data_V_1_payload_B;
        else 
            m_axis_data_data_V_1_data_out <= m_axis_data_data_V_1_payload_A;
        end if; 
    end process;

    m_axis_data_data_V_1_load_A <= (m_axis_data_data_V_1_state_cmp_full and not(m_axis_data_data_V_1_sel_wr));
    m_axis_data_data_V_1_load_B <= (m_axis_data_data_V_1_state_cmp_full and m_axis_data_data_V_1_sel_wr);
    m_axis_data_data_V_1_sel <= m_axis_data_data_V_1_sel_rd;
    m_axis_data_data_V_1_state_cmp_full <= '0' when (m_axis_data_data_V_1_state = ap_const_lv2_1) else '1';

    m_axis_data_data_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_data_data_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_data_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_data_data_V_1_vld_out <= m_axis_data_data_V_1_state(0);
    m_axis_data_keep_V_1_ack_in <= m_axis_data_keep_V_1_state(1);
    m_axis_data_keep_V_1_ack_out <= m_axis_data_TREADY;

    m_axis_data_keep_V_1_data_out_assign_proc : process(m_axis_data_keep_V_1_payload_A, m_axis_data_keep_V_1_payload_B, m_axis_data_keep_V_1_sel)
    begin
        if ((m_axis_data_keep_V_1_sel = ap_const_logic_1)) then 
            m_axis_data_keep_V_1_data_out <= m_axis_data_keep_V_1_payload_B;
        else 
            m_axis_data_keep_V_1_data_out <= m_axis_data_keep_V_1_payload_A;
        end if; 
    end process;

    m_axis_data_keep_V_1_load_A <= (m_axis_data_keep_V_1_state_cmp_full and not(m_axis_data_keep_V_1_sel_wr));
    m_axis_data_keep_V_1_load_B <= (m_axis_data_keep_V_1_state_cmp_full and m_axis_data_keep_V_1_sel_wr);
    m_axis_data_keep_V_1_sel <= m_axis_data_keep_V_1_sel_rd;
    m_axis_data_keep_V_1_state_cmp_full <= '0' when (m_axis_data_keep_V_1_state = ap_const_lv2_1) else '1';

    m_axis_data_keep_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_data_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_data_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_data_keep_V_1_vld_out <= m_axis_data_keep_V_1_state(0);
    m_axis_data_last_1_ack_in <= m_axis_data_last_1_state(1);
    m_axis_data_last_1_ack_out <= m_axis_data_TREADY;

    m_axis_data_last_1_data_out_assign_proc : process(m_axis_data_last_1_payload_A, m_axis_data_last_1_payload_B, m_axis_data_last_1_sel)
    begin
        if ((m_axis_data_last_1_sel = ap_const_logic_1)) then 
            m_axis_data_last_1_data_out <= m_axis_data_last_1_payload_B;
        else 
            m_axis_data_last_1_data_out <= m_axis_data_last_1_payload_A;
        end if; 
    end process;

    m_axis_data_last_1_load_A <= (m_axis_data_last_1_state_cmp_full and not(m_axis_data_last_1_sel_wr));
    m_axis_data_last_1_load_B <= (m_axis_data_last_1_state_cmp_full and m_axis_data_last_1_sel_wr);
    m_axis_data_last_1_sel <= m_axis_data_last_1_sel_rd;
    m_axis_data_last_1_state_cmp_full <= '0' when (m_axis_data_last_1_state = ap_const_lv2_1) else '1';

    m_axis_data_last_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_data_last_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_data_last_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_data_last_1_vld_out <= m_axis_data_last_1_state(0);

    s_axis_data_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, s_axis_data_data_V_0_state, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_data_TDATA_blk_n <= s_axis_data_data_V_0_state(0);
        else 
            s_axis_data_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_data_TREADY <= s_axis_data_last_0_state(1);
    s_axis_data_data_V_0_ack_in <= s_axis_data_data_V_0_state(1);

    s_axis_data_data_V_0_ack_out_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_data_data_V_0_ack_out <= ap_const_logic_1;
        else 
            s_axis_data_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_data_data_V_0_data_out_assign_proc : process(s_axis_data_data_V_0_payload_A, s_axis_data_data_V_0_payload_B, s_axis_data_data_V_0_sel)
    begin
        if ((s_axis_data_data_V_0_sel = ap_const_logic_1)) then 
            s_axis_data_data_V_0_data_out <= s_axis_data_data_V_0_payload_B;
        else 
            s_axis_data_data_V_0_data_out <= s_axis_data_data_V_0_payload_A;
        end if; 
    end process;

    s_axis_data_data_V_0_load_A <= (s_axis_data_data_V_0_state_cmp_full and not(s_axis_data_data_V_0_sel_wr));
    s_axis_data_data_V_0_load_B <= (s_axis_data_data_V_0_state_cmp_full and s_axis_data_data_V_0_sel_wr);
    s_axis_data_data_V_0_sel <= s_axis_data_data_V_0_sel_rd;
    s_axis_data_data_V_0_state_cmp_full <= '0' when (s_axis_data_data_V_0_state = ap_const_lv2_1) else '1';
    s_axis_data_data_V_0_vld_in <= s_axis_data_TVALID;
    s_axis_data_data_V_0_vld_out <= s_axis_data_data_V_0_state(0);
    s_axis_data_keep_V_0_ack_in <= s_axis_data_keep_V_0_state(1);

    s_axis_data_keep_V_0_ack_out_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_data_keep_V_0_ack_out <= ap_const_logic_1;
        else 
            s_axis_data_keep_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_data_keep_V_0_data_out_assign_proc : process(s_axis_data_keep_V_0_payload_A, s_axis_data_keep_V_0_payload_B, s_axis_data_keep_V_0_sel)
    begin
        if ((s_axis_data_keep_V_0_sel = ap_const_logic_1)) then 
            s_axis_data_keep_V_0_data_out <= s_axis_data_keep_V_0_payload_B;
        else 
            s_axis_data_keep_V_0_data_out <= s_axis_data_keep_V_0_payload_A;
        end if; 
    end process;

    s_axis_data_keep_V_0_load_A <= (s_axis_data_keep_V_0_state_cmp_full and not(s_axis_data_keep_V_0_sel_wr));
    s_axis_data_keep_V_0_load_B <= (s_axis_data_keep_V_0_state_cmp_full and s_axis_data_keep_V_0_sel_wr);
    s_axis_data_keep_V_0_sel <= s_axis_data_keep_V_0_sel_rd;
    s_axis_data_keep_V_0_state_cmp_full <= '0' when (s_axis_data_keep_V_0_state = ap_const_lv2_1) else '1';
    s_axis_data_keep_V_0_vld_in <= s_axis_data_TVALID;
    s_axis_data_keep_V_0_vld_out <= s_axis_data_keep_V_0_state(0);
    s_axis_data_last_0_ack_in <= s_axis_data_last_0_state(1);

    s_axis_data_last_0_ack_out_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_axis_data_last_0_ack_out <= ap_const_logic_1;
        else 
            s_axis_data_last_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_data_last_0_data_out_assign_proc : process(s_axis_data_last_0_payload_A, s_axis_data_last_0_payload_B, s_axis_data_last_0_sel)
    begin
        if ((s_axis_data_last_0_sel = ap_const_logic_1)) then 
            s_axis_data_last_0_data_out <= s_axis_data_last_0_payload_B;
        else 
            s_axis_data_last_0_data_out <= s_axis_data_last_0_payload_A;
        end if; 
    end process;

    s_axis_data_last_0_load_A <= (s_axis_data_last_0_state_cmp_full and not(s_axis_data_last_0_sel_wr));
    s_axis_data_last_0_load_B <= (s_axis_data_last_0_state_cmp_full and s_axis_data_last_0_sel_wr);
    s_axis_data_last_0_sel <= s_axis_data_last_0_sel_rd;
    s_axis_data_last_0_state_cmp_full <= '0' when (s_axis_data_last_0_state = ap_const_lv2_1) else '1';
    s_axis_data_last_0_vld_in <= s_axis_data_TVALID;
    s_axis_data_last_0_vld_out <= s_axis_data_last_0_state(0);
end behav;
