-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity output_assign is
port (
    ap_ready : OUT STD_LOGIC;
    tdata_assign : IN STD_LOGIC_VECTOR (15 downto 0);
    tvalid_assign : IN STD_LOGIC;
    tuser_assign : IN STD_LOGIC;
    tkeep0_assign : IN STD_LOGIC;
    tkeep1_assign : IN STD_LOGIC;
    treset_assign : IN STD_LOGIC;
    tlast_assign : IN STD_LOGIC;
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of output_assign is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';



begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= tdata_assign;
    ap_return_1 <= (0=>tvalid_assign, others=>'-');
    ap_return_2 <= (0=>tuser_assign, others=>'-');
    ap_return_3 <= (0=>tkeep0_assign, others=>'-');
    ap_return_4 <= (0=>tkeep1_assign, others=>'-');
    ap_return_5 <= (0=>treset_assign, others=>'-');
    ap_return_6 <= (0=>tlast_assign, others=>'-');
end behav;
