-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ped_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    channel_i : IN STD_LOGIC_VECTOR (15 downto 0);
    channel_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    channel_o_ap_vld : OUT STD_LOGIC;
    tdata : IN STD_LOGIC_VECTOR (15 downto 0);
    def_ped : IN STD_LOGIC_VECTOR (15 downto 0);
    tvalid_in : IN STD_LOGIC;
    tlast_user_in : IN STD_LOGIC;
    tkeep_in : IN STD_LOGIC;
    ped_array_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    ped_array_ce0 : OUT STD_LOGIC;
    ped_array_we0 : OUT STD_LOGIC;
    ped_array_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ped_array_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    ADC_adjusted : OUT STD_LOGIC_VECTOR (15 downto 0);
    ADC_adjusted_ap_vld : OUT STD_LOGIC;
    accum_array_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    accum_array_ce0 : OUT STD_LOGIC;
    accum_array_we0 : OUT STD_LOGIC;
    accum_array_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    accum_array_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    tready_in : IN STD_LOGIC;
    treset_in : IN STD_LOGIC;
    tvalid_out : OUT STD_LOGIC;
    tvalid_out_ap_vld : OUT STD_LOGIC;
    tkeep_out : OUT STD_LOGIC;
    tkeep_out_ap_vld : OUT STD_LOGIC;
    tlast_user_out : OUT STD_LOGIC;
    tlast_user_out_ap_vld : OUT STD_LOGIC;
    tready_out : OUT STD_LOGIC;
    tready_out_ap_vld : OUT STD_LOGIC;
    treset_out : OUT STD_LOGIC;
    treset_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ped_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ped_top,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.804000,HLS_SYN_LAT=37,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=76,HLS_SYN_LUT=542,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv8_F7 : STD_LOGIC_VECTOR (7 downto 0) := "11110111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_40 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal treset_in_read_read_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ped_array_addr_reg_455 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal accum_array_addr_reg_460 : STD_LOGIC_VECTOR (5 downto 0);
    signal ped_new_1_reg_465 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal accum_1_reg_473 : STD_LOGIC_VECTOR (7 downto 0);
    signal accum_1_i_fu_296_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal accum_1_i_reg_478 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ped_accum_reset_fu_250_ap_start : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ap_done : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ap_idle : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ap_ready : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ped_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_ped_accum_reset_fu_250_ped_array_ce0 : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ped_array_we0 : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_ped_array_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_ped_accum_reset_fu_250_accum_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_ped_accum_reset_fu_250_accum_array_ce0 : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_accum_array_we0 : STD_LOGIC;
    signal grp_ped_accum_reset_fu_250_accum_array_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal channel_loc_reg_225 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal channel_flag_reg_237 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ped_accum_reset_fu_250_ap_start_reg : STD_LOGIC := '0';
    signal tmp_fu_260_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal channel_new_1_fu_417_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal channel_flag_1_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ped_new_fu_389_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal accum_fu_381_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_i_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_i_fu_282_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_i_fu_271_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_read1_i_fu_288_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp1_fu_304_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_304_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_demorgan_i_fu_310_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_demorgan_i_fu_310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge6_i_fu_322_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_i_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_2_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_fu_342_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_i_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_i_fu_332_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_read_i_fu_347_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_val_1_i_fu_367_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal brmerge6_i_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_3_i_fu_360_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_397_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_403_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal channel_new_1_fu_417_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_409_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal channel_flag_1_fu_426_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component ped_accum_reset IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ped_array_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        ped_array_ce0 : OUT STD_LOGIC;
        ped_array_we0 : OUT STD_LOGIC;
        ped_array_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        accum_array_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        accum_array_ce0 : OUT STD_LOGIC;
        accum_array_we0 : OUT STD_LOGIC;
        accum_array_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        ped_val : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_ped_accum_reset_fu_250 : component ped_accum_reset
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_ped_accum_reset_fu_250_ap_start,
        ap_done => grp_ped_accum_reset_fu_250_ap_done,
        ap_idle => grp_ped_accum_reset_fu_250_ap_idle,
        ap_ready => grp_ped_accum_reset_fu_250_ap_ready,
        ped_array_address0 => grp_ped_accum_reset_fu_250_ped_array_address0,
        ped_array_ce0 => grp_ped_accum_reset_fu_250_ped_array_ce0,
        ped_array_we0 => grp_ped_accum_reset_fu_250_ped_array_we0,
        ped_array_d0 => grp_ped_accum_reset_fu_250_ped_array_d0,
        accum_array_address0 => grp_ped_accum_reset_fu_250_accum_array_address0,
        accum_array_ce0 => grp_ped_accum_reset_fu_250_accum_array_ce0,
        accum_array_we0 => grp_ped_accum_reset_fu_250_accum_array_we0,
        accum_array_d0 => grp_ped_accum_reset_fu_250_accum_array_d0,
        ped_val => def_ped);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_ped_accum_reset_fu_250_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_ped_accum_reset_fu_250_ap_start_reg <= ap_const_logic_0;
            else
                if (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_ped_accum_reset_fu_250_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ped_accum_reset_fu_250_ap_ready = ap_const_logic_1)) then 
                    grp_ped_accum_reset_fu_250_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    channel_flag_reg_237_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((treset_in_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                channel_flag_reg_237 <= ap_const_lv1_0;
            elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
                channel_flag_reg_237 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    channel_loc_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((treset_in_read_read_fu_104_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                channel_loc_reg_225 <= channel_i;
            elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then 
                channel_loc_reg_225 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                accum_1_i_reg_478 <= accum_1_i_fu_296_p3;
                accum_1_reg_473 <= accum_array_q0;
                ped_new_1_reg_465 <= ped_array_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                accum_array_addr_reg_460 <= tmp_fu_260_p1(6 - 1 downto 0);
                ped_array_addr_reg_455 <= tmp_fu_260_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ADC_adjusted <= std_logic_vector(unsigned(tdata) - unsigned(ped_val_1_i_fu_367_p3));

    ADC_adjusted_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ADC_adjusted_ap_vld <= ap_const_logic_1;
        else 
            ADC_adjusted_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    accum_1_i_fu_296_p3 <= 
        tmp_5_i_fu_271_p2 when (tmp_i_fu_266_p2(0) = '1') else 
        tmp_7_read1_i_fu_288_p3;
    accum_3_i_fu_360_p3 <= 
        ap_const_lv8_0 when (tmp_1_fu_354_p2(0) = '1') else 
        accum_1_i_reg_478;

    accum_array_address0_assign_proc : process(treset_in_read_read_fu_104_p2, ap_CS_fsm_state3, accum_array_addr_reg_460, grp_ped_accum_reset_fu_250_accum_array_address0, ap_CS_fsm_state2, tmp_fu_260_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            accum_array_address0 <= accum_array_addr_reg_460;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            accum_array_address0 <= tmp_fu_260_p1(6 - 1 downto 0);
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_array_address0 <= grp_ped_accum_reset_fu_250_accum_array_address0;
        else 
            accum_array_address0 <= "XXXXXX";
        end if; 
    end process;


    accum_array_ce0_assign_proc : process(treset_in_read_read_fu_104_p2, ap_CS_fsm_state3, grp_ped_accum_reset_fu_250_accum_array_ce0, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            accum_array_ce0 <= ap_const_logic_1;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_array_ce0 <= grp_ped_accum_reset_fu_250_accum_array_ce0;
        else 
            accum_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    accum_array_d0_assign_proc : process(treset_in_read_read_fu_104_p2, grp_ped_accum_reset_fu_250_accum_array_d0, ap_CS_fsm_state2, ap_CS_fsm_state5, accum_fu_381_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            accum_array_d0 <= accum_fu_381_p3;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_array_d0 <= grp_ped_accum_reset_fu_250_accum_array_d0;
        else 
            accum_array_d0 <= "XXXXXXXX";
        end if; 
    end process;


    accum_array_we0_assign_proc : process(treset_in_read_read_fu_104_p2, grp_ped_accum_reset_fu_250_accum_array_we0, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            accum_array_we0 <= ap_const_logic_1;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            accum_array_we0 <= grp_ped_accum_reset_fu_250_accum_array_we0;
        else 
            accum_array_we0 <= ap_const_logic_0;
        end if; 
    end process;

    accum_fu_381_p3 <= 
        accum_1_reg_473 when (brmerge6_i_fu_322_p2(0) = '1') else 
        accum_3_i_fu_360_p3;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state2_on_subcall_done_assign_proc : process(treset_in_read_read_fu_104_p2, grp_ped_accum_reset_fu_250_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (grp_ped_accum_reset_fu_250_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge5_demorgan_i_fu_310_p1 <= (0=>tready_in, others=>'-');
    brmerge5_demorgan_i_fu_310_p2 <= (tmp1_fu_304_p2 and brmerge5_demorgan_i_fu_310_p1);
    brmerge5_i_fu_316_p2 <= (brmerge5_demorgan_i_fu_310_p2 xor ap_const_lv1_1);
    brmerge6_i_fu_322_p0 <= (0=>treset_in, others=>'-');
    brmerge6_i_fu_322_p2 <= (brmerge6_i_fu_322_p0 or brmerge5_i_fu_316_p2);
    channel_flag_1_fu_426_p0 <= (0=>tlast_user_in, others=>'-');
    channel_flag_1_fu_426_p2 <= (channel_flag_reg_237 or channel_flag_1_fu_426_p0);
    channel_new_1_fu_417_p0 <= (0=>tlast_user_in, others=>'-');
    channel_new_1_fu_417_p3 <= 
        p_s_fu_409_p3 when (channel_new_1_fu_417_p0(0) = '1') else 
        ap_const_lv16_0;

    channel_o_assign_proc : process(channel_i, ap_CS_fsm_state5, channel_new_1_fu_417_p3, channel_flag_1_fu_426_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (channel_flag_1_fu_426_p2 = ap_const_lv1_1))) then 
            channel_o <= channel_new_1_fu_417_p3;
        else 
            channel_o <= channel_i;
        end if; 
    end process;


    channel_o_ap_vld_assign_proc : process(ap_CS_fsm_state5, channel_flag_1_fu_426_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (channel_flag_1_fu_426_p2 = ap_const_lv1_1))) then 
            channel_o_ap_vld <= ap_const_logic_1;
        else 
            channel_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_ped_accum_reset_fu_250_ap_start <= grp_ped_accum_reset_fu_250_ap_start_reg;
    p_s_fu_409_p3 <= 
        ap_const_lv16_0 when (tmp_4_fu_403_p2(0) = '1') else 
        tmp_3_fu_397_p2;

    ped_array_address0_assign_proc : process(treset_in_read_read_fu_104_p2, ped_array_addr_reg_455, ap_CS_fsm_state3, grp_ped_accum_reset_fu_250_ped_array_address0, ap_CS_fsm_state2, tmp_fu_260_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ped_array_address0 <= ped_array_addr_reg_455;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ped_array_address0 <= tmp_fu_260_p1(6 - 1 downto 0);
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ped_array_address0 <= grp_ped_accum_reset_fu_250_ped_array_address0;
        else 
            ped_array_address0 <= "XXXXXX";
        end if; 
    end process;


    ped_array_ce0_assign_proc : process(treset_in_read_read_fu_104_p2, ap_CS_fsm_state3, grp_ped_accum_reset_fu_250_ped_array_ce0, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ped_array_ce0 <= ap_const_logic_1;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ped_array_ce0 <= grp_ped_accum_reset_fu_250_ped_array_ce0;
        else 
            ped_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    ped_array_d0_assign_proc : process(treset_in_read_read_fu_104_p2, grp_ped_accum_reset_fu_250_ped_array_d0, ap_CS_fsm_state2, ap_CS_fsm_state5, ped_new_fu_389_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ped_array_d0 <= ped_new_fu_389_p3;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ped_array_d0 <= grp_ped_accum_reset_fu_250_ped_array_d0;
        else 
            ped_array_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ped_array_we0_assign_proc : process(treset_in_read_read_fu_104_p2, grp_ped_accum_reset_fu_250_ped_array_we0, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ped_array_we0 <= ap_const_logic_1;
        elsif (((treset_in_read_read_fu_104_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ped_array_we0 <= grp_ped_accum_reset_fu_250_ped_array_we0;
        else 
            ped_array_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ped_new_fu_389_p3 <= 
        ped_new_1_reg_465 when (brmerge6_i_fu_322_p2(0) = '1') else 
        ped_val_1_i_fu_367_p3;
    ped_val_1_i_fu_367_p3 <= 
        tmp_9_i_fu_332_p2 when (tmp_8_i_fu_327_p2(0) = '1') else 
        tmp_1_read_i_fu_347_p3;
    tkeep_out <= tkeep_in;

    tkeep_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tkeep_out_ap_vld <= ap_const_logic_1;
        else 
            tkeep_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tlast_user_out <= tlast_user_in;

    tlast_user_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tlast_user_out_ap_vld <= ap_const_logic_1;
        else 
            tlast_user_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_304_p0 <= (0=>tvalid_in, others=>'-');
    tmp1_fu_304_p1 <= (0=>tkeep_in, others=>'-');
    tmp1_fu_304_p2 <= (tmp1_fu_304_p1 and tmp1_fu_304_p0);
    tmp_1_fu_354_p2 <= (tmp_i_2_fu_337_p2 or tmp_8_i_fu_327_p2);
    tmp_1_i_fu_342_p2 <= std_logic_vector(unsigned(ped_new_1_reg_465) + unsigned(ap_const_lv16_FFFF));
    tmp_1_read_i_fu_347_p3 <= 
        tmp_1_i_fu_342_p2 when (tmp_i_2_fu_337_p2(0) = '1') else 
        ped_new_1_reg_465;
    tmp_3_fu_397_p2 <= std_logic_vector(signed(channel_loc_reg_225) + signed(ap_const_lv16_1));
    tmp_4_fu_403_p2 <= "1" when (tmp_3_fu_397_p2 = ap_const_lv16_40) else "0";
    tmp_5_i_fu_271_p2 <= std_logic_vector(unsigned(accum_array_q0) + unsigned(ap_const_lv8_1));
    tmp_6_i_fu_277_p2 <= "1" when (signed(tdata) < signed(ped_array_q0)) else "0";
    tmp_7_i_fu_282_p2 <= std_logic_vector(unsigned(accum_array_q0) + unsigned(ap_const_lv8_FF));
    tmp_7_read1_i_fu_288_p3 <= 
        tmp_7_i_fu_282_p2 when (tmp_6_i_fu_277_p2(0) = '1') else 
        accum_array_q0;
    tmp_8_i_fu_327_p2 <= "1" when (signed(accum_1_i_reg_478) > signed(ap_const_lv8_9)) else "0";
    tmp_9_i_fu_332_p2 <= std_logic_vector(unsigned(ped_new_1_reg_465) + unsigned(ap_const_lv16_1));
        tmp_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(channel_loc_reg_225),64));

    tmp_i_2_fu_337_p2 <= "1" when (signed(accum_1_i_reg_478) < signed(ap_const_lv8_F7)) else "0";
    tmp_i_fu_266_p2 <= "1" when (signed(tdata) > signed(ped_array_q0)) else "0";
    tready_out <= tready_in;

    tready_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tready_out_ap_vld <= ap_const_logic_1;
        else 
            tready_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    treset_in_read_read_fu_104_p2 <= (0=>treset_in, others=>'-');
    treset_out <= treset_in;

    treset_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            treset_out_ap_vld <= ap_const_logic_1;
        else 
            treset_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tvalid_out <= tvalid_in;

    tvalid_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tvalid_out_ap_vld <= ap_const_logic_1;
        else 
            tvalid_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
