-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pedsub_HLS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tdata_i : IN STD_LOGIC_VECTOR (15 downto 0);
    tdata_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    tdata_o_ap_vld : OUT STD_LOGIC;
    accum_i : IN STD_LOGIC_VECTOR (15 downto 0);
    accum_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    accum_o_ap_vld : OUT STD_LOGIC;
    ped_i : IN STD_LOGIC_VECTOR (15 downto 0);
    ped_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    ped_o_ap_vld : OUT STD_LOGIC;
    tvalid_i : IN STD_LOGIC;
    tvalid_o : OUT STD_LOGIC;
    tvalid_o_ap_vld : OUT STD_LOGIC;
    tuser_i : IN STD_LOGIC;
    tuser_o : OUT STD_LOGIC;
    tuser_o_ap_vld : OUT STD_LOGIC;
    tkeep0_i : IN STD_LOGIC;
    tkeep0_o : OUT STD_LOGIC;
    tkeep0_o_ap_vld : OUT STD_LOGIC;
    tkeep1_i : IN STD_LOGIC;
    tkeep1_o : OUT STD_LOGIC;
    tkeep1_o_ap_vld : OUT STD_LOGIC;
    tready_i : IN STD_LOGIC;
    treset_i : IN STD_LOGIC;
    treset_o : OUT STD_LOGIC;
    treset_o_ap_vld : OUT STD_LOGIC;
    tlast_i : IN STD_LOGIC;
    tlast_o : OUT STD_LOGIC;
    tlast_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pedsub_HLS is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pedsub_HLS,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.700750,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=150,HLS_SYN_LUT=772,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_1F4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000111110100";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_A : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001010";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_FFF6 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv16_FE0C : STD_LOGIC_VECTOR (15 downto 0) := "1111111000001100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal accum_stored : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ped_stored : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tlast_reset : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal restore_count : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal tdata_previous : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal tvalid_previous : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tuser_previous : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tkeep_previous : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tlast_previous : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tlast_i_read_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal treset_i_read_read_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal treset_i_read_reg_718 : STD_LOGIC_VECTOR (0 downto 0);
    signal tready_i_read_read_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tready_i_read_reg_722 : STD_LOGIC_VECTOR (0 downto 0);
    signal tkeep1_i_read_reg_726 : STD_LOGIC_VECTOR (0 downto 0);
    signal tkeep0_i_read_reg_731 : STD_LOGIC_VECTOR (0 downto 0);
    signal tuser_i_read_reg_736 : STD_LOGIC_VECTOR (0 downto 0);
    signal tvalid_i_read_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal tdata_i_read_reg_746 : STD_LOGIC_VECTOR (15 downto 0);
    signal accum_stored_load_reg_752 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_stored_load_reg_757 : STD_LOGIC_VECTOR (15 downto 0);
    signal accum_i_assign_fu_514_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal accum_i_assign_reg_763 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_i_assign_fu_544_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_i_assign_reg_768 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_accum_stored_flag_8_reg_235 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal accum_stored_flag_6_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_accum_stored_new_8_phi_fu_252_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_accum_stored_new_8_reg_249 : STD_LOGIC_VECTOR (15 downto 0);
    signal accum_stored_new_6_fu_608_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_ped_stored_flag_8_reg_262 : STD_LOGIC_VECTOR (0 downto 0);
    signal ped_stored_flag_6_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_ped_stored_new_8_phi_fu_279_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_ped_stored_new_8_reg_276 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_stored_new_6_fu_624_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tlast_reset_flag_4_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tlast_reset_flag_1_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_tlast_reset_new_4_reg_303 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_demorgan_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_restore_count_flag_3_reg_316 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_restore_count_new_3_phi_fu_333_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_restore_count_new_3_reg_330 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_tmp_9_fu_580_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tdata_o_assign_1_fu_696_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_8_fu_702_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tdata_o_assign_fu_707_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_390_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_390_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge1_demorgan_fu_396_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_408_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_420_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_448_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_460_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal brmerge1_demorgan_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tmp_1_fu_426_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp6_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_tmp_5_fu_466_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp_fu_506_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp1_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_ped_i_assign_fu_434_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_7_ped_i_assign_fu_474_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp3_fu_536_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_fu_552_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_accum_stored_flag_4_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_i_accum_stored_fu_564_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_stored_flag_4_fu_528_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ped_i_ped_stored_new_4_fu_572_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal brmerge2_demorgan_fu_633_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_demorgan_fu_633_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_204 : BOOLEAN;
    signal ap_condition_136 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then
                accum_i_assign_reg_763 <= accum_i_assign_fu_514_p3;
                ped_i_assign_reg_768 <= ped_i_assign_fu_544_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 = ap_const_lv1_1))) then
                accum_stored <= ap_phi_mux_accum_stored_new_8_phi_fu_252_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                accum_stored_load_reg_752 <= accum_stored;
                ped_stored_load_reg_757 <= ped_stored;
                tdata_i_read_reg_746 <= tdata_i;
                tkeep0_i_read_reg_731 <= (0=>tkeep0_i, others=>'-');
                tkeep1_i_read_reg_726 <= (0=>tkeep1_i, others=>'-');
                tlast_i_read_reg_713 <= (0=>tlast_i, others=>'-');
                tready_i_read_reg_722 <= (0=>tready_i, others=>'-');
                treset_i_read_reg_718 <= (0=>treset_i, others=>'-');
                tuser_i_read_reg_736 <= (0=>tuser_i, others=>'-');
                tvalid_i_read_reg_741 <= (0=>tvalid_i, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 = ap_const_lv1_1))) then
                ped_stored <= ap_phi_mux_ped_stored_new_8_phi_fu_279_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 = ap_const_lv1_1))) then
                restore_count <= ap_phi_mux_restore_count_new_3_phi_fu_333_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((treset_i_read_read_fu_114_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1)))) then
                tdata_previous <= tdata_i;
                tkeep_previous <= (0=>tkeep0_i, others=>'-');
                tlast_previous <= (0=>tlast_i, others=>'-');
                tuser_previous <= (0=>tuser_i, others=>'-');
                tvalid_previous <= (0=>tvalid_i, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 = ap_const_lv1_1))) then
                tlast_reset <= ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    accum_i_accum_stored_fu_564_p3 <= 
        accum_i when (tmp_s_fu_558_p2(0) = '1') else 
        accum_i_assign_fu_514_p3;
    accum_i_assign_fu_514_p3 <= 
        p_tmp_5_fu_466_p3 when (sel_tmp6_fu_500_p2(0) = '1') else 
        sel_tmp_fu_506_p3;

    accum_o_assign_proc : process(treset_i_read_reg_718, tready_i_read_reg_722, accum_stored_load_reg_752, accum_i_assign_reg_763, ap_condition_204)
    begin
        if ((ap_const_boolean_1 = ap_condition_204)) then
            if ((treset_i_read_reg_718 = ap_const_lv1_1)) then 
                accum_o <= ap_const_lv16_0;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_1))) then 
                accum_o <= accum_i_assign_reg_763;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0))) then 
                accum_o <= accum_stored_load_reg_752;
            else 
                accum_o <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            accum_o <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    accum_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            accum_o_ap_vld <= ap_const_logic_1;
        else 
            accum_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    accum_stored_flag_6_fu_601_p2 <= (tmp3_fu_595_p2 or sel_tmp6_fu_500_p2);
    accum_stored_new_6_fu_608_p3 <= 
        accum_i_accum_stored_fu_564_p3 when (tlast_reset(0) = '1') else 
        accum_i_assign_fu_514_p3;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_136_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0)
    begin
                ap_condition_136 <= ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0));
    end process;


    ap_condition_204_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_01001)
    begin
                ap_condition_204 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_accum_stored_flag_8_reg_235, accum_stored_flag_6_fu_601_p2, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 <= ap_const_lv1_0;
            elsif (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 <= accum_stored_flag_6_fu_601_p2;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 <= ap_phi_reg_pp0_iter0_accum_stored_flag_8_reg_235;
            end if;
        else 
            ap_phi_mux_accum_stored_flag_8_phi_fu_238_p6 <= ap_phi_reg_pp0_iter0_accum_stored_flag_8_reg_235;
        end if; 
    end process;


    ap_phi_mux_accum_stored_new_8_phi_fu_252_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_accum_stored_new_8_reg_249, accum_stored_new_6_fu_608_p3, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_accum_stored_new_8_phi_fu_252_p6 <= accum_stored_new_6_fu_608_p3;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_accum_stored_new_8_phi_fu_252_p6 <= ap_const_lv16_0;
            else 
                ap_phi_mux_accum_stored_new_8_phi_fu_252_p6 <= ap_phi_reg_pp0_iter0_accum_stored_new_8_reg_249;
            end if;
        else 
            ap_phi_mux_accum_stored_new_8_phi_fu_252_p6 <= ap_phi_reg_pp0_iter0_accum_stored_new_8_reg_249;
        end if; 
    end process;


    ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_ped_stored_flag_8_reg_262, ped_stored_flag_6_fu_617_p2, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 <= ap_const_lv1_0;
            elsif (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 <= ped_stored_flag_6_fu_617_p2;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 <= ap_phi_reg_pp0_iter0_ped_stored_flag_8_reg_262;
            end if;
        else 
            ap_phi_mux_ped_stored_flag_8_phi_fu_265_p6 <= ap_phi_reg_pp0_iter0_ped_stored_flag_8_reg_262;
        end if; 
    end process;


    ap_phi_mux_ped_stored_new_8_phi_fu_279_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_ped_stored_new_8_reg_276, ped_stored_new_6_fu_624_p3, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_ped_stored_new_8_phi_fu_279_p6 <= ped_stored_new_6_fu_624_p3;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_ped_stored_new_8_phi_fu_279_p6 <= ap_const_lv16_1F4;
            else 
                ap_phi_mux_ped_stored_new_8_phi_fu_279_p6 <= ap_phi_reg_pp0_iter0_ped_stored_new_8_reg_276;
            end if;
        else 
            ap_phi_mux_ped_stored_new_8_phi_fu_279_p6 <= ap_phi_reg_pp0_iter0_ped_stored_new_8_reg_276;
        end if; 
    end process;


    ap_phi_mux_restore_count_flag_3_phi_fu_319_p6_assign_proc : process(tlast_reset, treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_restore_count_flag_3_reg_316, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 <= ap_const_lv1_0;
            elsif (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 <= tlast_reset;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 <= ap_phi_reg_pp0_iter0_restore_count_flag_3_reg_316;
            end if;
        else 
            ap_phi_mux_restore_count_flag_3_phi_fu_319_p6 <= ap_phi_reg_pp0_iter0_restore_count_flag_3_reg_316;
        end if; 
    end process;


    ap_phi_mux_restore_count_new_3_phi_fu_333_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_restore_count_new_3_reg_330, p_tmp_9_fu_580_p3, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_restore_count_new_3_phi_fu_333_p6 <= p_tmp_9_fu_580_p3;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_restore_count_new_3_phi_fu_333_p6 <= ap_const_lv8_0;
            else 
                ap_phi_mux_restore_count_new_3_phi_fu_333_p6 <= ap_phi_reg_pp0_iter0_restore_count_new_3_reg_330;
            end if;
        else 
            ap_phi_mux_restore_count_new_3_phi_fu_333_p6 <= ap_phi_reg_pp0_iter0_restore_count_new_3_reg_330;
        end if; 
    end process;


    ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_tlast_reset_flag_4_reg_289, p_tlast_reset_flag_1_fu_640_p2, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_0))) then 
                ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 <= ap_const_lv1_0;
            elsif (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 <= p_tlast_reset_flag_1_fu_640_p2;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 <= ap_const_lv1_1;
            else 
                ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 <= ap_phi_reg_pp0_iter0_tlast_reset_flag_4_reg_289;
            end if;
        else 
            ap_phi_mux_tlast_reset_flag_4_phi_fu_292_p6 <= ap_phi_reg_pp0_iter0_tlast_reset_flag_4_reg_289;
        end if; 
    end process;


    ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6_assign_proc : process(treset_i_read_read_fu_114_p2, tready_i_read_read_fu_120_p2, ap_phi_reg_pp0_iter0_tlast_reset_new_4_reg_303, brmerge2_demorgan_fu_633_p2, ap_condition_136)
    begin
        if ((ap_const_boolean_1 = ap_condition_136)) then
            if (((treset_i_read_read_fu_114_p2 = ap_const_lv1_0) and (tready_i_read_read_fu_120_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6 <= brmerge2_demorgan_fu_633_p2;
            elsif ((treset_i_read_read_fu_114_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6 <= ap_const_lv1_0;
            else 
                ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6 <= ap_phi_reg_pp0_iter0_tlast_reset_new_4_reg_303;
            end if;
        else 
            ap_phi_mux_tlast_reset_new_4_phi_fu_306_p6 <= ap_phi_reg_pp0_iter0_tlast_reset_new_4_reg_303;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_accum_stored_flag_8_reg_235 <= "X";
    ap_phi_reg_pp0_iter0_accum_stored_new_8_reg_249 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_ped_stored_flag_8_reg_262 <= "X";
    ap_phi_reg_pp0_iter0_ped_stored_new_8_reg_276 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_restore_count_flag_3_reg_316 <= "X";
    ap_phi_reg_pp0_iter0_restore_count_new_3_reg_330 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_tlast_reset_flag_4_reg_289 <= "X";
    ap_phi_reg_pp0_iter0_tlast_reset_new_4_reg_303 <= "X";

    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge1_demorgan_fu_396_p1 <= (0=>tvalid_i, others=>'-');
    brmerge1_demorgan_fu_396_p2 <= (tmp1_fu_390_p2 and brmerge1_demorgan_fu_396_p1);
    brmerge2_demorgan_fu_633_p0 <= (0=>tlast_i, others=>'-');
    brmerge2_demorgan_fu_633_p1 <= (0=>tuser_i, others=>'-');
    brmerge2_demorgan_fu_633_p2 <= (brmerge2_demorgan_fu_633_p1 and brmerge2_demorgan_fu_633_p0);
    p_accum_stored_flag_4_fu_589_p2 <= (tmp_s_fu_558_p2 and tlast_reset);
    p_tlast_reset_flag_1_fu_640_p2 <= (p_accum_stored_flag_4_fu_589_p2 or brmerge2_demorgan_fu_633_p2);
    p_tmp_1_fu_426_p3 <= 
        ap_const_lv16_0 when (tmp_2_fu_414_p2(0) = '1') else 
        tmp_1_fu_408_p2;
    p_tmp_5_fu_466_p3 <= 
        ap_const_lv16_0 when (tmp_6_fu_454_p2(0) = '1') else 
        tmp_5_fu_448_p2;
    p_tmp_9_fu_580_p3 <= 
        ap_const_lv8_0 when (tmp_s_fu_558_p2(0) = '1') else 
        tmp_9_fu_552_p2;
    ped_i_assign_fu_544_p3 <= 
        tmp_7_ped_i_assign_fu_474_p3 when (sel_tmp6_fu_500_p2(0) = '1') else 
        sel_tmp3_fu_536_p3;
    ped_i_ped_stored_new_4_fu_572_p3 <= 
        ped_i when (tmp_s_fu_558_p2(0) = '1') else 
        ped_i_assign_fu_544_p3;

    ped_o_assign_proc : process(treset_i_read_reg_718, tready_i_read_reg_722, ped_stored_load_reg_757, ped_i_assign_reg_768, ap_condition_204)
    begin
        if ((ap_const_boolean_1 = ap_condition_204)) then
            if ((treset_i_read_reg_718 = ap_const_lv1_1)) then 
                ped_o <= ap_const_lv16_1F4;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_1))) then 
                ped_o <= ped_i_assign_reg_768;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0))) then 
                ped_o <= ped_stored_load_reg_757;
            else 
                ped_o <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            ped_o <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ped_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ped_o_ap_vld <= ap_const_logic_1;
        else 
            ped_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ped_stored_flag_4_fu_528_p3 <= 
        tmp_6_fu_454_p2 when (sel_tmp6_fu_500_p2(0) = '1') else 
        sel_tmp1_fu_522_p2;
    ped_stored_flag_6_fu_617_p2 <= (ped_stored_flag_4_fu_528_p3 or p_accum_stored_flag_4_fu_589_p2);
    ped_stored_new_6_fu_624_p3 <= 
        ped_i_ped_stored_new_4_fu_572_p3 when (tlast_reset(0) = '1') else 
        ped_i_assign_fu_544_p3;
    sel_tmp1_fu_522_p2 <= (tmp_2_fu_414_p2 and sel_tmp2_fu_482_p2);
    sel_tmp2_fu_482_p2 <= (tmp_fu_402_p2 and brmerge1_demorgan_fu_396_p2);
    sel_tmp3_fu_536_p3 <= 
        tmp_4_ped_i_assign_fu_434_p3 when (sel_tmp2_fu_482_p2(0) = '1') else 
        ped_stored;
    sel_tmp4_fu_488_p2 <= (tmp_fu_402_p2 xor ap_const_lv1_1);
    sel_tmp6_fu_500_p2 <= (tmp2_fu_494_p2 and brmerge1_demorgan_fu_396_p2);
    sel_tmp_fu_506_p3 <= 
        p_tmp_1_fu_426_p3 when (sel_tmp2_fu_482_p2(0) = '1') else 
        accum_stored;

    tdata_o_assign_proc : process(treset_i_read_reg_718, tready_i_read_reg_722, tdata_o_assign_1_fu_696_p2, tmp_8_fu_702_p2, tdata_o_assign_fu_707_p2, ap_condition_204)
    begin
        if ((ap_const_boolean_1 = ap_condition_204)) then
            if ((treset_i_read_reg_718 = ap_const_lv1_1)) then 
                tdata_o <= tdata_o_assign_fu_707_p2;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_1))) then 
                tdata_o <= tmp_8_fu_702_p2;
            elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0))) then 
                tdata_o <= tdata_o_assign_1_fu_696_p2;
            else 
                tdata_o <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            tdata_o <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    tdata_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tdata_o_ap_vld <= ap_const_logic_1;
        else 
            tdata_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tdata_o_assign_1_fu_696_p2 <= std_logic_vector(unsigned(tdata_previous) - unsigned(ped_stored_load_reg_757));
    tdata_o_assign_fu_707_p2 <= std_logic_vector(unsigned(tdata_i_read_reg_746) + unsigned(ap_const_lv16_FE0C));

    tkeep0_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tkeep_previous, treset_i_read_reg_718, tready_i_read_reg_722, tkeep0_i_read_reg_731, ap_block_pp0_stage0_01001)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)))) then 
            tkeep0_o <= tkeep0_i_read_reg_731(0);
        elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tkeep0_o <= tkeep_previous(0);
        else 
            tkeep0_o <= 'X';
        end if; 
    end process;


    tkeep0_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tkeep0_o_ap_vld <= ap_const_logic_1;
        else 
            tkeep0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    tkeep1_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tkeep_previous, treset_i_read_reg_718, tready_i_read_reg_722, tkeep1_i_read_reg_726, ap_block_pp0_stage0_01001)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)))) then 
            tkeep1_o <= tkeep1_i_read_reg_726(0);
        elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tkeep1_o <= tkeep_previous(0);
        else 
            tkeep1_o <= 'X';
        end if; 
    end process;


    tkeep1_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tkeep1_o_ap_vld <= ap_const_logic_1;
        else 
            tkeep1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    tlast_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tlast_previous, tlast_i_read_reg_713, treset_i_read_reg_718, tready_i_read_reg_722, ap_block_pp0_stage0_01001)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)))) then 
            tlast_o <= tlast_i_read_reg_713(0);
        elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tlast_o <= tlast_previous(0);
        else 
            tlast_o <= 'X';
        end if; 
    end process;


    tlast_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tlast_o_ap_vld <= ap_const_logic_1;
        else 
            tlast_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_390_p0 <= (0=>tkeep0_i, others=>'-');
    tmp1_fu_390_p1 <= (0=>tkeep1_i, others=>'-');
    tmp1_fu_390_p2 <= (tmp1_fu_390_p1 and tmp1_fu_390_p0);
    tmp2_fu_494_p2 <= (tmp_3_fu_442_p2 and sel_tmp4_fu_488_p2);
    tmp3_fu_595_p2 <= (sel_tmp2_fu_482_p2 or p_accum_stored_flag_4_fu_589_p2);
    tmp_1_fu_408_p2 <= std_logic_vector(unsigned(accum_stored) + unsigned(ap_const_lv16_1));
    tmp_2_fu_414_p2 <= "1" when (tmp_1_fu_408_p2 = ap_const_lv16_A) else "0";
    tmp_3_fu_442_p2 <= "1" when (signed(ped_stored) > signed(tdata_i)) else "0";
    tmp_4_fu_420_p2 <= std_logic_vector(unsigned(ped_stored) + unsigned(ap_const_lv16_1));
    tmp_4_ped_i_assign_fu_434_p3 <= 
        tmp_4_fu_420_p2 when (tmp_2_fu_414_p2(0) = '1') else 
        ped_stored;
    tmp_5_fu_448_p2 <= std_logic_vector(unsigned(accum_stored) + unsigned(ap_const_lv16_FFFF));
    tmp_6_fu_454_p2 <= "1" when (tmp_5_fu_448_p2 = ap_const_lv16_FFF6) else "0";
    tmp_7_fu_460_p2 <= std_logic_vector(unsigned(ped_stored) + unsigned(ap_const_lv16_FFFF));
    tmp_7_ped_i_assign_fu_474_p3 <= 
        tmp_7_fu_460_p2 when (tmp_6_fu_454_p2(0) = '1') else 
        ped_stored;
    tmp_8_fu_702_p2 <= std_logic_vector(unsigned(tdata_i_read_reg_746) - unsigned(ped_i_assign_reg_768));
    tmp_9_fu_552_p2 <= std_logic_vector(unsigned(restore_count) + unsigned(ap_const_lv8_1));
    tmp_fu_402_p2 <= "1" when (signed(ped_stored) < signed(tdata_i)) else "0";
    tmp_s_fu_558_p2 <= "1" when (tmp_9_fu_552_p2 = ap_const_lv8_4) else "0";
    tready_i_read_read_fu_120_p2 <= (0=>tready_i, others=>'-');
    treset_i_read_read_fu_114_p2 <= (0=>treset_i, others=>'-');

    treset_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, treset_i_read_reg_718, tready_i_read_reg_722, ap_block_pp0_stage0_01001)
    begin
        if (((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            treset_o <= ap_const_logic_1;
        elsif ((((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            treset_o <= ap_const_logic_0;
        else 
            treset_o <= 'X';
        end if; 
    end process;


    treset_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            treset_o_ap_vld <= ap_const_logic_1;
        else 
            treset_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    tuser_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tuser_previous, treset_i_read_reg_718, tready_i_read_reg_722, tuser_i_read_reg_736, ap_block_pp0_stage0_01001)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)))) then 
            tuser_o <= tuser_i_read_reg_736(0);
        elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tuser_o <= tuser_previous(0);
        else 
            tuser_o <= 'X';
        end if; 
    end process;


    tuser_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tuser_o_ap_vld <= ap_const_logic_1;
        else 
            tuser_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    tvalid_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tvalid_previous, treset_i_read_reg_718, tready_i_read_reg_722, tvalid_i_read_reg_741, ap_block_pp0_stage0_01001)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)))) then 
            tvalid_o <= tvalid_i_read_reg_741(0);
        elsif (((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tvalid_o <= tvalid_previous(0);
        else 
            tvalid_o <= 'X';
        end if; 
    end process;


    tvalid_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, treset_i_read_reg_718, tready_i_read_reg_722)
    begin
        if ((((treset_i_read_reg_718 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tready_i_read_reg_722 = ap_const_lv1_1)) or ((treset_i_read_reg_718 = ap_const_lv1_0) and (tready_i_read_reg_722 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tvalid_o_ap_vld <= ap_const_logic_1;
        else 
            tvalid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
