-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pedsub_axi4s_test is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tdata_o_TREADY : IN STD_LOGIC;
    tdata_i_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    tdata_i_TVALID : IN STD_LOGIC;
    tdata_i_TREADY : OUT STD_LOGIC;
    tdata_o_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    tdata_o_TVALID : OUT STD_LOGIC;
    tdata_o_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    tdata_o_TUSER : OUT STD_LOGIC;
    tdata_o_TLAST : OUT STD_LOGIC );
end;


architecture behav of pedsub_axi4s_test is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pedsub_axi4s_test,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=110,HLS_SYN_LUT=208,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal tdata_i_0_vld_out : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tdata_o_data_V_1_ack_in : STD_LOGIC;
    signal tdata_o_keep_V_1_ack_in : STD_LOGIC;
    signal tdata_o_user_1_ack_in : STD_LOGIC;
    signal tdata_o_last_1_ack_in : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tdata_i_0_data_out : STD_LOGIC_VECTOR (23 downto 0);
    signal tdata_i_0_vld_in : STD_LOGIC;
    signal tdata_i_0_ack_in : STD_LOGIC;
    signal tdata_i_0_ack_out : STD_LOGIC;
    signal tdata_i_0_payload_A : STD_LOGIC_VECTOR (23 downto 0);
    signal tdata_i_0_payload_B : STD_LOGIC_VECTOR (23 downto 0);
    signal tdata_i_0_sel_rd : STD_LOGIC := '0';
    signal tdata_i_0_sel_wr : STD_LOGIC := '0';
    signal tdata_i_0_sel : STD_LOGIC;
    signal tdata_i_0_load_A : STD_LOGIC;
    signal tdata_i_0_load_B : STD_LOGIC;
    signal tdata_i_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdata_i_0_state_cmp_full : STD_LOGIC;
    signal tdata_o_data_V_1_data_out : STD_LOGIC_VECTOR (15 downto 0);
    signal tdata_o_data_V_1_vld_in : STD_LOGIC;
    signal tdata_o_data_V_1_vld_out : STD_LOGIC;
    signal tdata_o_data_V_1_ack_out : STD_LOGIC;
    signal tdata_o_data_V_1_payload_A : STD_LOGIC_VECTOR (15 downto 0);
    signal tdata_o_data_V_1_payload_B : STD_LOGIC_VECTOR (15 downto 0);
    signal tdata_o_data_V_1_sel_rd : STD_LOGIC := '0';
    signal tdata_o_data_V_1_sel_wr : STD_LOGIC := '0';
    signal tdata_o_data_V_1_sel : STD_LOGIC;
    signal tdata_o_data_V_1_load_A : STD_LOGIC;
    signal tdata_o_data_V_1_load_B : STD_LOGIC;
    signal tdata_o_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdata_o_data_V_1_state_cmp_full : STD_LOGIC;
    signal tdata_o_keep_V_1_data_out : STD_LOGIC_VECTOR (1 downto 0);
    signal tdata_o_keep_V_1_vld_in : STD_LOGIC;
    signal tdata_o_keep_V_1_vld_out : STD_LOGIC;
    signal tdata_o_keep_V_1_ack_out : STD_LOGIC;
    signal tdata_o_keep_V_1_payload_A : STD_LOGIC_VECTOR (1 downto 0);
    signal tdata_o_keep_V_1_payload_B : STD_LOGIC_VECTOR (1 downto 0);
    signal tdata_o_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal tdata_o_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal tdata_o_keep_V_1_sel : STD_LOGIC;
    signal tdata_o_keep_V_1_load_A : STD_LOGIC;
    signal tdata_o_keep_V_1_load_B : STD_LOGIC;
    signal tdata_o_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdata_o_keep_V_1_state_cmp_full : STD_LOGIC;
    signal tdata_o_user_1_data_out : STD_LOGIC;
    signal tdata_o_user_1_vld_in : STD_LOGIC;
    signal tdata_o_user_1_vld_out : STD_LOGIC;
    signal tdata_o_user_1_ack_out : STD_LOGIC;
    signal tdata_o_user_1_payload_A : STD_LOGIC;
    signal tdata_o_user_1_payload_B : STD_LOGIC;
    signal tdata_o_user_1_sel_rd : STD_LOGIC := '0';
    signal tdata_o_user_1_sel_wr : STD_LOGIC := '0';
    signal tdata_o_user_1_sel : STD_LOGIC;
    signal tdata_o_user_1_load_A : STD_LOGIC;
    signal tdata_o_user_1_load_B : STD_LOGIC;
    signal tdata_o_user_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdata_o_user_1_state_cmp_full : STD_LOGIC;
    signal tdata_o_last_1_data_out : STD_LOGIC;
    signal tdata_o_last_1_vld_in : STD_LOGIC;
    signal tdata_o_last_1_vld_out : STD_LOGIC;
    signal tdata_o_last_1_ack_out : STD_LOGIC;
    signal tdata_o_last_1_payload_A : STD_LOGIC;
    signal tdata_o_last_1_payload_B : STD_LOGIC;
    signal tdata_o_last_1_sel_rd : STD_LOGIC := '0';
    signal tdata_o_last_1_sel_wr : STD_LOGIC := '0';
    signal tdata_o_last_1_sel : STD_LOGIC;
    signal tdata_o_last_1_load_A : STD_LOGIC;
    signal tdata_o_last_1_load_B : STD_LOGIC;
    signal tdata_o_last_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal tdata_o_last_1_state_cmp_full : STD_LOGIC;
    signal tdata_i_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tdata_o_TDATA_blk_n : STD_LOGIC;
    signal tmp_fu_70_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    tdata_i_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_i_0_sel_rd <= ap_const_logic_0;
            else
                if (((tdata_i_0_ack_out = ap_const_logic_1) and (tdata_i_0_vld_out = ap_const_logic_1))) then 
                                        tdata_i_0_sel_rd <= not(tdata_i_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    tdata_i_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_i_0_sel_wr <= ap_const_logic_0;
            else
                if (((tdata_i_0_ack_in = ap_const_logic_1) and (tdata_i_0_vld_in = ap_const_logic_1))) then 
                                        tdata_i_0_sel_wr <= not(tdata_i_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    tdata_i_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_i_0_state <= ap_const_lv2_0;
            else
                if ((((tdata_i_0_state = ap_const_lv2_2) and (tdata_i_0_vld_in = ap_const_logic_0)) or ((tdata_i_0_state = ap_const_lv2_3) and (tdata_i_0_vld_in = ap_const_logic_0) and (tdata_i_0_ack_out = ap_const_logic_1)))) then 
                    tdata_i_0_state <= ap_const_lv2_2;
                elsif ((((tdata_i_0_state = ap_const_lv2_1) and (tdata_i_0_ack_out = ap_const_logic_0)) or ((tdata_i_0_state = ap_const_lv2_3) and (tdata_i_0_ack_out = ap_const_logic_0) and (tdata_i_0_vld_in = ap_const_logic_1)))) then 
                    tdata_i_0_state <= ap_const_lv2_1;
                elsif (((not(((tdata_i_0_vld_in = ap_const_logic_0) and (tdata_i_0_ack_out = ap_const_logic_1))) and not(((tdata_i_0_ack_out = ap_const_logic_0) and (tdata_i_0_vld_in = ap_const_logic_1))) and (tdata_i_0_state = ap_const_lv2_3)) or ((tdata_i_0_state = ap_const_lv2_1) and (tdata_i_0_ack_out = ap_const_logic_1)) or ((tdata_i_0_state = ap_const_lv2_2) and (tdata_i_0_vld_in = ap_const_logic_1)))) then 
                    tdata_i_0_state <= ap_const_lv2_3;
                else 
                    tdata_i_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    tdata_o_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((tdata_o_data_V_1_ack_out = ap_const_logic_1) and (tdata_o_data_V_1_vld_out = ap_const_logic_1))) then 
                                        tdata_o_data_V_1_sel_rd <= not(tdata_o_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((tdata_o_data_V_1_ack_in = ap_const_logic_1) and (tdata_o_data_V_1_vld_in = ap_const_logic_1))) then 
                                        tdata_o_data_V_1_sel_wr <= not(tdata_o_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((tdata_o_data_V_1_state = ap_const_lv2_2) and (tdata_o_data_V_1_vld_in = ap_const_logic_0)) or ((tdata_o_data_V_1_state = ap_const_lv2_3) and (tdata_o_data_V_1_vld_in = ap_const_logic_0) and (tdata_o_data_V_1_ack_out = ap_const_logic_1)))) then 
                    tdata_o_data_V_1_state <= ap_const_lv2_2;
                elsif ((((tdata_o_data_V_1_state = ap_const_lv2_1) and (tdata_o_data_V_1_ack_out = ap_const_logic_0)) or ((tdata_o_data_V_1_state = ap_const_lv2_3) and (tdata_o_data_V_1_ack_out = ap_const_logic_0) and (tdata_o_data_V_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((tdata_o_data_V_1_vld_in = ap_const_logic_0) and (tdata_o_data_V_1_ack_out = ap_const_logic_1))) and not(((tdata_o_data_V_1_ack_out = ap_const_logic_0) and (tdata_o_data_V_1_vld_in = ap_const_logic_1))) and (tdata_o_data_V_1_state = ap_const_lv2_3)) or ((tdata_o_data_V_1_state = ap_const_lv2_1) and (tdata_o_data_V_1_ack_out = ap_const_logic_1)) or ((tdata_o_data_V_1_state = ap_const_lv2_2) and (tdata_o_data_V_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_data_V_1_state <= ap_const_lv2_3;
                else 
                    tdata_o_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    tdata_o_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((tdata_o_keep_V_1_ack_out = ap_const_logic_1) and (tdata_o_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        tdata_o_keep_V_1_sel_rd <= not(tdata_o_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((tdata_o_keep_V_1_ack_in = ap_const_logic_1) and (tdata_o_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        tdata_o_keep_V_1_sel_wr <= not(tdata_o_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((tdata_o_keep_V_1_state = ap_const_lv2_2) and (tdata_o_keep_V_1_vld_in = ap_const_logic_0)) or ((tdata_o_keep_V_1_state = ap_const_lv2_3) and (tdata_o_keep_V_1_vld_in = ap_const_logic_0) and (tdata_o_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    tdata_o_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((tdata_o_keep_V_1_state = ap_const_lv2_1) and (tdata_o_keep_V_1_ack_out = ap_const_logic_0)) or ((tdata_o_keep_V_1_state = ap_const_lv2_3) and (tdata_o_keep_V_1_ack_out = ap_const_logic_0) and (tdata_o_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((tdata_o_keep_V_1_vld_in = ap_const_logic_0) and (tdata_o_keep_V_1_ack_out = ap_const_logic_1))) and not(((tdata_o_keep_V_1_ack_out = ap_const_logic_0) and (tdata_o_keep_V_1_vld_in = ap_const_logic_1))) and (tdata_o_keep_V_1_state = ap_const_lv2_3)) or ((tdata_o_keep_V_1_state = ap_const_lv2_1) and (tdata_o_keep_V_1_ack_out = ap_const_logic_1)) or ((tdata_o_keep_V_1_state = ap_const_lv2_2) and (tdata_o_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_keep_V_1_state <= ap_const_lv2_3;
                else 
                    tdata_o_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    tdata_o_last_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_last_1_sel_rd <= ap_const_logic_0;
            else
                if (((tdata_o_last_1_ack_out = ap_const_logic_1) and (tdata_o_last_1_vld_out = ap_const_logic_1))) then 
                                        tdata_o_last_1_sel_rd <= not(tdata_o_last_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_last_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_last_1_sel_wr <= ap_const_logic_0;
            else
                if (((tdata_o_last_1_ack_in = ap_const_logic_1) and (tdata_o_last_1_vld_in = ap_const_logic_1))) then 
                                        tdata_o_last_1_sel_wr <= not(tdata_o_last_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_last_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_last_1_state <= ap_const_lv2_0;
            else
                if ((((tdata_o_last_1_state = ap_const_lv2_2) and (tdata_o_last_1_vld_in = ap_const_logic_0)) or ((tdata_o_last_1_state = ap_const_lv2_3) and (tdata_o_last_1_vld_in = ap_const_logic_0) and (tdata_o_last_1_ack_out = ap_const_logic_1)))) then 
                    tdata_o_last_1_state <= ap_const_lv2_2;
                elsif ((((tdata_o_last_1_state = ap_const_lv2_1) and (tdata_o_last_1_ack_out = ap_const_logic_0)) or ((tdata_o_last_1_state = ap_const_lv2_3) and (tdata_o_last_1_ack_out = ap_const_logic_0) and (tdata_o_last_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_last_1_state <= ap_const_lv2_1;
                elsif (((not(((tdata_o_last_1_vld_in = ap_const_logic_0) and (tdata_o_last_1_ack_out = ap_const_logic_1))) and not(((tdata_o_last_1_ack_out = ap_const_logic_0) and (tdata_o_last_1_vld_in = ap_const_logic_1))) and (tdata_o_last_1_state = ap_const_lv2_3)) or ((tdata_o_last_1_state = ap_const_lv2_1) and (tdata_o_last_1_ack_out = ap_const_logic_1)) or ((tdata_o_last_1_state = ap_const_lv2_2) and (tdata_o_last_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_last_1_state <= ap_const_lv2_3;
                else 
                    tdata_o_last_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    tdata_o_user_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_user_1_sel_rd <= ap_const_logic_0;
            else
                if (((tdata_o_user_1_ack_out = ap_const_logic_1) and (tdata_o_user_1_vld_out = ap_const_logic_1))) then 
                                        tdata_o_user_1_sel_rd <= not(tdata_o_user_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_user_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_user_1_sel_wr <= ap_const_logic_0;
            else
                if (((tdata_o_user_1_ack_in = ap_const_logic_1) and (tdata_o_user_1_vld_in = ap_const_logic_1))) then 
                                        tdata_o_user_1_sel_wr <= not(tdata_o_user_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    tdata_o_user_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                tdata_o_user_1_state <= ap_const_lv2_0;
            else
                if ((((tdata_o_user_1_state = ap_const_lv2_2) and (tdata_o_user_1_vld_in = ap_const_logic_0)) or ((tdata_o_user_1_state = ap_const_lv2_3) and (tdata_o_user_1_vld_in = ap_const_logic_0) and (tdata_o_user_1_ack_out = ap_const_logic_1)))) then 
                    tdata_o_user_1_state <= ap_const_lv2_2;
                elsif ((((tdata_o_user_1_state = ap_const_lv2_1) and (tdata_o_user_1_ack_out = ap_const_logic_0)) or ((tdata_o_user_1_state = ap_const_lv2_3) and (tdata_o_user_1_ack_out = ap_const_logic_0) and (tdata_o_user_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_user_1_state <= ap_const_lv2_1;
                elsif (((not(((tdata_o_user_1_vld_in = ap_const_logic_0) and (tdata_o_user_1_ack_out = ap_const_logic_1))) and not(((tdata_o_user_1_ack_out = ap_const_logic_0) and (tdata_o_user_1_vld_in = ap_const_logic_1))) and (tdata_o_user_1_state = ap_const_lv2_3)) or ((tdata_o_user_1_state = ap_const_lv2_1) and (tdata_o_user_1_ack_out = ap_const_logic_1)) or ((tdata_o_user_1_state = ap_const_lv2_2) and (tdata_o_user_1_vld_in = ap_const_logic_1)))) then 
                    tdata_o_user_1_state <= ap_const_lv2_3;
                else 
                    tdata_o_user_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_i_0_load_A = ap_const_logic_1)) then
                tdata_i_0_payload_A <= tdata_i_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_i_0_load_B = ap_const_logic_1)) then
                tdata_i_0_payload_B <= tdata_i_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_data_V_1_load_A = ap_const_logic_1)) then
                tdata_o_data_V_1_payload_A <= tmp_fu_70_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_data_V_1_load_B = ap_const_logic_1)) then
                tdata_o_data_V_1_payload_B <= tmp_fu_70_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_keep_V_1_load_A = ap_const_logic_1)) then
                tdata_o_keep_V_1_payload_A <= tdata_i_0_data_out(17 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_keep_V_1_load_B = ap_const_logic_1)) then
                tdata_o_keep_V_1_payload_B <= tdata_i_0_data_out(17 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_last_1_load_A = ap_const_logic_1)) then
                tdata_o_last_1_payload_A <= tdata_i_0_data_out(19);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_last_1_load_B = ap_const_logic_1)) then
                tdata_o_last_1_payload_B <= tdata_i_0_data_out(19);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_user_1_load_A = ap_const_logic_1)) then
                tdata_o_user_1_payload_A <= tdata_i_0_data_out(18);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((tdata_o_user_1_load_B = ap_const_logic_1)) then
                tdata_o_user_1_payload_B <= tdata_i_0_data_out(18);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tdata_i_0_vld_out, tdata_o_data_V_1_ack_in, tdata_o_keep_V_1_ack_in, tdata_o_user_1_ack_in, tdata_o_last_1_ack_in)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((tdata_o_last_1_ack_in = ap_const_logic_0) or (tdata_o_user_1_ack_in = ap_const_logic_0) or (tdata_o_keep_V_1_ack_in = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (tdata_i_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tdata_i_0_vld_out, tdata_o_data_V_1_ack_in, tdata_o_keep_V_1_ack_in, tdata_o_user_1_ack_in, tdata_o_last_1_ack_in)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((tdata_o_last_1_ack_in = ap_const_logic_0) or (tdata_o_user_1_ack_in = ap_const_logic_0) or (tdata_o_keep_V_1_ack_in = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0) or (tdata_i_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter1, tdata_i_0_vld_out, tdata_o_data_V_1_ack_in, tdata_o_keep_V_1_ack_in, tdata_o_user_1_ack_in, tdata_o_last_1_ack_in)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((tdata_o_last_1_ack_in = ap_const_logic_0) or (tdata_o_user_1_ack_in = ap_const_logic_0) or (tdata_o_keep_V_1_ack_in = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0))) or ((ap_start = ap_const_logic_1) and ((ap_start = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0) or (tdata_i_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, tdata_i_0_vld_out)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start = ap_const_logic_0) or (tdata_i_0_vld_out = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(tdata_o_data_V_1_ack_in, tdata_o_keep_V_1_ack_in, tdata_o_user_1_ack_in, tdata_o_last_1_ack_in)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((tdata_o_last_1_ack_in = ap_const_logic_0) or (tdata_o_user_1_ack_in = ap_const_logic_0) or (tdata_o_keep_V_1_ack_in = ap_const_logic_0) or (tdata_o_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    tdata_i_0_ack_in <= tdata_i_0_state(1);

    tdata_i_0_ack_out_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_i_0_ack_out <= ap_const_logic_1;
        else 
            tdata_i_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    tdata_i_0_data_out_assign_proc : process(tdata_i_0_payload_A, tdata_i_0_payload_B, tdata_i_0_sel)
    begin
        if ((tdata_i_0_sel = ap_const_logic_1)) then 
            tdata_i_0_data_out <= tdata_i_0_payload_B;
        else 
            tdata_i_0_data_out <= tdata_i_0_payload_A;
        end if; 
    end process;

    tdata_i_0_load_A <= (tdata_i_0_state_cmp_full and not(tdata_i_0_sel_wr));
    tdata_i_0_load_B <= (tdata_i_0_state_cmp_full and tdata_i_0_sel_wr);
    tdata_i_0_sel <= tdata_i_0_sel_rd;
    tdata_i_0_state_cmp_full <= '0' when (tdata_i_0_state = ap_const_lv2_1) else '1';
    tdata_i_0_vld_in <= tdata_i_TVALID;
    tdata_i_0_vld_out <= tdata_i_0_state(0);

    tdata_i_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, tdata_i_0_state, ap_block_pp0_stage0)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_i_TDATA_blk_n <= tdata_i_0_state(0);
        else 
            tdata_i_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tdata_i_TREADY <= tdata_i_0_state(1);
    tdata_o_TDATA <= tdata_o_data_V_1_data_out;

    tdata_o_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, tdata_o_data_V_1_state, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            tdata_o_TDATA_blk_n <= tdata_o_data_V_1_state(1);
        else 
            tdata_o_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tdata_o_TKEEP <= tdata_o_keep_V_1_data_out;
    tdata_o_TLAST <= tdata_o_last_1_data_out;
    tdata_o_TUSER <= tdata_o_user_1_data_out;
    tdata_o_TVALID <= tdata_o_last_1_state(0);
    tdata_o_data_V_1_ack_in <= tdata_o_data_V_1_state(1);
    tdata_o_data_V_1_ack_out <= tdata_o_TREADY;

    tdata_o_data_V_1_data_out_assign_proc : process(tdata_o_data_V_1_payload_A, tdata_o_data_V_1_payload_B, tdata_o_data_V_1_sel)
    begin
        if ((tdata_o_data_V_1_sel = ap_const_logic_1)) then 
            tdata_o_data_V_1_data_out <= tdata_o_data_V_1_payload_B;
        else 
            tdata_o_data_V_1_data_out <= tdata_o_data_V_1_payload_A;
        end if; 
    end process;

    tdata_o_data_V_1_load_A <= (tdata_o_data_V_1_state_cmp_full and not(tdata_o_data_V_1_sel_wr));
    tdata_o_data_V_1_load_B <= (tdata_o_data_V_1_state_cmp_full and tdata_o_data_V_1_sel_wr);
    tdata_o_data_V_1_sel <= tdata_o_data_V_1_sel_rd;
    tdata_o_data_V_1_state_cmp_full <= '0' when (tdata_o_data_V_1_state = ap_const_lv2_1) else '1';

    tdata_o_data_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_o_data_V_1_vld_in <= ap_const_logic_1;
        else 
            tdata_o_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    tdata_o_data_V_1_vld_out <= tdata_o_data_V_1_state(0);
    tdata_o_keep_V_1_ack_in <= tdata_o_keep_V_1_state(1);
    tdata_o_keep_V_1_ack_out <= tdata_o_TREADY;

    tdata_o_keep_V_1_data_out_assign_proc : process(tdata_o_keep_V_1_payload_A, tdata_o_keep_V_1_payload_B, tdata_o_keep_V_1_sel)
    begin
        if ((tdata_o_keep_V_1_sel = ap_const_logic_1)) then 
            tdata_o_keep_V_1_data_out <= tdata_o_keep_V_1_payload_B;
        else 
            tdata_o_keep_V_1_data_out <= tdata_o_keep_V_1_payload_A;
        end if; 
    end process;

    tdata_o_keep_V_1_load_A <= (tdata_o_keep_V_1_state_cmp_full and not(tdata_o_keep_V_1_sel_wr));
    tdata_o_keep_V_1_load_B <= (tdata_o_keep_V_1_state_cmp_full and tdata_o_keep_V_1_sel_wr);
    tdata_o_keep_V_1_sel <= tdata_o_keep_V_1_sel_rd;
    tdata_o_keep_V_1_state_cmp_full <= '0' when (tdata_o_keep_V_1_state = ap_const_lv2_1) else '1';

    tdata_o_keep_V_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_o_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            tdata_o_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    tdata_o_keep_V_1_vld_out <= tdata_o_keep_V_1_state(0);
    tdata_o_last_1_ack_in <= tdata_o_last_1_state(1);
    tdata_o_last_1_ack_out <= tdata_o_TREADY;

    tdata_o_last_1_data_out_assign_proc : process(tdata_o_last_1_payload_A, tdata_o_last_1_payload_B, tdata_o_last_1_sel)
    begin
        if ((tdata_o_last_1_sel = ap_const_logic_1)) then 
            tdata_o_last_1_data_out <= tdata_o_last_1_payload_B;
        else 
            tdata_o_last_1_data_out <= tdata_o_last_1_payload_A;
        end if; 
    end process;

    tdata_o_last_1_load_A <= (tdata_o_last_1_state_cmp_full and not(tdata_o_last_1_sel_wr));
    tdata_o_last_1_load_B <= (tdata_o_last_1_state_cmp_full and tdata_o_last_1_sel_wr);
    tdata_o_last_1_sel <= tdata_o_last_1_sel_rd;
    tdata_o_last_1_state_cmp_full <= '0' when (tdata_o_last_1_state = ap_const_lv2_1) else '1';

    tdata_o_last_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_o_last_1_vld_in <= ap_const_logic_1;
        else 
            tdata_o_last_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    tdata_o_last_1_vld_out <= tdata_o_last_1_state(0);
    tdata_o_user_1_ack_in <= tdata_o_user_1_state(1);
    tdata_o_user_1_ack_out <= tdata_o_TREADY;

    tdata_o_user_1_data_out_assign_proc : process(tdata_o_user_1_payload_A, tdata_o_user_1_payload_B, tdata_o_user_1_sel)
    begin
        if ((tdata_o_user_1_sel = ap_const_logic_1)) then 
            tdata_o_user_1_data_out <= tdata_o_user_1_payload_B;
        else 
            tdata_o_user_1_data_out <= tdata_o_user_1_payload_A;
        end if; 
    end process;

    tdata_o_user_1_load_A <= (tdata_o_user_1_state_cmp_full and not(tdata_o_user_1_sel_wr));
    tdata_o_user_1_load_B <= (tdata_o_user_1_state_cmp_full and tdata_o_user_1_sel_wr);
    tdata_o_user_1_sel <= tdata_o_user_1_sel_rd;
    tdata_o_user_1_state_cmp_full <= '0' when (tdata_o_user_1_state = ap_const_lv2_1) else '1';

    tdata_o_user_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tdata_o_user_1_vld_in <= ap_const_logic_1;
        else 
            tdata_o_user_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    tdata_o_user_1_vld_out <= tdata_o_user_1_state(0);
    tmp_fu_70_p1 <= tdata_i_0_data_out(16 - 1 downto 0);
end behav;
