// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ped_alg_HH_
#define _ped_alg_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ped_alg : public sc_module {
    // Port declarations 33
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > ped_val_i;
    sc_out< sc_lv<16> > ped_val_o;
    sc_out< sc_logic > ped_val_o_ap_vld;
    sc_in< sc_lv<8> > accum_i;
    sc_out< sc_lv<8> > accum_o;
    sc_out< sc_logic > accum_o_ap_vld;
    sc_out< sc_lv<16> > ADC;
    sc_out< sc_logic > ADC_ap_vld;
    sc_in< sc_lv<16> > tdata;
    sc_in< sc_logic > tvalid;
    sc_in< sc_logic > tkeep0;
    sc_in< sc_logic > tkeep1;
    sc_in< sc_logic > tready;
    sc_in< sc_logic > treset;
    sc_in< sc_logic > tlast;
    sc_out< sc_logic > tvalid_out;
    sc_out< sc_logic > tvalid_out_ap_vld;
    sc_out< sc_logic > tkeep0_out;
    sc_out< sc_logic > tkeep0_out_ap_vld;
    sc_out< sc_logic > tkeep1_out;
    sc_out< sc_logic > tkeep1_out_ap_vld;
    sc_out< sc_logic > tready_out;
    sc_out< sc_logic > tready_out_ap_vld;
    sc_out< sc_logic > treset_out;
    sc_out< sc_logic > treset_out_ap_vld;
    sc_out< sc_logic > tlast_out;
    sc_out< sc_logic > tlast_out_ap_vld;


    // Module declarations
    ped_alg(sc_module_name name);
    SC_HAS_PROCESS(ped_alg);

    ~ped_alg();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > or_ln32_fu_266_p2;
    sc_signal< sc_lv<1> > or_ln32_reg_383;
    sc_signal< sc_lv<16> > zext_ln37_fu_276_p1;
    sc_signal< sc_lv<16> > zext_ln37_reg_387;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln43_1_fu_312_p2;
    sc_signal< sc_lv<8> > select_ln43_fu_318_p3;
    sc_signal< sc_lv<16> > add_ln59_fu_338_p2;
    sc_signal< sc_lv<1> > icmp_ln53_fu_326_p2;
    sc_signal< sc_lv<1> > icmp_ln58_fu_332_p2;
    sc_signal< sc_lv<16> > add_ln54_fu_345_p2;
    sc_signal< sc_lv<16> > ped_val_load_3_reg_202;
    sc_signal< sc_lv<1> > ap_phi_mux_accum_flag_2_phi_fu_217_p6;
    sc_signal< sc_lv<1> > accum_flag_2_reg_213;
    sc_signal< sc_lv<8> > accum_new_2_reg_227;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > and_ln32_fu_242_p0;
    sc_signal< sc_lv<1> > and_ln32_fu_242_p1;
    sc_signal< sc_lv<1> > and_ln32_1_fu_248_p0;
    sc_signal< sc_lv<1> > and_ln32_1_fu_248_p1;
    sc_signal< sc_lv<1> > and_ln32_1_fu_248_p2;
    sc_signal< sc_lv<1> > and_ln32_fu_242_p2;
    sc_signal< sc_lv<1> > and_ln32_2_fu_254_p2;
    sc_signal< sc_lv<1> > or_ln32_fu_266_p0;
    sc_signal< sc_lv<1> > xor_ln32_fu_260_p2;
    sc_signal< sc_lv<12> > trunc_fu_272_p1;
    sc_signal< sc_lv<1> > icmp_ln47_fu_292_p2;
    sc_signal< sc_lv<8> > add_ln48_fu_298_p2;
    sc_signal< sc_lv<1> > icmp_ln43_fu_280_p2;
    sc_signal< sc_lv<8> > add_ln44_fu_286_p2;
    sc_signal< sc_lv<8> > select_ln47_fu_304_p3;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_9;
    static const sc_lv<8> ap_const_lv8_F7;
    static const sc_lv<16> ap_const_lv16_FFFF;
    static const sc_lv<16> ap_const_lv16_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ADC();
    void thread_ADC_ap_vld();
    void thread_accum_o();
    void thread_accum_o_ap_vld();
    void thread_add_ln44_fu_286_p2();
    void thread_add_ln48_fu_298_p2();
    void thread_add_ln54_fu_345_p2();
    void thread_add_ln59_fu_338_p2();
    void thread_and_ln32_1_fu_248_p0();
    void thread_and_ln32_1_fu_248_p1();
    void thread_and_ln32_1_fu_248_p2();
    void thread_and_ln32_2_fu_254_p2();
    void thread_and_ln32_fu_242_p0();
    void thread_and_ln32_fu_242_p1();
    void thread_and_ln32_fu_242_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_accum_flag_2_phi_fu_217_p6();
    void thread_ap_ready();
    void thread_icmp_ln43_1_fu_312_p2();
    void thread_icmp_ln43_fu_280_p2();
    void thread_icmp_ln47_fu_292_p2();
    void thread_icmp_ln53_fu_326_p2();
    void thread_icmp_ln58_fu_332_p2();
    void thread_or_ln32_fu_266_p0();
    void thread_or_ln32_fu_266_p2();
    void thread_ped_val_o();
    void thread_ped_val_o_ap_vld();
    void thread_select_ln43_fu_318_p3();
    void thread_select_ln47_fu_304_p3();
    void thread_tkeep0_out();
    void thread_tkeep0_out_ap_vld();
    void thread_tkeep1_out();
    void thread_tkeep1_out_ap_vld();
    void thread_tlast_out();
    void thread_tlast_out_ap_vld();
    void thread_tready_out();
    void thread_tready_out_ap_vld();
    void thread_treset_out();
    void thread_treset_out_ap_vld();
    void thread_trunc_fu_272_p1();
    void thread_tvalid_out();
    void thread_tvalid_out_ap_vld();
    void thread_xor_ln32_fu_260_p2();
    void thread_zext_ln37_fu_276_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
