-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ped_alg is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ped_val_i : IN STD_LOGIC_VECTOR (15 downto 0);
    ped_val_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    ped_val_o_ap_vld : OUT STD_LOGIC;
    accum_i : IN STD_LOGIC_VECTOR (7 downto 0);
    accum_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    accum_o_ap_vld : OUT STD_LOGIC;
    ADC : OUT STD_LOGIC_VECTOR (15 downto 0);
    ADC_ap_vld : OUT STD_LOGIC;
    tdata : IN STD_LOGIC_VECTOR (15 downto 0);
    tvalid : IN STD_LOGIC;
    tkeep0 : IN STD_LOGIC;
    tkeep1 : IN STD_LOGIC;
    tready : IN STD_LOGIC;
    treset : IN STD_LOGIC;
    tlast : IN STD_LOGIC;
    tvalid_out : OUT STD_LOGIC;
    tvalid_out_ap_vld : OUT STD_LOGIC;
    tkeep0_out : OUT STD_LOGIC;
    tkeep0_out_ap_vld : OUT STD_LOGIC;
    tkeep1_out : OUT STD_LOGIC;
    tkeep1_out_ap_vld : OUT STD_LOGIC;
    tready_out : OUT STD_LOGIC;
    tready_out_ap_vld : OUT STD_LOGIC;
    treset_out : OUT STD_LOGIC;
    treset_out_ap_vld : OUT STD_LOGIC;
    tlast_out : OUT STD_LOGIC;
    tlast_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ped_alg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ped_alg,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.018750,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=31,HLS_SYN_LUT=276,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_F7 : STD_LOGIC_VECTOR (7 downto 0) := "11110111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal brmerge5_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_reg_375 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_11_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_new_1_fu_310_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_330_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_337_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ped_val_load_3_reg_202 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_accum_flag_2_phi_fu_217_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_flag_2_reg_213 : STD_LOGIC_VECTOR (0 downto 0);
    signal accum_new_2_reg_227 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp1_fu_242_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_242_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_248_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_248_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_demorgan_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_fu_266_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_290_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_278_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_accum_load_fu_296_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    accum_flag_2_reg_213_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_6_fu_324_p2 = ap_const_lv1_0) and (tmp_4_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                accum_flag_2_reg_213 <= tmp_11_fu_304_p2;
            elsif ((((tmp_4_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((tmp_6_fu_324_p2 = ap_const_lv1_1) and (tmp_4_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                accum_flag_2_reg_213 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    accum_new_2_reg_227_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_6_fu_324_p2 = ap_const_lv1_0) and (tmp_4_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                accum_new_2_reg_227 <= accum_new_1_fu_310_p3;
            elsif ((((tmp_4_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((tmp_6_fu_324_p2 = ap_const_lv1_1) and (tmp_4_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
                accum_new_2_reg_227 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    ped_val_load_3_reg_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if (((tmp_6_fu_324_p2 = ap_const_lv1_0) and (tmp_4_fu_318_p2 = ap_const_lv1_0))) then 
                    ped_val_load_3_reg_202 <= ped_val_i;
                elsif (((tmp_6_fu_324_p2 = ap_const_lv1_1) and (tmp_4_fu_318_p2 = ap_const_lv1_0))) then 
                    ped_val_load_3_reg_202 <= tmp_7_fu_330_p2;
                elsif ((tmp_4_fu_318_p2 = ap_const_lv1_1)) then 
                    ped_val_load_3_reg_202 <= tmp_5_fu_337_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                brmerge5_reg_375 <= brmerge5_fu_266_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, brmerge5_fu_266_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((brmerge5_fu_266_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((brmerge5_fu_266_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ADC <= std_logic_vector(unsigned(tdata) - unsigned(ped_val_load_3_reg_202));

    ADC_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ADC_ap_vld <= ap_const_logic_1;
        else 
            ADC_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    accum_new_1_fu_310_p3 <= 
        tmp_1_fu_278_p2 when (tmp_fu_272_p2(0) = '1') else 
        tmp_3_accum_load_fu_296_p3;

    accum_o_assign_proc : process(accum_i, brmerge5_reg_375, ap_phi_mux_accum_flag_2_phi_fu_217_p6, accum_new_2_reg_227, ap_CS_fsm_state5)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_217_p6 = ap_const_lv1_1) and (brmerge5_reg_375 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            accum_o <= accum_new_2_reg_227;
        else 
            accum_o <= accum_i;
        end if; 
    end process;


    accum_o_ap_vld_assign_proc : process(brmerge5_reg_375, ap_phi_mux_accum_flag_2_phi_fu_217_p6, ap_CS_fsm_state5)
    begin
        if (((ap_phi_mux_accum_flag_2_phi_fu_217_p6 = ap_const_lv1_1) and (brmerge5_reg_375 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            accum_o_ap_vld <= ap_const_logic_1;
        else 
            accum_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_accum_flag_2_phi_fu_217_p6 <= accum_flag_2_reg_213;

    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge4_demorgan_fu_254_p2 <= (tmp2_fu_248_p2 and tmp1_fu_242_p2);
    brmerge4_fu_260_p2 <= (brmerge4_demorgan_fu_254_p2 xor ap_const_lv1_1);
    brmerge5_fu_266_p0 <= (0=>treset, others=>'-');
    brmerge5_fu_266_p2 <= (brmerge5_fu_266_p0 or brmerge4_fu_260_p2);

    ped_val_o_assign_proc : process(ped_val_i, ap_CS_fsm_state3, tmp_7_fu_330_p2, tmp_4_fu_318_p2, tmp_6_fu_324_p2, tmp_5_fu_337_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((tmp_4_fu_318_p2 = ap_const_lv1_1)) then 
                ped_val_o <= tmp_5_fu_337_p2;
            elsif (((tmp_6_fu_324_p2 = ap_const_lv1_1) and (tmp_4_fu_318_p2 = ap_const_lv1_0))) then 
                ped_val_o <= tmp_7_fu_330_p2;
            else 
                ped_val_o <= ped_val_i;
            end if;
        else 
            ped_val_o <= ped_val_i;
        end if; 
    end process;


    ped_val_o_ap_vld_assign_proc : process(ap_CS_fsm_state3, tmp_4_fu_318_p2, tmp_6_fu_324_p2)
    begin
        if ((((tmp_4_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((tmp_6_fu_324_p2 = ap_const_lv1_1) and (tmp_4_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ped_val_o_ap_vld <= ap_const_logic_1;
        else 
            ped_val_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tkeep0_out <= tkeep0;

    tkeep0_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tkeep0_out_ap_vld <= ap_const_logic_1;
        else 
            tkeep0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tkeep1_out <= tkeep1;

    tkeep1_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tkeep1_out_ap_vld <= ap_const_logic_1;
        else 
            tkeep1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tlast_out <= tlast;

    tlast_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tlast_out_ap_vld <= ap_const_logic_1;
        else 
            tlast_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_242_p0 <= (0=>tready, others=>'-');
    tmp1_fu_242_p1 <= (0=>tvalid, others=>'-');
    tmp1_fu_242_p2 <= (tmp1_fu_242_p1 and tmp1_fu_242_p0);
    tmp2_fu_248_p0 <= (0=>tkeep0, others=>'-');
    tmp2_fu_248_p1 <= (0=>tkeep1, others=>'-');
    tmp2_fu_248_p2 <= (tmp2_fu_248_p1 and tmp2_fu_248_p0);
    tmp_11_fu_304_p2 <= "0" when (tdata = ped_val_i) else "1";
    tmp_1_fu_278_p2 <= std_logic_vector(unsigned(accum_i) + unsigned(ap_const_lv8_1));
    tmp_2_fu_284_p2 <= "1" when (signed(tdata) < signed(ped_val_i)) else "0";
    tmp_3_accum_load_fu_296_p3 <= 
        tmp_3_fu_290_p2 when (tmp_2_fu_284_p2(0) = '1') else 
        accum_i;
    tmp_3_fu_290_p2 <= std_logic_vector(unsigned(accum_i) + unsigned(ap_const_lv8_FF));
    tmp_4_fu_318_p2 <= "1" when (signed(accum_new_1_fu_310_p3) > signed(ap_const_lv8_9)) else "0";
    tmp_5_fu_337_p2 <= std_logic_vector(unsigned(ped_val_i) + unsigned(ap_const_lv16_1));
    tmp_6_fu_324_p2 <= "1" when (signed(accum_new_1_fu_310_p3) < signed(ap_const_lv8_F7)) else "0";
    tmp_7_fu_330_p2 <= std_logic_vector(unsigned(ped_val_i) + unsigned(ap_const_lv16_FFFF));
    tmp_fu_272_p2 <= "1" when (signed(tdata) > signed(ped_val_i)) else "0";
    tready_out <= tready;

    tready_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tready_out_ap_vld <= ap_const_logic_1;
        else 
            tready_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    treset_out <= treset;

    treset_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            treset_out_ap_vld <= ap_const_logic_1;
        else 
            treset_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tvalid_out <= tvalid;

    tvalid_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tvalid_out_ap_vld <= ap_const_logic_1;
        else 
            tvalid_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
