// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ped_alg_HH_
#define _ped_alg_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ped_alg : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > ped_val_i;
    sc_out< sc_lv<16> > ped_val_o;
    sc_out< sc_logic > ped_val_o_ap_vld;
    sc_in< sc_lv<8> > accum_i;
    sc_out< sc_lv<8> > accum_o;
    sc_out< sc_logic > accum_o_ap_vld;
    sc_out< sc_lv<16> > ADC;
    sc_out< sc_logic > ADC_ap_vld;
    sc_in< sc_lv<16> > tdata;
    sc_in< sc_logic > tvalid;
    sc_in< sc_logic > tkeep0;
    sc_in< sc_logic > tkeep1;
    sc_in< sc_logic > tready;


    // Module declarations
    ped_alg(sc_module_name name);
    SC_HAS_PROCESS(ped_alg);

    ~ped_alg();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > or_ln24_1_fu_195_p2;
    sc_signal< sc_lv<1> > or_ln24_1_reg_286;
    sc_signal< sc_lv<12> > trunc_fu_201_p1;
    sc_signal< sc_lv<12> > trunc_reg_290;
    sc_signal< sc_lv<16> > zext_ln29_fu_205_p1;
    sc_signal< sc_lv<16> > zext_ln29_reg_295;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln35_1_fu_240_p2;
    sc_signal< sc_lv<8> > select_ln35_fu_246_p3;
    sc_signal< sc_lv<16> > add_ln51_fu_266_p2;
    sc_signal< sc_lv<1> > icmp_ln45_fu_254_p2;
    sc_signal< sc_lv<1> > icmp_ln50_fu_260_p2;
    sc_signal< sc_lv<16> > add_ln46_fu_273_p2;
    sc_signal< sc_lv<16> > ped_val_load_3_reg_131;
    sc_signal< sc_lv<1> > ap_phi_mux_accum_flag_2_phi_fu_146_p6;
    sc_signal< sc_lv<1> > accum_flag_2_reg_142;
    sc_signal< sc_lv<8> > accum_new_2_reg_156;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > xor_ln24_fu_171_p0;
    sc_signal< sc_lv<1> > or_ln24_fu_177_p0;
    sc_signal< sc_lv<1> > xor_ln24_fu_171_p2;
    sc_signal< sc_lv<1> > and_ln24_fu_183_p0;
    sc_signal< sc_lv<1> > and_ln24_fu_183_p1;
    sc_signal< sc_lv<1> > and_ln24_fu_183_p2;
    sc_signal< sc_lv<1> > or_ln24_fu_177_p2;
    sc_signal< sc_lv<1> > xor_ln24_1_fu_189_p2;
    sc_signal< sc_lv<1> > icmp_ln39_fu_220_p2;
    sc_signal< sc_lv<8> > add_ln40_fu_226_p2;
    sc_signal< sc_lv<1> > icmp_ln35_fu_208_p2;
    sc_signal< sc_lv<8> > add_ln36_fu_214_p2;
    sc_signal< sc_lv<8> > select_ln39_fu_232_p3;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<8> ap_const_lv8_9;
    static const sc_lv<8> ap_const_lv8_F7;
    static const sc_lv<16> ap_const_lv16_FFFF;
    static const sc_lv<16> ap_const_lv16_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ADC();
    void thread_ADC_ap_vld();
    void thread_accum_o();
    void thread_accum_o_ap_vld();
    void thread_add_ln36_fu_214_p2();
    void thread_add_ln40_fu_226_p2();
    void thread_add_ln46_fu_273_p2();
    void thread_add_ln51_fu_266_p2();
    void thread_and_ln24_fu_183_p0();
    void thread_and_ln24_fu_183_p1();
    void thread_and_ln24_fu_183_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_accum_flag_2_phi_fu_146_p6();
    void thread_ap_ready();
    void thread_icmp_ln35_1_fu_240_p2();
    void thread_icmp_ln35_fu_208_p2();
    void thread_icmp_ln39_fu_220_p2();
    void thread_icmp_ln45_fu_254_p2();
    void thread_icmp_ln50_fu_260_p2();
    void thread_or_ln24_1_fu_195_p2();
    void thread_or_ln24_fu_177_p0();
    void thread_or_ln24_fu_177_p2();
    void thread_ped_val_o();
    void thread_ped_val_o_ap_vld();
    void thread_select_ln35_fu_246_p3();
    void thread_select_ln39_fu_232_p3();
    void thread_trunc_fu_201_p1();
    void thread_xor_ln24_1_fu_189_p2();
    void thread_xor_ln24_fu_171_p0();
    void thread_xor_ln24_fu_171_p2();
    void thread_zext_ln29_fu_205_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
