// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ped_alg_HH_
#define _ped_alg_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ped_alg : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > ped_val_i;
    sc_out< sc_lv<32> > ped_val_o;
    sc_out< sc_logic > ped_val_o_ap_vld;
    sc_in< sc_lv<32> > accum_i;
    sc_out< sc_lv<32> > accum_o;
    sc_out< sc_logic > accum_o_ap_vld;
    sc_in< sc_lv<32> > ADC_i;
    sc_out< sc_lv<32> > ADC_o;
    sc_out< sc_logic > ADC_o_ap_vld;


    // Module declarations
    ped_alg(sc_module_name name);
    SC_HAS_PROCESS(ped_alg);

    ~ped_alg();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > ADC_read_reg_203;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln17_1_fu_157_p2;
    sc_signal< sc_lv<32> > select_ln17_fu_163_p3;
    sc_signal< sc_lv<32> > add_ln34_fu_183_p2;
    sc_signal< sc_lv<1> > icmp_ln27_fu_171_p2;
    sc_signal< sc_lv<1> > icmp_ln33_fu_177_p2;
    sc_signal< sc_lv<32> > add_ln28_fu_190_p2;
    sc_signal< sc_lv<1> > ap_phi_mux_accum_flag_2_phi_fu_89_p6;
    sc_signal< sc_lv<1> > accum_flag_2_reg_85;
    sc_signal< sc_lv<32> > accum_new_2_reg_99;
    sc_signal< sc_lv<32> > ped_val_load_3_reg_114;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln21_fu_137_p2;
    sc_signal< sc_lv<32> > add_ln22_fu_143_p2;
    sc_signal< sc_lv<1> > icmp_ln17_fu_125_p2;
    sc_signal< sc_lv<32> > add_ln18_fu_131_p2;
    sc_signal< sc_lv<32> > select_ln21_fu_149_p3;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_FFFFFFF7;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ADC_o();
    void thread_ADC_o_ap_vld();
    void thread_accum_o();
    void thread_accum_o_ap_vld();
    void thread_add_ln18_fu_131_p2();
    void thread_add_ln22_fu_143_p2();
    void thread_add_ln28_fu_190_p2();
    void thread_add_ln34_fu_183_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_accum_flag_2_phi_fu_89_p6();
    void thread_ap_ready();
    void thread_icmp_ln17_1_fu_157_p2();
    void thread_icmp_ln17_fu_125_p2();
    void thread_icmp_ln21_fu_137_p2();
    void thread_icmp_ln27_fu_171_p2();
    void thread_icmp_ln33_fu_177_p2();
    void thread_ped_val_o();
    void thread_ped_val_o_ap_vld();
    void thread_select_ln17_fu_163_p3();
    void thread_select_ln21_fu_149_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
